Repository MinecraftForge/MinecraftForge, pull requests merged in 2018-03, with the labels that each got.

#4675 Make lookupFluidForBlock work for flowing water and lava
  src/main/java/net/minecraftforge/fluids/FluidRegistry.java
Labels: 1.12, Feature

#4806 Fix some IResources being leaked
  src/main/java/net/minecraftforge/client/model/ModelDynBucket.java
  src/main/java/net/minecraftforge/client/model/animation/ModelBlockAnimation.java
  src/main/java/net/minecraftforge/client/model/b3d/B3DLoader.java
  src/main/java/net/minecraftforge/client/model/obj/OBJLoader.java
  src/main/java/net/minecraftforge/common/model/animation/AnimationStateMachine.java
Labels: 1.12, Assigned, Bug

#4765 Fixed sound engine crash when stopping streaming sounds
  src/main/java/net/minecraftforge/fml/common/asm/transformers/SoundEngineFixTransformer.java
  src/main/java/net/minecraftforge/fml/relauncher/FMLCorePlugin.java
Labels: 1.12, Assigned, Vanilla Bug

#4810 Add creator mod ID for modded enchanted books, potions, arrows, and spawn eggs
  patches/minecraft/net/minecraft/item/Item.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.12, Feature

#4700 Cleaner TileEntityItemStackRenderers
  patches/minecraft/net/minecraft/client/renderer/ChestRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/RenderItem.java.patch
  patches/minecraft/net/minecraft/item/Item.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: 1.12, Assigned, Feature
