Repository MinecraftForge/MinecraftForge, pull requests merged in 2018-02, with the labels that each got.

#4734 Clean up some GUI code and change magic numbers to GL constants
  src/main/java/net/minecraftforge/fml/client/GuiModList.java
  src/main/java/net/minecraftforge/fml/client/GuiScrollingList.java
  src/main/java/net/minecraftforge/fml/client/config/GuiUtils.java
Labels: 1.12, Cleanup

#4738 Directly insert byte data to BufferBuilder, closes #4722
  patches/minecraft/net/minecraft/client/renderer/BufferBuilder.java.patch
  src/test/java/net/minecraftforge/test/BufferBuilderExpansionTest.java
Labels: 1.12, Assigned, Feature

#4749 Don't cull generated item models with non-default GUI transform
  src/main/java/net/minecraftforge/client/model/BakedItemModel.java
Labels: 1.12, Assigned, Bug

#4690 Fix incorrect dimension ID being used for maps
  patches/minecraft/net/minecraft/item/ItemMap.java.patch
Labels: 1.12, Assigned, Bug

#4761 Improve the "Mod rejections" error message when connecting to a server
  src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java
  src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeClientState.java
  src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeServerState.java
  src/main/java/net/minecraftforge/fml/common/network/internal/FMLNetworkHandler.java
  src/main/java/net/minecraftforge/fml/common/network/internal/NetworkModHolder.java
Labels: 1.12, Assigned, Feature

#4689 Prevent various vanilla blocks from loading unloaded chunks
  patches/minecraft/net/minecraft/block/BlockCactus.java.patch
  patches/minecraft/net/minecraft/block/BlockCrops.java.patch
  patches/minecraft/net/minecraft/block/BlockDynamicLiquid.java.patch
  patches/minecraft/net/minecraft/block/BlockFire.java.patch
  patches/minecraft/net/minecraft/block/BlockGrass.java.patch
  patches/minecraft/net/minecraft/block/BlockLeaves.java.patch
  patches/minecraft/net/minecraft/block/BlockMycelium.java.patch
  patches/minecraft/net/minecraft/block/BlockSapling.java.patch
  patches/minecraft/net/minecraft/block/BlockStem.java.patch
  patches/minecraft/net/minecraft/block/BlockVine.java.patch
  patches/minecraft/net/minecraft/tileentity/TileEntityChest.java.patch
  patches/minecraft/net/minecraft/village/Village.java.patch
  patches/minecraft/net/minecraft/village/VillageCollection.java.patch
  patches/minecraft/net/minecraft/world/WorldServer.java.patch
Labels: 1.12, Assigned, Performance

#4711 Improve how smooth lighting code handles translucency
  src/main/java/net/minecraftforge/client/model/pipeline/BlockInfo.java
Labels: 1.12, Assigned, Rendering
