Repository MinecraftForge/MinecraftForge, pull requests merged in 2018-10, with the labels that each got.

#5152 Add a notification event for handling game rule changes
  patches/minecraft/net/minecraft/command/CommandGameRule.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/GameRuleChangeEvent.java
Labels: 1.12, Assigned, Feature

#5177 Fixed incorrect vanilla biome entries in BiomeDictionary
  src/main/java/net/minecraftforge/common/BiomeDictionary.java
Labels: 1.12, Bug

#5185 Fix diffuse lighting being broken on vanilla pipeline
  patches/minecraft/net/minecraft/client/renderer/block/model/FaceBakery.java.patch
Labels: 1.13, Bug

#5180 Make Forge-provided default transforms accessible to custom models
  src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java
Labels: 1.12, Feature, Rendering

#5192 Add missing license headers.
  src/main/java/net/minecraftforge/fml/LoadingFailedException.java
  src/main/java/net/minecraftforge/fml/MavenVersionStringHelper.java
  src/main/java/net/minecraftforge/fml/TextComponentMessageFormatHandler.java
  src/main/java/net/minecraftforge/fml/client/gui/GuiButtonClickConsumer.java
  src/main/java/net/minecraftforge/fml/client/gui/LoadingErrorScreen.java
  src/main/java/net/minecraftforge/fml/loading/EarlyLoadingException.java
  src/main/java/net/minecraftforge/fml/loading/MavenVersionAdapter.java
  src/main/java/net/minecraftforge/server/ServerMain.java
  src/main/java/net/minecraftforge/versions/mcp/MCPVersion.java
Labels: 1.13, Assigned, Cleanup
