Repository MinecraftForge/MinecraftForge, pull requests merged in 2018-07, with the labels that each got.

#5007 Fix giveItemToPlayer creating item entities with incorrect contents
  src/main/java/net/minecraftforge/items/ItemHandlerHelper.java
Labels: 1.12, Bug

#4970 Write full class name in undefined packet error messages
  src/main/java/net/minecraftforge/fml/common/network/FMLIndexedMessageToMessageCodec.java
Labels: 1.12, Feature

#5006 Move some test mods into appropriate packages
  src/test/java/net/minecraftforge/debug/block/PortalSpawnEventTest.java
  src/test/java/net/minecraftforge/debug/entity/living/AttackEventTest.java
  src/test/java/net/minecraftforge/debug/entity/living/MobGriefingEventTest.java
  src/test/java/net/minecraftforge/debug/fluid/FluidPlaceBlockEventTest.java
  src/test/java/net/minecraftforge/debug/gameplay/GiveItemToPlayerTest.java
  src/test/java/net/minecraftforge/debug/network/TrackingTargetTest.java
  src/test/java/net/minecraftforge/debug/world/ChunkWatchEventTest.java
  src/test/java/net/minecraftforge/debug/world/WorldProviderCanSleepAtTest.java
Labels: 1.12, Cleanup

#5010 Change some client hooks to use GlStateManager functions
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: 1.12, Cleanup

#4861 Fix potential deadlock when chunkload raises non-IO exception
  src/main/java/net/minecraftforge/common/chunkio/ChunkIOExecutor.java
  src/main/java/net/minecraftforge/common/chunkio/ChunkIOProvider.java
  src/main/java/net/minecraftforge/common/chunkio/ChunkIOThreadPoolExecutor.java
Labels: 1.12, Assigned, Bug

#4978 Clean up and improve ICapabilityProvider javadocs
  src/main/java/net/minecraftforge/common/capabilities/ICapabilityProvider.java
Labels: 1.12, Cleanup

#5016 Check use item result before calling onItemUseFirst.
  patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch
  src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
Labels: 1.12, Assigned, Bug

#5015 Use itemstack in LivingEntityUseItemEvent.Finish before it was used
  patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch
  src/main/java/net/minecraftforge/event/entity/living/LivingEntityUseItemEvent.java
Labels: 1.12, Assigned, Bug

#4952 Add support for FluidStack-dependant colouring to Forge bucket
  src/main/java/net/minecraftforge/client/FluidContainerColorer.java
  src/main/java/net/minecraftforge/client/ForgeClientHandler.java
  src/main/java/net/minecraftforge/client/model/ItemTextureQuadConverter.java
  src/main/java/net/minecraftforge/client/model/ModelDynBucket.java
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
  src/main/java/net/minecraftforge/common/ForgeModContainer.java
  src/main/resources/assets/forge/blockstates/dynbucket.json
Labels: 1.12, Assigned, Bug

#5024 Allow configuring log levels using system properties.
  src/main/resources/log4j2.xml
  src/main/resources/log4j2_server.xml
Labels: 1.12, Feature

#4763 Update Forge fluid model
  patches/minecraft/net/minecraft/block/Block.java.patch
  patches/minecraft/net/minecraft/client/renderer/ActiveRenderInfo.java.patch
  src/main/java/net/minecraftforge/client/model/ModelDynBucket.java
  src/main/java/net/minecraftforge/client/model/ModelFluid.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/property/PropertyFloat.java
  src/main/java/net/minecraftforge/fluids/BlockFluidBase.java
  src/main/java/net/minecraftforge/fluids/BlockFluidClassic.java
  src/main/java/net/minecraftforge/fluids/Fluid.java
  src/main/java/net/minecraftforge/fluids/FluidRegistry.java
  src/test/java/net/minecraftforge/debug/block/MaterialFogColorTest.java
  src/test/java/net/minecraftforge/debug/client/model/ModelFluidTest.java
  src/test/java/net/minecraftforge/debug/fluid/ColoredFluidTest.java
  src/test/java/net/minecraftforge/debug/fluid/FluidPlacementTest.java
Labels: 1.12, Assigned, Bug

#5036 Make doors equal
  src/main/java/net/minecraftforge/oredict/OreDictionary.java
Labels: 1.12, Assigned, Feature

#5034 CreativeTabs#getBackgroundImage
  patches/minecraft/net/minecraft/client/gui/inventory/GuiContainerCreative.java.patch
  patches/minecraft/net/minecraft/creativetab/CreativeTabs.java.patch
Labels: 1.12, Assigned, Feature

#5033 Add functionality in IItemHandler to test if a slot can accept an item
  src/main/java/net/minecraftforge/items/IItemHandler.java
  src/main/java/net/minecraftforge/items/ItemStackHandler.java
  src/main/java/net/minecraftforge/items/SlotItemHandler.java
  src/main/java/net/minecraftforge/items/VanillaDoubleChestItemHandler.java
  src/main/java/net/minecraftforge/items/wrapper/CombinedInvWrapper.java
  src/main/java/net/minecraftforge/items/wrapper/EmptyHandler.java
  src/main/java/net/minecraftforge/items/wrapper/EntityEquipmentInvWrapper.java
  src/main/java/net/minecraftforge/items/wrapper/InvWrapper.java
  src/main/java/net/minecraftforge/items/wrapper/RangedWrapper.java
  src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java
Labels: 1.12, Assigned, Feature

#5029 Fire colour events for mesa and swamp biomes
  patches/minecraft/net/minecraft/world/biome/BiomeMesa.java.patch
  patches/minecraft/net/minecraft/world/biome/BiomeSwamp.java.patch
Labels: 1.12, Assigned, Bug

#5011 Improve crash report details
  patches/minecraft/net/minecraft/client/renderer/RenderItem.java.patch
  patches/minecraft/net/minecraft/crash/CrashReportCategory.java.patch
  patches/minecraft/net/minecraft/entity/player/InventoryPlayer.java.patch
  patches/minecraft/net/minecraft/tileentity/TileEntity.java.patch
  patches/minecraft/net/minecraft/world/World.java.patch
Labels: 1.12, Assigned, Feature

#4658 Resource type sensitive ResourceManager reloading
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/gui/GuiLanguage.java.patch
  patches/minecraft/net/minecraft/client/gui/recipebook/GuiRecipeBook.java.patch
  patches/minecraft/net/minecraft/client/resources/IResourceManagerReloadListener.java.patch
  patches/minecraft/net/minecraft/client/resources/SimpleReloadableResourceManager.java.patch
  patches/minecraft/net/minecraft/client/settings/GameSettings.java.patch
  src/main/java/net/minecraftforge/client/CloudRenderer.java
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/model/ICustomModelLoader.java
  src/main/java/net/minecraftforge/client/resource/IResourceType.java
  src/main/java/net/minecraftforge/client/resource/ISelectiveResourceReloadListener.java
  src/main/java/net/minecraftforge/client/resource/ReloadRequirements.java
  src/main/java/net/minecraftforge/client/resource/SelectiveReloadStateHandler.java
  src/main/java/net/minecraftforge/client/resource/VanillaResourceType.java
  src/main/java/net/minecraftforge/client/resource/package-info.java
  src/main/java/net/minecraftforge/common/ForgeModContainer.java
  src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java
  src/main/resources/assets/forge/lang/en_US.lang
Labels: 1.12, Assigned, Feature, Performance

#4973 Allow custom SpawnPlacementType registration
  patches/minecraft/net/minecraft/entity/EntityLiving.java.patch
  patches/minecraft/net/minecraft/entity/EntitySpawnPlacementRegistry.java.patch
  patches/minecraft/net/minecraft/world/WorldEntitySpawner.java.patch
  src/main/java/net/minecraftforge/common/util/EnumHelper.java
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/entity/living/CustomSpawnPlacementTest.java
  src/test/java/net/minecraftforge/test/EnumHelperTest.java
Labels: 1.12, Assigned, Feature

#5017 Add function to lookup model location for an ItemStack
  src/main/java/net/minecraftforge/client/ItemModelMesherForge.java
  src/main/resources/forge_at.cfg
Labels: 1.12, Assigned, Feature
