Repository MinecraftForge/MinecraftForge, pull requests merged in 2018-11, with the labels that each got.

#5233 Fix patch from #5160 setting rotation as well as position
  patches/minecraft/net/minecraft/network/NetHandlerPlayServer.java.patch
Labels: 1.12, Bug

#5127 Remove synthetic lambda methods only in method body of SideOnly methods
  src/main/java/net/minecraftforge/fml/common/asm/transformers/SideTransformer.java
Labels: 1.12, Bug

#5235 Fix defaulted registries returning null keys
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
  src/main/java/net/minecraftforge/registries/NamespacedDefaultedWrapper.java
Labels: 1.12, Bug

#5225 Fix crash when placing furnaces or brewing stands in 1.13
  patches/minecraft/net/minecraft/tileentity/TileEntityBrewingStand.java.patch
  patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
  src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java
Labels: 1.13

#5107 Fix SleepingTimeCheck in EntityPlayer.trySleep
  patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
Labels: 1.12, Assigned, Bug

#5200 Re-add some missing villager profession patches
  patches/minecraft/net/minecraft/entity/monster/EntityZombieVillager.java.patch
  patches/minecraft/net/minecraft/world/gen/structure/StructureVillagePieces.java.patch
  src/main/java/net/minecraftforge/fml/common/registry/VillagerRegistry.java
Labels: 1.12, Assigned, Bug

#5210 Fix missing string interpolation parameters in log messages
  src/main/java/net/minecraftforge/common/config/ConfigManager.java
  src/main/java/net/minecraftforge/fml/common/FMLCommonHandler.java
  src/main/java/net/minecraftforge/fml/common/FMLModContainer.java
  src/main/java/net/minecraftforge/fml/common/ILanguageAdapter.java
  src/main/java/net/minecraftforge/fml/common/ObfuscationReflectionHelper.java
  src/main/java/net/minecraftforge/fml/common/ProxyInjector.java
  src/main/java/net/minecraftforge/fml/common/discovery/JarDiscoverer.java
  src/main/java/net/minecraftforge/fml/common/network/internal/NetworkModHolder.java
  src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java
Labels: 1.12, Assigned, Bug, Cleanup

#4853 Improve reflection helper methods
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java
  src/main/java/net/minecraftforge/fml/common/FMLCommonHandler.java
  src/main/java/net/minecraftforge/fml/common/ObfuscationReflectionHelper.java
  src/main/java/net/minecraftforge/fml/common/patcher/ClassPatchManager.java
  src/main/java/net/minecraftforge/fml/common/registry/EntityEntryBuilder.java
  src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java
  src/main/java/net/minecraftforge/fml/relauncher/FMLLaunchHandler.java
  src/main/java/net/minecraftforge/fml/relauncher/ReflectionHelper.java
  src/main/java/net/minecraftforge/fml/server/FMLServerHandler.java
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
Labels: 1.12, Assigned, Cleanup

#5078 Fix inaccurate main thread name shown in client log
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: 1.12, Assigned, Bug

#5227 Clean up logged mod states
  src/main/java/net/minecraftforge/fml/common/LoadController.java
Labels: 1.12, Assigned, Cleanup

#5206 Fix small logic omissions in BlockFluidBase
  src/main/java/net/minecraftforge/fluids/BlockFluidBase.java
  src/main/java/net/minecraftforge/fluids/BlockFluidClassic.java
Labels: 1.12, Assigned, Bug, Regression

#5047 Allow item model rendering to detect emissive quads and render them properly
  patches/minecraft/net/minecraft/client/renderer/RenderItem.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/common/ForgeModContainer.java
  src/main/resources/assets/forge/lang/en_US.lang
  src/main/resources/forge_at.cfg
Labels: 1.12, Assigned, Feature

#5214 Fixed error message
  src/main/java/net/minecraftforge/registries/ObjectHolderRef.java
Labels: 1.12, Bug

#5111 Improve context provided by potion icon rendering hooks
  patches/minecraft/net/minecraft/client/gui/GuiIngame.java.patch
  patches/minecraft/net/minecraft/client/renderer/InventoryEffectRenderer.java.patch
  patches/minecraft/net/minecraft/potion/Potion.java.patch
  src/test/java/net/minecraftforge/debug/gameplay/PotionRegistryTest.java
Labels: 1.12, Assigned, Feature, Rendering

#5226 Don't catch exceptions from server starting events
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/fml/common/Loader.java
Labels: 1.12, Assigned, Bug
