Repository MinecraftForge/MinecraftForge, pull requests merged in 2018-05, with the labels that each got.

#4909 Clean up broken aliases caused by 4894 bug.
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
Labels: 1.12, Bug

#4914 Fix MC-12269
  patches/minecraft/net/minecraft/client/particle/Particle.java.patch
Labels: 1.12, Vanilla Bug

#4922 Clean up mod dependency checking code
  src/main/java/net/minecraftforge/fml/common/Loader.java
Labels: 1.12, Cleanup

#4869 Give immediate and complete error messages when there is a crash during startup
  src/main/java/com/google/common/eventbus/FMLThrowingEventBus.java
  src/main/java/net/minecraftforge/fml/client/CustomModLoadingErrorDisplayException.java
  src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java
  src/main/java/net/minecraftforge/fml/client/IDisplayableError.java
  src/main/java/net/minecraftforge/fml/common/DuplicateModsFoundException.java
  src/main/java/net/minecraftforge/fml/common/FMLModContainer.java
  src/main/java/net/minecraftforge/fml/common/LoadController.java
  src/main/java/net/minecraftforge/fml/common/Loader.java
  src/main/java/net/minecraftforge/fml/common/MissingModsException.java
  src/main/java/net/minecraftforge/fml/common/MultipleModsErrored.java
  src/main/java/net/minecraftforge/fml/common/WrongMinecraftVersionException.java
  src/main/java/net/minecraftforge/fml/common/toposort/ModSortingException.java
Labels: 1.12, Assigned, Bug

#4826 Add supports for redirects when doing mod version checks
  src/main/java/net/minecraftforge/common/ForgeVersion.java
Labels: 1.12, Assigned, Bug

#4642 Fix some light-emitting blocks letting light through (MC-119932)
  patches/minecraft/net/minecraft/world/World.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#4732 Allow custom models to have per-state lighting
  patches/minecraft/net/minecraft/client/renderer/BlockModelRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/model/IBakedModel.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/model/SimpleBakedModel.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/model/WeightedBakedModel.java.patch
  src/main/java/net/minecraftforge/client/model/BakedModelWrapper.java
  src/main/java/net/minecraftforge/client/model/MultiLayerModel.java
  src/main/java/net/minecraftforge/client/model/MultiModel.java
  src/main/java/net/minecraftforge/client/model/PerspectiveMapWrapper.java
Labels: 1.12, Assigned, Feature

#4735 Add an event to control nether portal formation
  patches/minecraft/net/minecraft/block/BlockPortal.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/world/BlockEvent.java
  src/test/java/net/minecraftforge/debug/PortalSpawnEventTest.java
Labels: 1.12, Assigned, Feature

#4681 Check name used for tile entity registrations
  src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/IForgeRegistryEntry.java
  src/test/java/net/minecraftforge/debug/client/rendering/FastTESRTransparentTest.java
Labels: 1.12, Assigned, Cleanup

#4745 Add functionality for replacing more crops
  patches/minecraft/net/minecraft/entity/ai/EntityAIHarvestFarmland.java.patch
Labels: 1.12, Assigned, Feature

#4809 Change composite models to fetch quads from submodels using full context
  src/main/java/net/minecraftforge/client/model/MultiLayerModel.java
  src/main/java/net/minecraftforge/client/model/MultiModel.java
Labels: 1.12, Assigned, Bug

#4880 Fix memory leaks in EnchantmentHelper (MC-128547)
  patches/minecraft/net/minecraft/enchantment/EnchantmentHelper.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#4882 Fix server-side data not being released
  patches/minecraft/net/minecraft/server/MinecraftServer.java.patch
  src/main/java/net/minecraftforge/fml/common/network/FMLEmbeddedChannel.java
  src/main/java/net/minecraftforge/fml/common/network/NetworkRegistry.java
  src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java
Labels: 1.12, Assigned, Vanilla Bug

#4925 Added formatting support for status messages
  src/main/java/net/minecraftforge/client/GuiIngameForge.java
Labels: 1.12, Assigned, Feature

#4766 Fixes parameter inconsistency in IFieldWrapper (Fixes #4325)
  src/main/java/net/minecraftforge/common/config/ConfigManager.java
  src/main/java/net/minecraftforge/common/config/FieldWrapper.java
  src/main/java/net/minecraftforge/common/config/IFieldWrapper.java
  src/main/java/net/minecraftforge/common/config/ITypeAdapter.java
  src/test/java/net/minecraftforge/debug/mod/ConfigAnnotationTest.java
Labels: 1.12, Bug

#4791 Reuse multipart model instances across variants
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
Labels: 1.12, Performance

#4942 Fix crash from search tree processing invalid recipes
  src/main/java/net/minecraftforge/common/ForgeModContainer.java
Labels: 1.12, Bug
