Repository MinecraftForge/MinecraftForge, pull requests merged in 2018-04, with the labels that each got.

#4823 Fix entities sometimes not rendering when out-of-world (MC-73139)
  patches/minecraft/net/minecraft/client/renderer/RenderGlobal.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#4807 Add fences and fence gates to ore dictionary
  src/main/java/net/minecraftforge/oredict/OreDictionary.java
Labels: 1.12, Assigned, Feature

#4805 Added chunk instance to ChunkWatchEvent
  patches/minecraft/net/minecraft/server/management/PlayerChunkMapEntry.java.patch
  src/main/java/net/minecraftforge/event/world/ChunkWatchEvent.java
  src/test/java/net/minecraftforge/debug/ChunkWatchWorldTest.java
Labels: 1.12, Assigned, Feature

#4786 In ItemStack, switch Item.getItemFromBlock(Blocks.AIR) to Items.AIR
  patches/minecraft/net/minecraft/item/ItemStack.java.patch
Labels: 1.12, Assigned, Performance

#4784 Fix for the player inadvertently being removed from the Entity Tracke…
  patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#4781 Fix some block connection logic not matching vanilla
  patches/minecraft/net/minecraft/block/BlockFence.java.patch
  patches/minecraft/net/minecraft/block/BlockFenceGate.java.patch
  patches/minecraft/net/minecraft/block/BlockPane.java.patch
  patches/minecraft/net/minecraft/block/BlockWall.java.patch
Labels: 1.12, Assigned, Bug

#4753 Reduce memory usage of model transforms
  patches/minecraft/net/minecraft/client/renderer/block/model/ModelRotation.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/model/BakedItemModel.java
  src/main/java/net/minecraftforge/client/model/BlockStateLoader.java
  src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java
  src/main/java/net/minecraftforge/client/model/ItemTextureQuadConverter.java
  src/main/java/net/minecraftforge/client/model/ModelFluid.java
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
  src/main/java/net/minecraftforge/client/model/MultiModel.java
  src/main/java/net/minecraftforge/client/model/PerspectiveMapWrapper.java
  src/main/java/net/minecraftforge/client/model/animation/ModelBlockAnimation.java
  src/main/java/net/minecraftforge/common/model/TRSRTransformation.java
Labels: 1.12, Assigned, Performance

#4742 Fix FMLCommonHandler#exitJava printing useless/wrong calling info
  src/main/java/net/minecraftforge/fml/common/FMLCommonHandler.java
Labels: 1.12, Assigned, Bug

#4741 Add a WorldProvider#canSleepHere() method
  patches/minecraft/net/minecraft/block/BlockBed.java.patch
  patches/minecraft/net/minecraft/world/WorldProvider.java.patch
  src/test/java/net/minecraftforge/debug/CanSleepAtTest.java
Labels: 1.12, Assigned, Feature

#4728 Fixed Spectator mode particles and sounds computed from where you have been before (MC-46445)
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/audio/SoundHandler.java.patch
  patches/minecraft/net/minecraft/client/audio/SoundManager.java.patch
  patches/minecraft/net/minecraft/client/renderer/ActiveRenderInfo.java.patch
  patches/minecraft/net/minecraft/client/renderer/EntityRenderer.java.patch
  src/main/resources/forge.exc
Labels: 1.12, Assigned, Vanilla Bug

#4720 Update ItemHandlerHelper.giveItemToPlayer to allow player who picked up the item to hear the sound as well
  src/main/java/net/minecraftforge/items/ItemHandlerHelper.java
  src/test/java/net/minecraftforge/debug/GiveItemToPlayerTest.java
Labels: 1.12, Assigned, Bug

#4714 Explain the watchdog's Error
  patches/minecraft/net/minecraft/server/dedicated/ServerHangWatchdog.java.patch
Labels: 1.12, Assigned, Feature

#4710 Create event for overriding mob griefing behaviour
  patches/minecraft/net/minecraft/entity/Entity.java.patch
  patches/minecraft/net/minecraft/entity/EntityLiving.java.patch
  patches/minecraft/net/minecraft/entity/ai/EntityAIBreakDoor.java.patch
  patches/minecraft/net/minecraft/entity/ai/EntityAIEatGrass.java.patch
  patches/minecraft/net/minecraft/entity/ai/EntityAIHarvestFarmland.java.patch
  patches/minecraft/net/minecraft/entity/boss/EntityDragon.java.patch
  patches/minecraft/net/minecraft/entity/boss/EntityWither.java.patch
  patches/minecraft/net/minecraft/entity/monster/EntityCreeper.java.patch
  patches/minecraft/net/minecraft/entity/monster/EntityEnderman.java.patch
  patches/minecraft/net/minecraft/entity/monster/EntityEvoker.java.patch
  patches/minecraft/net/minecraft/entity/monster/EntitySilverfish.java.patch
  patches/minecraft/net/minecraft/entity/monster/EntitySnowman.java.patch
  patches/minecraft/net/minecraft/entity/passive/EntityRabbit.java.patch
  patches/minecraft/net/minecraft/entity/projectile/EntityLargeFireball.java.patch
  patches/minecraft/net/minecraft/entity/projectile/EntitySmallFireball.java.patch
  patches/minecraft/net/minecraft/entity/projectile/EntityWitherSkull.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/EntityMobGriefingEvent.java
  src/test/java/net/minecraftforge/debug/EntityMobGriefingEventTest.java
Labels: 1.12, Assigned, Feature

#4704 Improve dimension unload handling
  patches/minecraft/net/minecraft/world/gen/ChunkProviderServer.java.patch
  src/main/java/net/minecraftforge/common/DimensionManager.java
  src/main/java/net/minecraftforge/server/command/ChunkGenWorker.java
Labels: 1.12, Assigned, Feature

#4699 Optimise adding normal element to vertex formats
  src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterFlat.java
Labels: 1.12, Assigned, Performance

#4698 Improve performance of some ExtendedBlockState methods
  src/main/java/net/minecraftforge/common/property/ExtendedBlockState.java
Labels: 1.12, Assigned, Performance

#4685 Add a way to get a list of registered biome types
  src/main/java/net/minecraftforge/common/BiomeDictionary.java
Labels: 1.12, Assigned, Feature

#4661 Prevent EntityPlayer.attackEntityFrom from firing LivingAttackEvent twice
  patches/minecraft/net/minecraft/client/entity/EntityOtherPlayerMP.java.patch
  patches/minecraft/net/minecraft/client/entity/EntityPlayerSP.java.patch
  patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/test/java/net/minecraftforge/debug/LivingAttackEventTest.java
Labels: 1.12, Assigned, Bug

#4631 Add a FML outbound target for tracking point. Closes #3677
  patches/minecraft/net/minecraft/server/management/PlayerChunkMapEntry.java.patch
  src/main/java/net/minecraftforge/fml/common/network/FMLEventChannel.java
  src/main/java/net/minecraftforge/fml/common/network/FMLOutboundHandler.java
  src/main/java/net/minecraftforge/fml/common/network/simpleimpl/SimpleNetworkWrapper.java
  src/test/java/net/minecraftforge/debug/TrackingTargetTest.java
Labels: 1.12, Assigned, Feature

#4602 Better support for dimensional teleportation
  patches/minecraft/net/minecraft/entity/Entity.java.patch
  patches/minecraft/net/minecraft/entity/item/EntityEnderPearl.java.patch
  patches/minecraft/net/minecraft/entity/item/EntityItem.java.patch
  patches/minecraft/net/minecraft/entity/item/EntityMinecartContainer.java.patch
  patches/minecraft/net/minecraft/entity/player/EntityPlayerMP.java.patch
  patches/minecraft/net/minecraft/server/management/PlayerList.java.patch
  patches/minecraft/net/minecraft/world/Teleporter.java.patch
  patches/minecraft/net/minecraft/world/WorldProviderEnd.java.patch
  patches/minecraft/net/minecraft/world/end/DragonFightManager.java.patch
  src/main/java/net/minecraftforge/common/util/FakePlayer.java
  src/main/java/net/minecraftforge/common/util/ITeleporter.java
  src/main/java/net/minecraftforge/server/command/CommandSetDimension.java
  src/main/java/net/minecraftforge/server/command/ForgeCommand.java
  src/main/resources/assets/forge/lang/en_US.lang
  src/main/resources/forge.exc
Labels: 1.12, Assigned, Feature

#4725 Improve the warning logged for cascading world generation
  patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
Labels: 1.12, Assigned, Feature, Needs Update

#4830 Fix MC-88179 in a better way that avoids and closes #4824
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/server/management/PlayerList.java.patch
Labels: 1.12, Bug

#4854 Fix FluidUtil.getFluidHandler skipping fluid based tile entities
  src/main/java/net/minecraftforge/fluids/FluidUtil.java
Labels: 1.12, Bug

#4872 Clean up Reader/Writer handling to use a specified charset
  src/main/java/net/minecraftforge/client/model/BlockStateLoader.java
  src/main/java/net/minecraftforge/client/model/animation/ModelBlockAnimation.java
  src/main/java/net/minecraftforge/common/model/animation/AnimationStateMachine.java
  src/main/java/net/minecraftforge/fml/client/SplashProgress.java
  src/main/java/net/minecraftforge/fml/common/Loader.java
  src/main/java/net/minecraftforge/fml/common/MetadataCollection.java
  src/main/java/net/minecraftforge/fml/common/discovery/json/JsonAnnotationLoader.java
Labels: 1.12, Cleanup

#4878 Fix incorrectly-typed comparisons in biome dictionary
  src/main/java/net/minecraftforge/common/BiomeDictionary.java
Labels: 1.12, Bug

#4868 Fix dragon fight not initialising correctly under some circumstances
  patches/minecraft/net/minecraft/world/end/DragonFightManager.java.patch
Labels: 1.12, Assigned, Bug

#4811 Don't try to render removed tile entities (MC-123363)
  patches/minecraft/net/minecraft/client/renderer/tileentity/TileEntityRendererDispatcher.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#4881 Fix some code holding client world references longer than needed
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/client/MinecraftForgeClient.java
  src/main/java/net/minecraftforge/client/model/pipeline/BlockInfo.java
  src/main/java/net/minecraftforge/client/model/pipeline/ForgeBlockModelRenderer.java
  src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterFlat.java
Labels: 1.12, Assigned, Performance

#4890 Add checks for undefined packet discriminators when sending messages
  src/main/java/net/minecraftforge/fml/common/network/FMLIndexedMessageToMessageCodec.java
Labels: 1.12, Assigned, Bug

#4774 Fix #4772: add an "isActivator" boolean to powered rails
  patches/minecraft/net/minecraft/block/Block.java.patch
  patches/minecraft/net/minecraft/block/BlockRailPowered.java.patch
Labels: 1.12, Bug

#4729 Fix too early light initialization (fixes #4723)
  patches/minecraft/net/minecraft/world/World.java.patch
Labels: 1.12, Performance
