Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-12, with the labels that each got.

#6043 new SleepFinishedTimeEvent
  patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/world/SleepFinishedTimeEvent.java
Labels: 1.14, Assigned, Feature, New Event

#6327 1.14 - Added FENCES_WOODEN and FENCE_GATES_WOODEN tags as smeltables in AbstractFurnaceTileEntity
  patches/minecraft/net/minecraft/tileentity/AbstractFurnaceTileEntity.java.patch
Labels: 1.14, Assigned, Feature

#6328 Add item tag for beacon payment
  src/generated/resources/data/forge/tags/items/beacon_payment.json
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeItemTagsProvider.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
Labels: 1.14, Assigned, Feature

#6334 Fixed invocation of Vanilla spawn logic
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: 1.14, Assigned, Bug

#6335 Restore camera setup render event
  patches/minecraft/net/minecraft/client/renderer/ActiveRenderInfo.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: 1.14, Assigned, Bug

#6269 Split DrawBlockHighlightEvent into subevents to make usage clearer, addresses #2190
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/DrawBlockHighlightEvent.java
Labels: 1.14, Feature

#6347 Made canRiderInteract boolean in IForgeEntity actually work
  patches/minecraft/net/minecraft/entity/projectile/ProjectileHelper.java.patch
Labels: 1.14, Assigned, Bug

#6355 Reduce event spam for certain projectiles
  patches/minecraft/net/minecraft/entity/projectile/AbstractArrowEntity.java.patch
  patches/minecraft/net/minecraft/entity/projectile/LlamaSpitEntity.java.patch
Labels: 1.14, Bug

#6362 Some code cleanup for 1.15
  .travis.yml
  build.gradle
  src/fmllauncher/java/net/minecraftforge/fml/loading/LibraryFinder.java
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/DrawHighlightEvent.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/crafting/NBTIngredient.java
Labels: 1.15, Assigned, Cleanup

#6368 Fix capabilities becoming inaccessible on returning from end (1.15.1)
  patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch
Labels: 1.15, Assigned, Bug

#6363 Fix warning screen about missing minecraft registry entries
  src/main/java/net/minecraftforge/common/ForgeMod.java
Labels: 1.15

#6364 Fix game crashing when modded entities are present
  patches/minecraft/net/minecraft/client/renderer/entity/EntityRendererManager.java.patch
  src/main/java/net/minecraftforge/fml/client/registry/RenderingRegistry.java
Labels: 1.15, Assigned, Bug

#6353 Add FluidStack support to the Forge packet buffer.
  src/main/java/net/minecraftforge/common/extensions/IForgePacketBuffer.java
Labels: 1.14, Assigned, Feature

#6354 Minor Minecart Functionality
  patches/minecraft/net/minecraft/block/PoweredRailBlock.java.patch
  patches/minecraft/net/minecraft/entity/item/minecart/AbstractMinecartEntity.java.patch
Labels: 1.14, Assigned, Feature
