Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-11, with the labels that each got.

#6284 Removed getTypes invocation from ensureHasTypes to prevent infinite recursion.
  src/main/java/net/minecraftforge/common/BiomeDictionary.java
Labels: 1.14, Assigned, Bug

#6250 Added some biome types to BiomeDictionary
  src/main/java/net/minecraftforge/common/BiomeDictionary.java
Labels: 1.14, Assigned, Feature

#6282 Made the slash optional in fml confirm/cancel.
  src/main/java/net/minecraftforge/fml/StartupQuery.java
Labels: 1.14, Assigned

#6292 Fixed an NPE caused by missing registries.
  src/main/java/net/minecraftforge/registries/RegistryManager.java
Labels: Bug

#6046 [1.14] Add LeftClickEvent trigger to onPlayerDamageBlock
  patches/minecraft/net/minecraft/client/multiplayer/PlayerController.java.patch
Labels: 1.14, Bug, Needs Update

#6268 Modify StonecutterContainer to allow shift-click insertion of any block with a valid recipe rather than limiting to blocks in an Immutable List
  patches/minecraft/net/minecraft/inventory/container/StonecutterContainer.java.patch
Labels: 1.14, Assigned, Feature

#6303 Fix DyeColor referencing incorrect Tag path
  patches/minecraft/net/minecraft/item/DyeColor.java.patch
Labels: 1.14, Assigned, Bug

#6310 Fix RawMouseEvent not being cancelable
  src/main/java/net/minecraftforge/client/event/InputEvent.java
Labels: 1.14, Bug

#6266 Add tags supports_beacon and supports_conduit and modify Beacon and Conduit to use these tags
  patches/minecraft/net/minecraft/tileentity/ConduitTileEntity.java.patch
  src/generated/resources/data/forge/tags/blocks/supports_beacon.json
  src/generated/resources/data/forge/tags/blocks/supports_conduit.json
  src/generated/resources/data/forge/tags/items/supports_beacon.json
  src/generated/resources/data/forge/tags/items/supports_conduit.json
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeBlockTagsProvider.java
  src/main/java/net/minecraftforge/common/data/ForgeItemTagsProvider.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
Labels: 1.14, Assigned, Feature

#6290 Make it easier to add custom TNT blocks
  patches/minecraft/net/minecraft/block/FireBlock.java.patch
  patches/minecraft/net/minecraft/block/TNTBlock.java.patch
  patches/minecraft/net/minecraft/dispenser/IDispenseItemBehavior.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/block/CustomTNTTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/custom_tnt_test/blockstates/test_tnt.json
  src/test/resources/assets/custom_tnt_test/models/item/test_tnt.json
Labels: 1.14, Assigned, Feature

#6331 Fix emissive items not working
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: 1.14, Bug
