Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-10, with the labels that each got.

#6094 Patch Sweet Berry Bush to have Crop Growth Event Hook
  patches/minecraft/net/minecraft/block/SweetBerryBushBlock.java.patch
Labels: 1.14, Feature

#6139 Move displaying the main menu during init to after launch
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
Labels: 1.14, Feature, Vanilla Bug

#6196 Fix FluidTank with empty contents throwing error if drained
  src/main/java/net/minecraftforge/fluids/capability/templates/FluidTank.java
Labels: Bug, Fluids

#6154 Reimplement forge blockstates variants as pseudo-models (fixes custom model loading for blocks)
  patches/minecraft/net/minecraft/client/renderer/model/BlockModelDefinition.java.patch
  patches/minecraft/net/minecraft/client/renderer/model/ModelBakery.java.patch
  patches/minecraft/net/minecraft/client/renderer/model/Variant.java.patch
  src/main/java/net/minecraftforge/client/model/BlockStateLoader.java
  src/main/java/net/minecraftforge/client/model/ISmartVariant.java
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
  src/main/java/net/minecraftforge/client/model/ModelLoaderRegistry.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/client/model/ForgeBlockStatesLoaderTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/forgeblockstatesloader/blockstates/cobblestone_wall.json
  src/test/resources/assets/forgeblockstatesloader/blockstates/custom_wall.json
  src/test/resources/assets/forgeblockstatesloader/blockstates/mossy_cobblestone_wall.json
Labels: 1.14, Feature, Rendering

#6221 Allow IParticleRenderTypes to be rendered
  patches/minecraft/net/minecraft/client/particle/ParticleManager.java.patch
Labels: 1.14, Feature, Rendering

#6115 Fixed IModelData not able to be removed once the tile entity is removed
  patches/minecraft/net/minecraft/tileentity/TileEntity.java.patch
  src/main/java/net/minecraftforge/client/model/ModelDataManager.java
Labels: 1.14, Feature

#6170 Fix mod info rendering incorrectly on some systems with HiDPI displays
  src/main/java/net/minecraftforge/client/gui/ScrollPanel.java
  src/main/java/net/minecraftforge/fml/client/gui/GuiModList.java
Labels: 1.14, Assigned, Rendering

#6171 add onCropsGrow event to KelpTopBlock
  patches/minecraft/net/minecraft/block/KelpTopBlock.java.patch
Labels: 1.14, Assigned, Feature

#6193 Fix some config checks still using the old fields
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/gui/NotificationModUpdateScreen.java
  src/main/java/net/minecraftforge/client/model/FancyMissingModel.java
  src/main/java/net/minecraftforge/client/model/pipeline/ForgeBlockModelRenderer.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
Labels: 1.14, Assigned, Bug, Cleanup

#6202 Fix sheep shear sound not playing
  patches/minecraft/net/minecraft/entity/passive/SheepEntity.java.patch
Labels: 1.14, Assigned, Bug

#6206 Fix error logging in FMLUserdevLaunchProvider.setup
  src/userdev/java/net/minecraftforge/userdev/FMLUserdevLaunchProvider.java
Labels: 1.14, Assigned, Bug

#6208 Allow mods actually to have their own usable config gui
  src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  src/main/java/net/minecraftforge/fml/client/gui/GuiModList.java
Labels: 1.14, Assigned, Bug

#6216 [1.14] Fix MC-162953 bounds checks in `NativeImage`
  patches/minecraft/net/minecraft/client/renderer/texture/NativeImage.java.patch
Labels: 1.14, Assigned, Vanilla Bug

#6218 Fix loading error/warning screen not showing
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/fml/client/ClientModLoader.java
Labels: 1.14, Assigned, Bug

#6222 Include a project icon for the launcher json
  build.gradle
Labels: 1.14, Assigned, Feature

#6246 [1.14] Fix RightClickBlock#getUseBlock and #getUseItem being ignored. Fixes #6244
  patches/minecraft/net/minecraft/client/multiplayer/PlayerController.java.patch
  patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch
Labels: 1.14, Bug, Regression

#6256 Fixed `shouldCauseReequipAnimation `
  patches/minecraft/net/minecraft/client/renderer/FirstPersonRenderer.java.patch
Labels: 1.14, Assigned, Bug, Regression

#6178 Fixed forge rendering pipeline and shape based light occulsion.
  src/main/java/net/minecraftforge/client/model/pipeline/BlockInfo.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
Labels: 1.14, Assigned, Bug, Feature, Rendering

#6230 Exclude cobblestone slabs and wall recipes
  src/generated/resources/data/minecraft/recipes/cobblestone_slab.json
  src/generated/resources/data/minecraft/recipes/cobblestone_wall.json
  src/main/java/net/minecraftforge/common/data/ForgeRecipeProvider.java
Labels: 1.14, Assigned, Bug

#6114 [1.14]reimplement usage of Item#doesSneakBypassUse()
  patches/minecraft/net/minecraft/client/multiplayer/PlayerController.java.patch
  patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch
Labels: 1.14, Feature

#6091 Fixed entity navigation to stop entities spinning
  patches/minecraft/net/minecraft/pathfinding/PathNavigator.java.patch
  patches/minecraft/net/minecraft/pathfinding/SwimmerPathNavigator.java.patch
Labels: 1.14, Assigned, Bug, Vanilla Bug
