Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-06, with the labels that each got.

#5792 Use dragon_immune block tag instead of manually checking blocks
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
Labels: 1.14

#5789 Fix RenderSpecificHandEvent firing with wrong hand
  patches/minecraft/net/minecraft/client/renderer/FirstPersonRenderer.java.patch
Labels: 1.14, Regression

#5799 Fix AT for EntitySpawnPlacementRegistry.register
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.14

#5781 Update Example Mod
  mdk/src/main/java/com/example/examplemod/ExampleMod.java
  mdk/src/main/resources/META-INF/mods.toml
Labels: 1.14, Bug

#5793 [1.14] Add mod loading failure identification
  src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/InvalidModIdentifier.java
  src/main/java/net/minecraftforge/fml/ModLoader.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.14, Feature

#5813 [1.14.2] Implement Ingredient.getSerializer for custom ingredients
  src/main/java/net/minecraftforge/common/crafting/CompoundIngredient.java
  src/main/java/net/minecraftforge/common/crafting/IngredientNBT.java
Labels: 1.14, Bug

#5773 Update readme and issue template.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  docs/CONTRIBUTING.md
  docs/EnergySystems.md
  docs/NewFML.md
  docs/README.md
  docs/SUPPORT.md
  docs/assets/Forge_logo.svg
Labels: 1.14, Cleanup

#5843 [1.14.x] Replace dye items in Forge tags.
  src/generated/resources/data/forge/tags/items/dyes/black.json
  src/generated/resources/data/forge/tags/items/dyes/blue.json
  src/generated/resources/data/forge/tags/items/dyes/brown.json
  src/generated/resources/data/forge/tags/items/dyes/white.json
  src/main/java/net/minecraftforge/common/data/ForgeItemTagsProvider.java
Labels: 1.14

#5812 Add extension to write entry id's to PacketBuffer's
  patches/minecraft/net/minecraft/network/PacketBuffer.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgePacketBuffer.java
Labels: 1.14, Feature

#5757 Fix item placement losing NBT data in creative mode
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.14, Bug, Regression
