Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-03, with the labels that each got.

#5530 Add UI for warnings that occurred during loading
  src/fmllauncher/java/net/minecraftforge/fml/loading/LoadingModList.java
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/fml/ModLoader.java
  src/main/java/net/minecraftforge/fml/ModLoadingWarning.java
  src/main/java/net/minecraftforge/fml/client/ClientModLoader.java
  src/main/java/net/minecraftforge/fml/client/gui/LoadingErrorScreen.java
  src/main/java/net/minecraftforge/fml/server/ServerModLoader.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.13, Feature

#5182 Generalise EnumRarity to an interface
  patches/minecraft/net/minecraft/client/gui/GuiScreen.java.patch
  patches/minecraft/net/minecraft/client/gui/inventory/GuiContainerCreative.java.patch
  patches/minecraft/net/minecraft/item/EnumRarity.java.patch
  patches/minecraft/net/minecraft/item/Item.java.patch
  patches/minecraft/net/minecraft/item/ItemStack.java.patch
  src/main/java/net/minecraftforge/common/IRarity.java
  src/main/java/net/minecraftforge/common/util/EnumHelper.java
  src/test/java/net/minecraftforge/debug/item/CustomRarityTest.java
Labels: 1.12, Assigned, Feature

#5057 Place Event (Implements #5054)
  patches/minecraft/net/minecraft/entity/item/EntityFallingBlock.java.patch
  patches/minecraft/net/minecraft/entity/monster/EntityEnderman.java.patch
  patches/minecraft/net/minecraft/item/ItemBlock.java.patch
  patches/minecraft/net/minecraft/item/ItemBlockSpecial.java.patch
  patches/minecraft/net/minecraft/item/ItemRedstone.java.patch
  patches/minecraft/net/minecraft/world/World.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/world/BlockEvent.java
  src/test/java/net/minecraftforge/debug/block/BasePlaceEventTest.java
Labels: 1.12, Assigned, Feature

#5348 Only prompt for missing registries on local worlds
  src/main/java/net/minecraftforge/registries/GameData.java
Labels: 1.12, Assigned, Bug

#5389 [1.12] Fix special spawn event not firing in many cases.
  patches/minecraft/net/minecraft/item/ItemMonsterPlacer.java.patch
  src/test/java/net/minecraftforge/debug/entity/living/SpecialSpawnTest.java
Labels: 1.12, Assigned, Bug

#5302 [1.12.2] Add a few events pertaining to villages
  patches/minecraft/net/minecraft/entity/NpcMerchant.java.patch
  patches/minecraft/net/minecraft/entity/passive/EntityVillager.java.patch
  patches/minecraft/net/minecraft/village/VillageSiege.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/village/MerchantTradeOffersEvent.java
  src/main/java/net/minecraftforge/event/village/VillageSiegeEvent.java
  src/test/java/net/minecraftforge/debug/village/MerchantTradeOffersEventTest.java
  src/test/java/net/minecraftforge/debug/village/VillageSiegeEventTest.java
Labels: 1.12, Assigned, Feature

#5603 [1.13.x] Fix entity spawn packet pitch (reversed yaw/pitch)
  src/main/java/net/minecraftforge/fml/network/FMLPlayMessages.java
Labels: 1.13, Assigned, Bug

#5572 Fix being unable to plant nether wart
  patches/minecraft/net/minecraft/item/ItemSeeds.java.patch
Labels: 1.13, Assigned, Bug

#5323 Added more Constants
  src/main/java/net/minecraftforge/common/util/BlockSnapshot.java
  src/main/java/net/minecraftforge/common/util/Constants.java
  src/main/java/net/minecraftforge/fluids/BlockFluidClassic.java
  src/main/java/net/minecraftforge/fluids/BlockFluidFinite.java
  src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockLiquidWrapper.java
  src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockWrapper.java
Labels: 1.12, Assigned, Cleanup

#5534 Fix getDefaultCreatorModId for enchanted books
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.13

#5257 Fail fast when null is used with setTag instead of crashing in writeEntry
  patches/minecraft/net/minecraft/nbt/NBTTagCompound.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#5611 Fix PlayerInteractEvent using Dist when it should be using LogicalSide
  src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
Labels: 1.13, Assigned, Bug

#5591 [1.13] Remove uses of java.awt
  src/main/java/net/minecraftforge/client/GuiIngameForge.java
  src/main/java/net/minecraftforge/client/event/ScreenshotEvent.java
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
  src/main/java/net/minecraftforge/common/util/Size2i.java
  src/main/java/net/minecraftforge/fluids/Fluid.java
  src/main/java/net/minecraftforge/fml/client/SplashProgress.java
  src/main/java/net/minecraftforge/fml/client/gui/GuiBackupFailed.java
  src/main/java/net/minecraftforge/fml/client/gui/GuiModList.java
  src/test/java/net/minecraftforge/debug/fluid/ColoredFluidTest.java
  src/test/java/net/minecraftforge/debug/gameplay/DynamicBannerTest.java
  src/test/java/net/minecraftforge/debug/util/TextureDumper.java
Labels: 1.13, Assigned, Cleanup

#5522 [1.13] Final touches for recipes
  src/main/java/net/minecraftforge/common/extensions/ForgeRecipeManager.java
  src/main/java/net/minecraftforge/common/extensions/IForgeRecipe.java
  src/main/java/net/minecraftforge/items/wrapper/RecipeWrapper.java
Labels: 1.13, Assigned, Feature

#5525 Add method to IResourcePack to hide it entirely from the UI
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/gui/GuiScreenResourcePacks.java.patch
  patches/minecraft/net/minecraft/client/resources/ResourcePackInfoClient.java.patch
  patches/minecraft/net/minecraft/resources/IResourcePack.java.patch
  patches/minecraft/net/minecraft/resources/ResourcePackInfo.java.patch
  src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModFileInfo.java
  src/main/java/net/minecraftforge/client/extensions/IForgeResourcePack.java
  src/main/java/net/minecraftforge/fml/packs/ModFileResourcePack.java
  src/main/resources/forge.exc
Labels: 1.13, Assigned, Feature
