Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-07, with the labels that each got.

#5885 Fix TickEvent.PlayerTickEvent firing twice for tick end (fixes #5878)
  patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch
Labels: 1.14

#5884 Fix WorldEvent.Unload not firing on the client (fixes #5880)
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
Labels: 1.14

#5873 [1.14] Allow mods to specify recipe book categories
  patches/minecraft/net/minecraft/client/gui/recipebook/RecipeBookGui.java.patch
  patches/minecraft/net/minecraft/inventory/container/RecipeBookContainer.java.patch
Labels: 1.14, Feature

#5870 Update TextureStitchEvent.Pre to give access to the list of ResourceLocations that will be loaded as textures.
  patches/minecraft/net/minecraft/client/renderer/texture/AtlasTexture.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/TextureStitchEvent.java
Labels: 1.14, Regression

#5833 [1.14.x] [Bug] Fix old entity not being removed in Entity#changeDimension
  patches/minecraft/net/minecraft/entity/Entity.java.patch
Labels: 1.14, Assigned, Bug

#5893 [1.14.x] ObfuscationReflectionHelper
  src/main/java/net/minecraftforge/fml/common/ObfuscationReflectionHelper.java
Labels: 1.14

#5606 Add isServer and isClient methods to LogicalSide
  src/main/java/net/minecraftforge/fml/LogicalSide.java
Labels: 1.13, Assigned, Feature, Needs Rebase, Needs Update

#5646 Throw when a mod returns null from a capability provider
  src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java
Labels: 1.13, Feature, Needs Rebase

#5761 Fix BakedModelWrapper not delegating new methods
  src/main/java/net/minecraftforge/client/model/BakedModelWrapper.java
Labels: 1.14, Bug

#5756 Add IModelData to getParticleTexture
  patches/minecraft/net/minecraft/client/particle/DiggingParticle.java.patch
  patches/minecraft/net/minecraft/client/renderer/BlockModelShapes.java.patch
  patches/minecraft/net/minecraft/client/renderer/FirstPersonRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/model/IBakedModel.java.patch
  src/main/java/net/minecraftforge/client/extensions/IForgeBakedModel.java
  src/main/java/net/minecraftforge/client/model/BakedModelWrapper.java
Labels: 1.14, Feature

#5744 Pass tick counter to custom render handlers
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  src/main/java/net/minecraftforge/client/CloudRenderer.java
  src/main/java/net/minecraftforge/client/IRenderHandler.java
Labels: 1.13, Feature, Needs Rebase

#5698 Add InputEvent documentation
  src/main/java/net/minecraftforge/client/event/InputEvent.java
Labels: 1.13, Cleanup, Needs Rebase

#5762 Adds some explanatory javadocs and check world in ModelDataManager
  patches/minecraft/net/minecraft/client/renderer/model/IBakedModel.java.patch
  src/main/java/net/minecraftforge/client/model/ModelDataManager.java
  src/main/java/net/minecraftforge/common/extensions/IForgeTileEntity.java
Labels: 1.14, Bug, Cleanup

#5775 [Bug] fml|ModInfo.java: `logoFile` wrong order of priority
  src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
Labels: 1.13, Bug, Needs Rebase

#5795 [1.13.2/1.14.2] Fire Loading event for default server config
  src/main/java/net/minecraftforge/fml/config/ConfigTracker.java
Labels: 1.14, Bug

#5670 Add general damage hook for items. Closes #5502
  patches/minecraft/net/minecraft/item/ItemStack.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
Labels: 1.14, Feature

#5927 Fix RenderSpecificHandEvent firing with wrong hand stack
  patches/minecraft/net/minecraft/client/renderer/FirstPersonRenderer.java.patch
Labels: 1.14, Bug

#5925 Remove OnlyIn Client Distribution from Effect and EffectType methods.
  patches/minecraft/net/minecraft/potion/Effect.java.patch
  patches/minecraft/net/minecraft/potion/EffectType.java.patch
Labels: 1.14, Feature

#5922 Fix & Improve state comparison when checking vanilla block replacements
  build.gradle
  patches/minecraft/net/minecraft/item/BlockItem.java.patch
  patches/minecraft/net/minecraft/item/WallOrFloorItem.java.patch
  src/main/java/net/minecraftforge/registries/GameData.java
Labels: 1.14, Bug

#5964 Fix worlds being queued twice to unload
  patches/minecraft/net/minecraft/world/server/ChunkManager.java.patch
  src/main/java/net/minecraftforge/common/DimensionManager.java
Labels: 1.14, Bug
