Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-08, with the labels that each got.

#5766 Fix various unclosed I/O resources
  patches/minecraft/net/minecraft/client/resources/ResourcePackRepository.java.patch
  patches/minecraft/net/minecraft/util/text/translation/LanguageMap.java.patch
  patches/minecraft/net/minecraft/world/chunk/storage/AnvilChunkLoader.java.patch
  src/main/java/net/minecraftforge/common/ForgeModContainer.java
  src/main/java/net/minecraftforge/fml/client/GuiModList.java
  src/main/java/net/minecraftforge/fml/common/Loader.java
  src/main/java/net/minecraftforge/fml/common/patcher/ClassPatchManager.java
Labels: 1.12, Bug, Vanilla Bug

#5760 Fix more unclosed resources
  src/main/java/net/minecraftforge/client/MinecraftForgeClient.java
  src/main/java/net/minecraftforge/client/model/ModelDynBucket.java
  src/main/java/net/minecraftforge/client/model/obj/OBJModel.java
Labels: 1.12, Bug

#5752 Protect against concurrent modification in World#setTileEntity
  patches/minecraft/net/minecraft/world/World.java.patch
Labels: 1.12, Bug, Stale

#5910 Fix link applying to whole component in chat if component starts with link (1.12.2)
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.12, Bug

#5772 LazyOptional no longer silently swallows all Throwables
  src/main/java/net/minecraftforge/common/util/LazyOptional.java
Labels: 1.13, Bug, Needs Rebase

#5924 Fix GuiButtonExt and #5687
  src/main/java/net/minecraftforge/fml/client/config/GuiButtonExt.java
  src/main/java/net/minecraftforge/fml/client/gui/LoadingErrorScreen.java
Labels: 1.14, Bug

#5876 Fix concurrent modification when loading chunk tickets
  src/main/java/net/minecraftforge/common/ForgeChunkManager.java
Labels: 1.12, Bug

#5798 [1.14.x] Add piston hooks with test
  patches/minecraft/net/minecraft/block/PistonBlock.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/world/PistonEvent.java
  src/test/java/net/minecraftforge/debug/block/PistonEventTest.java
Labels: 1.14, Feature

#5787 Fix hashCode when side is null
  src/main/java/net/minecraftforge/items/wrapper/SidedInvWrapper.java
Labels: 1.12

#5763 Improve performance of smooth vertex lighting
  src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterSmoothAo.java
Labels: 1.12, BreakingChange, Performance

#5758 Avoid caching OBJ and B3D models since they're baked on load now.
  src/main/java/net/minecraftforge/client/model/b3d/B3DLoader.java
  src/main/java/net/minecraftforge/client/model/obj/OBJLoader.java
Labels: 1.12, Cleanup

#6019 Make DimensionManager.SavedEntry save sky light consistently
  src/main/java/net/minecraftforge/common/DimensionManager.java
Labels: 1.14, Assigned, Bug

#6009 Cover more cases for RightClickBlock event and restore functionality of onItemUseFirst
  patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch
Labels: 1.14, Bug, Feature

#6010 Add hook to load custom mrls/rls not attached to a block or item.
  patches/minecraft/net/minecraft/client/renderer/model/ModelBakery.java.patch
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
Labels: 1.14, Feature, Rendering

#6078 Fix coremod not redirecting to the correct method
  patches/minecraft/net/minecraft/potion/EffectInstance.java.patch
  src/main/resources/META-INF/fieldtomethodtransformers.js
Labels: 1.14, Assigned, Bug

#6061 Fix regular arrows giving off particles after a world reload (MC-107941)
  patches/minecraft/net/minecraft/entity/projectile/ArrowEntity.java.patch
Labels: 1.14, Vanilla Bug

#5706 [1.12] Improve performance of persistent chunk checks
  patches/minecraft/net/minecraft/world/World.java.patch
  src/main/java/net/minecraftforge/common/ForgeChunkManager.java
Labels: 1.12, Performance

#6018 Make vanilla particle system usable by mods
  patches/minecraft/net/minecraft/client/particle/ParticleManager.java.patch
  src/main/java/net/minecraftforge/client/event/ParticleFactoryRegisterEvent.java
Labels: 1.14, Bug

#5290 Adding more support for interaction with lightning. Closes #2754
  patches/minecraft/net/minecraft/world/World.java.patch
Labels: 1.12, Assigned, Feature

#5255 Allow conditional loading of advancements
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java
Labels: 1.12, Assigned, Feature

#5718 Fix invalid placeholder entity attributes (MC-150405)
  patches/minecraft/net/minecraft/client/network/NetHandlerPlayClient.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#5720 [1.12.x] Fix client sometimes generating biomes, causing incorrect biome generation on integrated server
  patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#5724 Add checks for tile entities in now-unloaded chunks
  patches/minecraft/net/minecraft/client/renderer/tileentity/TileEntityRendererDispatcher.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#6012 Updated constants to 1.14
  src/main/java/net/minecraftforge/common/util/BlockSnapshot.java
  src/main/java/net/minecraftforge/common/util/Constants.java
Labels: 1.14, Cleanup

#6016 Add Villager Trading Events
  src/main/java/net/minecraftforge/common/BasicTrade.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/VillagerTradingManager.java
  src/main/java/net/minecraftforge/event/village/VillagerTradesEvent.java
  src/main/java/net/minecraftforge/event/village/WandererTradesEvent.java
Labels: 1.14, Feature, Triage

#6079 Config: Add a comment that lists the available constants of enums
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: 1.14, Feature

#6080 Update en_us.json
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.14, Cleanup

#6077 Fix Digging particle using the wrong block pos for ModelData
  patches/minecraft/net/minecraft/client/particle/DiggingParticle.java.patch
  patches/minecraft/net/minecraft/entity/Entity.java.patch
  patches/minecraft/net/minecraft/entity/passive/IronGolemEntity.java.patch
  patches/minecraft/net/minecraft/particles/BlockParticleData.java.patch
Labels: 1.14, Rendering

#6089 Minor model system cleanup/documentation
  patches/minecraft/net/minecraft/client/renderer/ItemRenderer.java.patch
  src/main/java/net/minecraftforge/client/model/BasicState.java
  src/main/java/net/minecraftforge/client/model/ICustomModelLoader.java
  src/main/java/net/minecraftforge/client/model/IModel.java
  src/main/java/net/minecraftforge/client/model/ItemLayerModel.java
  src/main/java/net/minecraftforge/client/model/MapModelState.java
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
  src/main/java/net/minecraftforge/client/model/ModelLoaderRegistry.java
  src/main/java/net/minecraftforge/client/model/ModelStateComposition.java
  src/main/java/net/minecraftforge/client/model/MultiLayerModel.java
  src/main/java/net/minecraftforge/client/model/SimpleModelState.java
  src/main/java/net/minecraftforge/common/model/IModelPart.java
  src/main/java/net/minecraftforge/common/model/IModelState.java
Labels: 1.14, Rendering
