Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-05, with the labels that each got.

#5564 Add new system for model data, replacing extended states
  patches/minecraft/net/minecraft/client/renderer/BlockModelRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/BlockRendererDispatcher.java.patch
  patches/minecraft/net/minecraft/client/renderer/chunk/ChunkRenderTask.java.patch
  patches/minecraft/net/minecraft/client/renderer/chunk/RenderChunk.java.patch
  patches/minecraft/net/minecraft/client/renderer/model/IBakedModel.java.patch
  patches/minecraft/net/minecraft/world/chunk/ChunkSection.java.patch
  src/main/java/net/minecraftforge/client/MinecraftForgeClient.java
  src/main/java/net/minecraftforge/client/extensions/IForgeBakedModel.java
  src/main/java/net/minecraftforge/client/model/ModelDataManager.java
  src/main/java/net/minecraftforge/client/model/ModelFluid.java
  src/main/java/net/minecraftforge/client/model/ModelLoader.java
  src/main/java/net/minecraftforge/client/model/animation/TileEntityRendererAnimation.java
  src/main/java/net/minecraftforge/client/model/b3d/B3DLoader.java
  src/main/java/net/minecraftforge/client/model/data/EmptyModelData.java
  src/main/java/net/minecraftforge/client/model/data/IDynamicBakedModel.java
  src/main/java/net/minecraftforge/client/model/data/IModelData.java
  src/main/java/net/minecraftforge/client/model/data/ModelDataMap.java
  src/main/java/net/minecraftforge/client/model/data/ModelProperty.java
  src/main/java/net/minecraftforge/client/model/obj/OBJModel.java
  src/main/java/net/minecraftforge/common/extensions/IForgeTileEntity.java
  src/main/java/net/minecraftforge/common/property/ExtendedStateContainer.java
  src/main/java/net/minecraftforge/common/property/IExtendedBlockState.java
  src/main/java/net/minecraftforge/common/property/IExtendedState.java
  src/main/java/net/minecraftforge/common/property/IUnlistedProperty.java
  src/main/java/net/minecraftforge/common/property/Properties.java
  src/main/java/net/minecraftforge/common/property/PropertyFloat.java
  src/main/resources/assets/forge/blockstates/modeltest.json
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/client/model/ModelDataTest.java
Labels: 1.13, Feature, RFC

#5725 Fix vanilla handling of options file (MC-117449, MC-151173)
  patches/minecraft/net/minecraft/client/settings/GameSettings.java.patch
Labels: 1.12, Assigned, Vanilla Bug

#5367 Fix GuiContainer#keyPressed to return the correct key handled boolean
  patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
Labels: 1.13, Assigned, Vanilla Bug

#5738 [1.13.x] Tags for several old oredicts and some extra
  src/main/resources/data/forge/tags/blocks/bookshelves.json
  src/main/resources/data/forge/tags/blocks/end_stone.json
  src/main/resources/data/forge/tags/blocks/gravel.json
  src/main/resources/data/forge/tags/blocks/heads.json
  src/main/resources/data/forge/tags/blocks/netherrack.json
  src/main/resources/data/forge/tags/blocks/obsidian.json
  src/main/resources/data/forge/tags/blocks/sandstone.json
  src/main/resources/data/forge/tags/items/arrows.json
  src/main/resources/data/forge/tags/items/bone.json
  src/main/resources/data/forge/tags/items/bookshelves.json
  src/main/resources/data/forge/tags/items/crops.json
  src/main/resources/data/forge/tags/items/crops/beetroot.json
  src/main/resources/data/forge/tags/items/crops/carrot.json
  src/main/resources/data/forge/tags/items/crops/nether_wart.json
  src/main/resources/data/forge/tags/items/crops/potato.json
  src/main/resources/data/forge/tags/items/crops/wheat.json
  src/main/resources/data/forge/tags/items/egg.json
  src/main/resources/data/forge/tags/items/end_stone.json
  src/main/resources/data/forge/tags/items/ender_pearl.json
  src/main/resources/data/forge/tags/items/feather.json
  src/main/resources/data/forge/tags/items/gravel.json
  src/main/resources/data/forge/tags/items/gunpowder.json
  src/main/resources/data/forge/tags/items/heads.json
  src/main/resources/data/forge/tags/items/leather.json
  src/main/resources/data/forge/tags/items/nether_star.json
  src/main/resources/data/forge/tags/items/netherrack.json
  src/main/resources/data/forge/tags/items/obsidian.json
  src/main/resources/data/forge/tags/items/sandstone.json
  src/main/resources/data/forge/tags/items/seeds.json
  src/main/resources/data/forge/tags/items/seeds/beetroot.json
  src/main/resources/data/forge/tags/items/seeds/melon.json
  src/main/resources/data/forge/tags/items/seeds/pumpkin.json
  src/main/resources/data/forge/tags/items/seeds/wheat.json
  src/main/resources/data/forge/tags/items/slime_ball.json
  src/main/resources/data/forge/tags/items/string.json
Labels: 1.13, Feature
