Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-01, with the labels that each got.

#5250 Ensure slave maps are cleaned up when handling registry overrides
  src/main/java/net/minecraftforge/registries/GameData.java
Labels: 1.12, Assigned, Bug

#5201 Fix incorrect indexing in mipmap generation code
  patches/minecraft/net/minecraft/client/renderer/texture/TextureUtil.java.patch
Labels: 1.12, Assigned, Bug, Rendering

#5125 Allow config GUI cycling button elements generated from enums to display toString return values, rather than actual values.
  src/main/java/net/minecraftforge/common/config/ConfigElement.java
  src/main/java/net/minecraftforge/common/config/Configuration.java
  src/main/java/net/minecraftforge/common/config/FieldWrapper.java
  src/main/java/net/minecraftforge/common/config/Property.java
  src/main/java/net/minecraftforge/fml/client/config/DummyConfigElement.java
  src/main/java/net/minecraftforge/fml/client/config/GuiConfigEntries.java
  src/main/java/net/minecraftforge/fml/client/config/IConfigElement.java
  src/test/java/net/minecraftforge/debug/mod/ConfigAnnotationTest.java
Labels: 1.12, Assigned, Feature

#5320 Fix small logic error in emissive item rendering code
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: 1.12, Assigned, Bug, Rendering

#5026 Add an annotation for @Config elements which will automatically create a slider control
  src/main/java/net/minecraftforge/common/config/Config.java
  src/main/java/net/minecraftforge/common/config/ConfigElement.java
  src/main/java/net/minecraftforge/common/config/ConfigManager.java
  src/main/java/net/minecraftforge/common/config/FieldWrapper.java
  src/main/java/net/minecraftforge/common/config/IFieldWrapper.java
  src/main/java/net/minecraftforge/common/config/Property.java
  src/main/java/net/minecraftforge/fml/client/config/GuiConfig.java
  src/main/java/net/minecraftforge/fml/client/config/GuiConfigEntries.java
  src/main/java/net/minecraftforge/fml/client/config/IConfigElement.java
  src/test/java/net/minecraftforge/test/SliderConfigElementTest.java
  src/test/resources/mcmod.info
Labels: 1.12, Assigned, Feature

#5213 Add redirects to PotionEffect to respect registry replacement
  patches/minecraft/net/minecraft/potion/PotionEffect.java.patch
  src/main/java/net/minecraftforge/fml/common/asm/transformers/PotionEffectTransformer.java
  src/main/java/net/minecraftforge/fml/common/launcher/FMLDeobfTweaker.java
  src/test/java/net/minecraftforge/debug/mod/RegistryOverrideTest.java
Labels: 1.12, Assigned, Feature

#5293 Added an additional constructor to every implementation of IFluidBlock..
  src/main/java/net/minecraftforge/fluids/BlockFluidBase.java
  src/main/java/net/minecraftforge/fluids/BlockFluidClassic.java
  src/main/java/net/minecraftforge/fluids/BlockFluidFinite.java
Labels: 1.12, Assigned, Feature

#5313 Make Block.Builder methods accessible. Closes #5310
  src/main/resources/forge_at.cfg
Labels: 1.13

#5279 Fix blockstate id map calculation.
  patches/minecraft/net/minecraft/block/Block.java.patch
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/IForgeRegistry.java
  src/main/java/net/minecraftforge/registries/RegistryBuilder.java
  src/main/java/net/minecraftforge/registries/RegistryManager.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/forge_at.cfg
  src/userdev/java/net/minecraftforge/userdev/FMLUserdevClientLaunchProvider.java
  src/userdev/java/net/minecraftforge/userdev/FMLUserdevLaunchProvider.java
  src/userdev/java/net/minecraftforge/userdev/FMLUserdevServerLaunchProvider.java
Labels: 1.13

#5357 Greatly improve DeferredWorkQueue API
  src/main/java/net/minecraftforge/fml/DeferredWorkQueue.java
  src/main/java/net/minecraftforge/fml/ModList.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.13

#5319 [1.13] Improves topological sort
  build.gradle
  src/fmllauncher/java/net/minecraftforge/fml/loading/ModSorter.java
  src/fmllauncher/java/net/minecraftforge/fml/loading/toposort/CyclePresentException.java
  src/fmllauncher/java/net/minecraftforge/fml/loading/toposort/StronglyConnectedComponentDetector.java
  src/fmllauncher/java/net/minecraftforge/fml/loading/toposort/TopologicalSort.java
  src/fmllaunchertest/java/net/minecraftforge/fml/test/TopologicalSortTests.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.13, Performance

#5312 Add recipe types.
  patches/minecraft/net/minecraft/entity/passive/EntitySheep.java.patch
  patches/minecraft/net/minecraft/inventory/Container.java.patch
  patches/minecraft/net/minecraft/inventory/ContainerFurnace.java.patch
  patches/minecraft/net/minecraft/inventory/SlotCrafting.java.patch
  patches/minecraft/net/minecraft/item/crafting/FurnaceRecipe.java.patch
  patches/minecraft/net/minecraft/item/crafting/IRecipe.java.patch
  patches/minecraft/net/minecraft/item/crafting/RecipeManager.java.patch
  patches/minecraft/net/minecraft/item/crafting/ShapedRecipe.java.patch
  patches/minecraft/net/minecraft/item/crafting/ShapelessRecipe.java.patch
  patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
  patches/minecraft/net/minecraft/world/storage/loot/functions/Smelt.java.patch
  src/main/java/net/minecraftforge/common/crafting/RecipeType.java
  src/main/java/net/minecraftforge/common/crafting/VanillaRecipeTypes.java
  src/main/java/net/minecraftforge/common/extensions/ForgeRecipeManager.java
  src/main/java/net/minecraftforge/common/extensions/IForgeRecipe.java
Labels: 1.13, Feature

#5303 Add RecipesUpdatedEvent
  patches/minecraft/net/minecraft/client/network/NetHandlerPlayClient.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/RecipesUpdatedEvent.java
Labels: 1.13, Feature

#5402 Fix RuntimeEnumExtender creating new enums with incorrect ordinal value
  src/fmllauncher/java/net/minecraftforge/common/asm/RuntimeEnumExtender.java
  src/test/java/net/minecraftforge/debug/misc/EnumPlantTypeTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.13, Assigned, Bug
