Repository MinecraftForge/MinecraftForge, pull requests merged in 2019-02, with the labels that each got.

#5434 [1.13] Update multiple classes to use correct grass block
  patches/minecraft/net/minecraft/block/Block.java.patch
  patches/minecraft/net/minecraft/entity/passive/EntityParrot.java.patch
  patches/minecraft/net/minecraft/entity/passive/EntityRabbit.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
Labels: 1.13, Assigned, Bug

#5400 [1.13] Added 'create'-method for EnumCreatureType
  patches/minecraft/net/minecraft/entity/EnumCreatureType.java.patch
  src/main/resources/forge.exc
Labels: 1.13, Assigned, Feature

#5426 Fix up torch placement logic to handle more vanilla special-casing
  patches/minecraft/net/minecraft/block/Block.java.patch
Labels: 1.12, Assigned, Regression

#5397 [1.13] Port Minecraft client patch for 'ClientTickEvent'
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches_old_unknown/Minecraft.java.patch
Labels: 1.13, Feature

#5332 [1.13] Allow GuiContainer and ItemGroup to specify slot hover colors
  patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
  patches/minecraft/net/minecraft/client/gui/inventory/GuiContainerCreative.java.patch
  patches/minecraft/net/minecraft/item/ItemGroup.java.patch
Labels: 1.13, Feature

#5272 Remove FluidStack amount from hashcode calculation
  src/main/java/net/minecraftforge/fluids/FluidStack.java
Labels: 1.12, Bug

#5330 [1.13] Let ItemGroup provide it's own tabs image resource location
  patches/minecraft/net/minecraft/client/gui/inventory/GuiContainerCreative.java.patch
  patches/minecraft/net/minecraft/item/ItemGroup.java.patch
Labels: 1.13, Feature

#5432 Fix leaking unclosed InputStream in Scanner.fileVisitor
  src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/Scanner.java
Labels: 1.13, Bug

#5395 Made functional interface IChunkGeneratorFactory public
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.13, Vanilla Bug

#5411 Port CommandEvent and custom entity selectors to 1.13
  patches/minecraft/net/minecraft/command/Commands.java.patch
  patches/minecraft/net/minecraft/command/arguments/EntitySelectorParser.java.patch
  patches_old/minecraft/net/minecraft/command/CommandHandler.java.patch
  patches_old/minecraft/net/minecraft/command/EntitySelector.java.patch
  src/main/java/net/minecraftforge/common/command/EntitySelectorManager.java
  src/main/java/net/minecraftforge/common/command/IEntitySelectorType.java
  src/main/java/net/minecraftforge/event/CommandEvent.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/chat/CommandEventTest.java
  src/test/java/net/minecraftforge/debug/chat/EntitySelectorFactoryTest.java
  src/test/java/net/minecraftforge/debug/chat/EntitySelectorTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.13, Feature

#5364 Fix incorrect string representation of string list config property default values in their comments.
  src/main/java/net/minecraftforge/common/config/Configuration.java
Labels: 1.12, Assigned, Bug

#5249 Improve tracking of used dimension IDs
  src/main/java/net/minecraftforge/common/DimensionManager.java
Labels: 1.12, Assigned, Cleanup

#5209 Better support for custom bows
  patches/minecraft/net/minecraft/client/entity/AbstractClientPlayer.java.patch
  patches/minecraft/net/minecraft/client/model/ModelSkeleton.java.patch
  patches/minecraft/net/minecraft/client/renderer/ItemRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/layers/LayerHeldItemWitch.java.patch
  patches/minecraft/net/minecraft/entity/ai/EntityAIAttackRangedBow.java.patch
  patches/minecraft/net/minecraft/entity/monster/AbstractSkeleton.java.patch
  patches/minecraft/net/minecraft/entity/monster/EntityIllusionIllager.java.patch
  patches/minecraft/net/minecraft/item/ItemBow.java.patch
  src/main/resources/forge_at.cfg
Labels: 1.12, Assigned, Feature

#5463 Fix small logic error in ItemTextureQuadConverter
  src/main/java/net/minecraftforge/client/model/ItemTextureQuadConverter.java
Labels: 1.12, Assigned, Bug

#5451 [1.13] Reintroduce a container-opening system
  patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
  src/main/java/net/minecraftforge/fml/network/FMLPlayHandler.java
  src/main/java/net/minecraftforge/fml/network/FMLPlayMessages.java
  src/main/java/net/minecraftforge/fml/network/NetworkHooks.java
  src/main/java/net/minecraftforge/fml/network/NetworkRegistry.java
Labels: 1.13, Feature

#5468 Apply access-level changes to inner class attributes
  src/main/java/net/minecraftforge/fml/common/asm/transformers/AccessTransformer.java
Labels: 1.12, Bug

#5483 Add back missing patch for Item.BLOCK_TO_ITEM
  patches/minecraft/net/minecraft/item/Item.java.patch
Labels: 1.13, Regression

#5509 [1.13.2] Fix bug with ObfuscationReflectionHelper
  src/main/java/net/minecraftforge/fml/common/ObfuscationReflectionHelper.java
Labels: 1.13, Assigned, Bug

#5493 [1.13.x] Altered EntityType registry to use a Forge based registry
  patches/minecraft/net/minecraft/util/registry/IRegistry.java.patch
Labels: 1.13, Assigned, Bug

#5490 [1.13] Fix some minor patch regressions
  patches/minecraft/net/minecraft/block/BlockCrops.java.patch
  patches/minecraft/net/minecraft/client/gui/inventory/GuiContainerCreative.java.patch
  patches/minecraft/net/minecraft/tileentity/TileEntityBeacon.java.patch
  patches/minecraft/net/minecraft/world/WorldEntitySpawner.java.patch
Labels: 1.13, Assigned, Regression

#5464 Make BannerPattern extensible
  patches/minecraft/net/minecraft/tileentity/BannerPattern.java.patch
  src/main/resources/forge.exc
Labels: 1.13, Assigned, Feature

#5452 [1.13.x] Fix GuiEnchantment throwing ArrayIndexOutOfBoundsException
  patches/minecraft/net/minecraft/client/gui/GuiEnchantment.java.patch
Labels: 1.13, Assigned, Bug

#5526 [1.13] Remove EnumFacing internal ID maps from AT file
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.13, Cleanup

#5474 Add back missing ItemColors patch
  patches/minecraft/net/minecraft/client/renderer/color/ItemColors.java.patch
Labels: 1.13, Regression

#5566 Fix entity shearing logic
  patches/minecraft/net/minecraft/entity/monster/EntitySnowman.java.patch
  patches/minecraft/net/minecraft/entity/passive/EntitySheep.java.patch
Labels: 1.13, Bug

#5553 [1.13] Update MDK Readme.txt
  mdk/README.txt
Labels: 1.13, Cleanup

#5480 Add missing constructors to match existing vanilla constructors
  patches/minecraft/net/minecraft/client/settings/KeyBinding.java.patch
Labels: 1.13, Cleanup
