Repository MinecraftForge/MinecraftForge, pull requests merged in 2020-01, with the labels that each got.

#6337 Revert one of the hunks of #6216, which was actually correct as it was.
  patches/minecraft/net/minecraft/client/renderer/texture/NativeImage.java.patch
Labels: 1.14, Assigned, Bug

#6359 Fix capabilities becoming inaccessible on returning from end
  patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch
Labels: 1.14, Assigned, Bug

#6407 [1.15.x] Remove unused parameter from ElementBuilder#rotation (fixes #6321)
  src/main/java/net/minecraftforge/client/model/generators/ModelBuilder.java
Labels: 1.15, Assigned, BreakingChange, Cleanup

#6338 [1.14.x] Remove unused parameter from ElementBuilder#rotation (fixes #6321)
  src/main/java/net/minecraftforge/client/model/generators/ModelBuilder.java
Labels: 1.14, Assigned, Cleanup

#6395 InputEvent.RawMouseEvent fix
  patches/minecraft/net/minecraft/client/MouseHelper.java.patch
Labels: 1.15, Assigned, Bug

#6389 Add support for custom nether portal frame blocks
  patches/minecraft/net/minecraft/block/NetherPortalBlock.java.patch
  patches/minecraft/net/minecraft/item/FlintAndSteelItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
Labels: 1.15, Assigned, Feature

#6408 [1.15.x] Fix validation in RotationBuilder#angle (fixes #6323)
  src/main/java/net/minecraftforge/client/model/generators/ModelBuilder.java
Labels: 1.15, Assigned, Bug

#6417 [1.14] Add support for custom nether portal frame blocks
  patches/minecraft/net/minecraft/block/NetherPortalBlock.java.patch
  patches/minecraft/net/minecraft/item/FlintAndSteelItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
Labels: 1.14, Assigned, Feature

#6047 [1.15] Add new InputEvent.ClickInputEvent, addresses #5802
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/InputEvent.java
Labels: 1.15, Assigned, Feature, New Event

#6416 [1.15.x] Added entity nameplate rendering event hook
  patches/minecraft/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
  src/main/java/net/minecraftforge/client/event/RenderLivingEvent.java
  src/main/java/net/minecraftforge/client/event/RenderNameplateEvent.java
  src/test/java/net/minecraftforge/debug/client/rendering/NameplateRenderingEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.15, Assigned, BreakingChange, Feature

#6433 Use extended version of getLightValue in all places
  patches/minecraft/net/minecraft/block/Block.java.patch
  patches/minecraft/net/minecraft/client/renderer/BlockModelRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  patches/minecraft/net/minecraft/world/IBlockReader.java.patch
  patches/minecraft/net/minecraft/world/chunk/ChunkPrimer.java.patch
  patches/minecraft/net/minecraft/world/chunk/storage/ChunkSerializer.java.patch
  patches/minecraft/net/minecraft/world/gen/NoiseChunkGenerator.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
Labels: 1.15, Assigned, BreakingChange, Bug

#6452 Use delegates for RenderTypeLookup - Fixes #6449
  patches/minecraft/net/minecraft/client/renderer/RenderTypeLookup.java.patch
Labels: 1.15, Assigned, Bug, Rendering

#6455 Fixed rounding issue with entity navigation fix
  patches/minecraft/net/minecraft/pathfinding/PathNavigator.java.patch
  patches/minecraft/net/minecraft/pathfinding/SwimmerPathNavigator.java.patch
Labels: 1.14, Assigned, Bug

#6456 Fixed rounding issue with entity navigation fix (1.15)
  patches/minecraft/net/minecraft/pathfinding/PathNavigator.java.patch
  patches/minecraft/net/minecraft/pathfinding/SwimmerPathNavigator.java.patch
Labels: 1.15, Assigned, Bug

#6460 [1.15.x] Fix Widget FG Color to allow black
  patches/minecraft/net/minecraft/client/gui/widget/Widget.java.patch
  src/main/java/net/minecraftforge/fml/client/config/GuiButtonExt.java
Labels: 1.15, Assigned, Bug

#6461 Updated method names referencing ItemStackTileEntityRenderer
  patches/minecraft/net/minecraft/client/renderer/ItemRenderer.java.patch
  patches/minecraft/net/minecraft/item/Item.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
Labels: 1.15, Assigned, BreakingChange, Cleanup

#6468 Fixed issue in #6461
  patches/minecraft/net/minecraft/item/Item.java.patch
Labels: 1.15, Bug

#6437 Cleanup fml package and fix HoverChecker
  patches/minecraft/net/minecraft/client/gui/screen/MainMenuScreen.java.patch
  patches/minecraft/net/minecraft/client/gui/screen/Screen.java.patch
  patches/minecraft/net/minecraft/client/gui/screen/inventory/CreativeScreen.java.patch
  src/main/java/net/minecraftforge/client/gui/ScrollPanel.java
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/fml/ResourceLocationUtils.java
  src/main/java/net/minecraftforge/fml/StackTraceUtils.java
  src/main/java/net/minecraftforge/fml/StartupQuery.java
  src/main/java/net/minecraftforge/fml/client/ClientModLoader.java
  src/main/java/net/minecraftforge/fml/client/FMLConfigGuiFactory.java
  src/main/java/net/minecraftforge/fml/client/IModGuiFactory.java
  src/main/java/net/minecraftforge/fml/client/TextureTracker.java
  src/main/java/net/minecraftforge/fml/client/config/ConfigGuiType.java
  src/main/java/net/minecraftforge/fml/client/config/DummyConfigElement.java
  src/main/java/net/minecraftforge/fml/client/config/GuiCheckBox.java
  src/main/java/net/minecraftforge/fml/client/config/GuiMessageDialog.java
  src/main/java/net/minecraftforge/fml/client/config/IArrayEntry.java
  src/main/java/net/minecraftforge/fml/client/config/IConfigElement.java
  src/main/java/net/minecraftforge/fml/client/config/IConfigEntry.java
  src/main/java/net/minecraftforge/fml/client/event/ConfigChangedEvent.java
  src/main/java/net/minecraftforge/fml/client/gui/GuiAccessDenied.java
  src/main/java/net/minecraftforge/fml/client/gui/GuiBackupFailed.java
  src/main/java/net/minecraftforge/fml/client/gui/GuiUtils.java
  src/main/java/net/minecraftforge/fml/client/gui/HoverChecker.java
  src/main/java/net/minecraftforge/fml/client/gui/screen/ConfirmationScreen.java
  src/main/java/net/minecraftforge/fml/client/gui/screen/LoadingErrorScreen.java
  src/main/java/net/minecraftforge/fml/client/gui/screen/ModListScreen.java
  src/main/java/net/minecraftforge/fml/client/gui/screen/NotificationScreen.java
  src/main/java/net/minecraftforge/fml/client/gui/widget/ExtendedButton.java
  src/main/java/net/minecraftforge/fml/client/gui/widget/ModListWidget.java
  src/main/java/net/minecraftforge/fml/client/gui/widget/Slider.java
  src/main/java/net/minecraftforge/fml/client/gui/widget/UnicodeGlyphButton.java
  src/main/java/net/minecraftforge/fml/common/ClassNameUtils.java
  src/main/java/net/minecraftforge/fml/common/IFMLHandledException.java
  src/main/java/net/minecraftforge/fml/common/IWorldGenerator.java
  src/main/java/net/minecraftforge/fml/common/network/IGuiHandler.java
  src/main/java/net/minecraftforge/fml/common/registry/ExistingSubstitutionException.java
  src/main/java/net/minecraftforge/fml/config/ConfigFileTypeHandler.java
  src/main/java/net/minecraftforge/fml/config/ConfigTracker.java
  src/main/java/net/minecraftforge/fml/config/ModConfig.java
  src/main/java/net/minecraftforge/fml/packs/ModFileResourcePack.java
Labels: 1.15, BreakingChange, Cleanup

#6476 (1.14.x)Fixed Brown Mooshrooms dropping Red Mushrooms when sheared
  patches/minecraft/net/minecraft/entity/passive/MooshroomEntity.java.patch
Labels: 1.14, Assigned, Bug

#6404 [1.15] Reimplemented the ITeleporter interface
  patches/minecraft/net/minecraft/entity/Entity.java.patch
  patches/minecraft/net/minecraft/entity/item/EnderPearlEntity.java.patch
  patches/minecraft/net/minecraft/entity/item/ItemEntity.java.patch
  patches/minecraft/net/minecraft/entity/item/minecart/ContainerMinecartEntity.java.patch
  patches/minecraft/net/minecraft/entity/merchant/villager/AbstractVillagerEntity.java.patch
  patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch
  patches/minecraft/net/minecraft/world/Teleporter.java.patch
  src/main/java/net/minecraftforge/common/util/ITeleporter.java
  src/main/java/net/minecraftforge/server/command/CommandSetDimension.java
  src/main/resources/forge.exc
Labels: 1.15, Assigned, Feature

#6466 [1.15.x] Small Forge config fixes
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.15, Bug, Cleanup

#6465 Defer material getting for ChestTileEntityRenderer into seperate function
  patches/minecraft/net/minecraft/client/renderer/tileentity/ChestTileEntityRenderer.java.patch
Labels: 1.15, Feature

#6451 Fix RightClickBlock code differences between client and server implementation
  patches/minecraft/net/minecraft/client/multiplayer/PlayerController.java.patch
  patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch
Labels: 1.15, Bug

#6450 Fix incorrectly ported patch for restoreBlurMipmap
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/texture/Texture.java.patch
Labels: 1.15, Bug, Rendering

#6473 Fix NullPointerException on java 8u242 in dev environment.
  src/userdev/java/net/minecraftforge/userdev/LaunchTesting.java
Labels: 1.15

#6444 Clean up a bunch of render events
  patches/minecraft/net/minecraft/client/renderer/FirstPersonRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/ItemFrameRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/LivingRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/PlayerRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/DrawHighlightEvent.java
  src/main/java/net/minecraftforge/client/event/RenderHandEvent.java
  src/main/java/net/minecraftforge/client/event/RenderItemInFrameEvent.java
  src/main/java/net/minecraftforge/client/event/RenderLivingEvent.java
  src/main/java/net/minecraftforge/client/event/RenderPlayerEvent.java
  src/main/java/net/minecraftforge/client/event/RenderSpecificHandEvent.java
Labels: 1.15, BreakingChange, Rendering

#6481 Fixed Attacks/Punches not Registering
  src/main/java/net/minecraftforge/client/extensions/IForgeKeybinding.java
Labels: 1.15, Bug
