Repository MinecraftForge/MinecraftForge, pull requests merged in 2020-10, with the labels that each got.

#7337 Fix modded EntityClassifications
  patches/minecraft/net/minecraft/entity/EntityClassification.java.patch
  patches/minecraft/net/minecraft/world/gen/feature/jigsaw/JigsawPattern.java.patch
  src/main/java/net/minecraftforge/common/IExtensibleEnum.java
Labels: 1.16.2, Assigned, Bug

#7373 Fix toggleable keybindings still being active while in GUI
  patches/minecraft/net/minecraft/client/settings/ToggleableKeyBinding.java.patch
  src/main/java/net/minecraftforge/client/SkyRenderHandler.java
  src/test/java/net/minecraftforge/debug/world/BiomeLoadingEventTest.java
Labels: 1.16.2, Assigned, Bug

#7381 Fix MC-201374
  patches/minecraft/net/minecraft/block/CampfireBlock.java.patch
Labels: 1.16.2, Assigned, Vanilla Bug

#7384 Added "Bukkit Plugin" to InvalidModIdentifier
  src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/InvalidModIdentifier.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.16.2, Assigned

#7393 [1.15.x] Add mixin 0.8.1
  build.gradle
Labels: 1.15, Feature

#7378 Add back patches to Screen allowing for item tooltips to be auto wrapped again
  patches/minecraft/net/minecraft/client/gui/screen/Screen.java.patch
  patches/minecraft/net/minecraft/client/gui/screen/inventory/CreativeScreen.java.patch
Labels: 1.16.2, Assigned, Bug, Regression

#7344 Make it possible to modify the spawn lists for structures
  patches/minecraft/net/minecraft/server/MinecraftServer.java.patch
  patches/minecraft/net/minecraft/world/gen/NoiseChunkGenerator.java.patch
  patches/minecraft/net/minecraft/world/gen/feature/structure/FortressStructure.java.patch
  patches/minecraft/net/minecraft/world/gen/feature/structure/OceanMonumentStructure.java.patch
  patches/minecraft/net/minecraft/world/gen/feature/structure/PillagerOutpostStructure.java.patch
  patches/minecraft/net/minecraft/world/gen/feature/structure/Structure.java.patch
  patches/minecraft/net/minecraft/world/gen/feature/structure/SwampHutStructure.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeStructure.java
  src/main/java/net/minecraftforge/common/world/StructureSpawnManager.java
  src/main/java/net/minecraftforge/event/world/StructureSpawnListGatherEvent.java
  src/test/java/net/minecraftforge/debug/world/StructureSpawnListGatherEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16.2, Assigned, Feature, New Event

#7385 Added Basic Class-Level SAS Capability to checkSAS, added Vector4f to SAS
  build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/CheckSAS.groovy
  patches/minecraft/net/minecraft/util/math/vector/Vector4f.java.patch
  src/main/resources/forge.sas
Labels: 1.16.2, Assigned, Cleanup

#7398 Additions to the mdk build.gradle to accommodate datagens.
  mdk/build.gradle
Labels: 1.16, 1.16.2, Assigned

#7408 DynamicBucketModel Cover Texture Present Fix
  src/main/java/net/minecraftforge/client/model/DynamicBucketModel.java
Labels: 1.16.2, Assigned, Bug

#7355 [1.16.x] Add event for player changing game mode
  patches/minecraft/net/minecraft/client/network/play/NetworkPlayerInfo.java.patch
  patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/ClientPlayerChangeGameModeEvent.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/entity/player/PlayerEvent.java
  src/test/java/net/minecraftforge/debug/entity/player/PlayerGameModeEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16, Assigned, Feature, New Event

#7379 Adds tag support for Enchantments, Potions, and TileEntityTypes
  patches/minecraft/net/minecraft/enchantment/Enchantment.java.patch
  patches/minecraft/net/minecraft/potion/Potion.java.patch
  patches/minecraft/net/minecraft/tileentity/TileEntityType.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/custom_tag_types_test/tags/enchantments/fire.json
  src/generated_test/resources/data/custom_tag_types_test/tags/potions/damage.json
  src/generated_test/resources/data/custom_tag_types_test/tags/tile_entity_types/storage.json
  src/main/java/net/minecraftforge/registries/GameData.java
  src/test/java/net/minecraftforge/debug/misc/CustomTagTypesTest.java
Labels: 1.16.2, Assigned, Feature

#7317 [1.16.3] Extended ITeleporter Interface
  patches/minecraft/net/minecraft/entity/Entity.java.patch
  patches/minecraft/net/minecraft/entity/player/ServerPlayerEntity.java.patch
  src/main/java/net/minecraftforge/common/util/ITeleporter.java
Labels: 1.16.2, Assigned, Bug, Feature, Regression

#7434 Fix data pack biomes failing to load in SingleBiomeProvider
  patches/minecraft/net/minecraft/world/biome/Biome.java.patch
  patches/minecraft/net/minecraft/world/gen/FlatGenerationSettings.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/world/BiomeLoadingEvent.java
Labels: 1.16.2, Feature

#7387 Reimplement nametag distance attribute, fix attribute translation keys
  patches/minecraft/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.16, Assigned, Bug, Confirmed, Regression
