Repository MinecraftForge/MinecraftForge, pull requests merged in 2020-06, with the labels that each got.

#6748 Fix "overlayMessage" rendering in ForgeIngameGui being different than vanilla
  src/main/java/net/minecraftforge/client/gui/ForgeIngameGui.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.15, Bug

#6742 Add custom registry type support to DeferredRegister.
  src/main/java/net/minecraftforge/fml/RegistryObject.java
  src/main/java/net/minecraftforge/registries/DeferredRegister.java
  src/main/java/net/minecraftforge/registries/IForgeRegistry.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
  src/main/java/net/minecraftforge/registries/RegistryBuilder.java
  src/test/java/net/minecraftforge/debug/DeferredRegistryTest.java
  src/test/java/net/minecraftforge/debug/block/PistonEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.15, Work In Progress

#6758 Added ProjectileImpactEvent.FireworkRocket
  patches/minecraft/net/minecraft/entity/item/FireworkRocketEntity.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/ProjectileImpactEvent.java
Labels: 1.15, Feature, New Event

#6699 Fix StartupQuery not working more than once on the client
  src/main/java/net/minecraftforge/fml/StartupQuery.java
Labels: 1.15, Bug

#6537 Supply matrixstack to IRenderHandler where possible. Closes #6439
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  src/main/java/net/minecraftforge/client/CloudRenderHandler.java
  src/main/java/net/minecraftforge/client/SkyRenderHandler.java
  src/main/java/net/minecraftforge/client/WeatherRenderHandler.java
Labels: 1.15, Assigned, Rendering

#6764 Fixed ItemStack comparison ignoring capabilities when stack nbt is null.
  patches/minecraft/net/minecraft/item/ItemStack.java.patch
Labels: 1.15, Bug

#6754 Fixed --server argument crashing the client
  patches/minecraft/net/minecraft/client/gui/ResourceLoadProgressGui.java.patch
Labels: 1.15, Bug

#6515 Add system for dimensions to be marked for deletion
  src/main/java/net/minecraftforge/common/DimensionManager.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/test/java/net/minecraftforge/debug/world/MarkDimensionForDeletionTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.15, Assigned, Feature

#6740 Potential userProperties Fix
  src/userdev/java/net/minecraftforge/userdev/LaunchTesting.java
Labels: 1.15, Bug

#6784 Potential userProperties Fix (#6740)
  src/userdev/java/net/minecraftforge/userdev/LaunchTesting.java
Labels: 1.14, Assigned, Bug

#6789 Throw an exception from DeferredRegister when trying to register entries after registry event has fired
  src/main/java/net/minecraftforge/registries/DeferredRegister.java
Labels: 1.15, Assigned

#6793 DirectoryCache: use custom comparator.
  patches/minecraft/net/minecraft/data/DirectoryCache.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/data_gen_test/tags/blocks/thing/one.json
  src/generated_test/resources/data/data_gen_test/tags/blocks/thing/three.json
  src/generated_test/resources/data/data_gen_test/tags/blocks/thing/two.json
  src/generated_test/resources/data/data_gen_test/tags/blocks/things.json
  src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
  src/test/java/net/minecraftforge/debug/world/MarkDimensionForDeletionTest.java
Labels: 1.15, Assigned, Bug

#6765 [1.15.x] DataGenerator for LootTable, replacing shears item to shears tag
  src/generated/resources/data/forge/tags/items/shears.json
  src/generated/resources/data/minecraft/loot_tables/blocks/acacia_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/birch_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/cobweb.json
  src/generated/resources/data/minecraft/loot_tables/blocks/dark_oak_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/dead_bush.json
  src/generated/resources/data/minecraft/loot_tables/blocks/fern.json
  src/generated/resources/data/minecraft/loot_tables/blocks/grass.json
  src/generated/resources/data/minecraft/loot_tables/blocks/jungle_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/large_fern.json
  src/generated/resources/data/minecraft/loot_tables/blocks/oak_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/seagrass.json
  src/generated/resources/data/minecraft/loot_tables/blocks/spruce_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/tall_grass.json
  src/generated/resources/data/minecraft/loot_tables/blocks/tall_seagrass.json
  src/generated/resources/data/minecraft/loot_tables/blocks/vine.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeItemTagsProvider.java
  src/main/java/net/minecraftforge/common/data/ForgeLootTableProvider.java
Labels: 1.15, Assigned

#6702 Fire the levelchange event after having enchanted an item
  patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch
Labels: 1.14, Assigned, Bug

#6530 Add missing localization for attributes
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.14, Assigned, Bug

#6708 Allow RayTraceContext to be constructed with a null entity.
  patches/minecraft/net/minecraft/util/math/RayTraceContext.java.patch
Labels: 1.15, Feature

#6815 Fix z-level issues on item tooltips
  src/main/java/net/minecraftforge/fml/client/gui/GuiUtils.java
Labels: 1.16, Assigned, Bug, Rendering

#6817 Fixed sneaking while swimming
  patches/minecraft/net/minecraft/entity/LivingEntity.java.patch
Labels: 1.16, Assigned, Bug

#6819 Retarget Block.Properties patch to the new AbstractBlock, reintroduce harvestLevel and harvestTool fields
  patches/minecraft/net/minecraft/block/AbstractBlock.java.patch
Labels: 1.16, Assigned, Regression

#6827 Fix creative screen GUI having the arrow buttons misaligned
  patches/minecraft/net/minecraft/client/gui/screen/inventory/CreativeScreen.java.patch
Labels: 1.16, Bug, Rendering

#6822 [1.16.x] Allow GlobalEntityTypeAttributes' EntityType -> AttributeModifierMap to be added to
  patches/minecraft/net/minecraft/entity/ai/attributes/GlobalEntityTypeAttributes.java.patch
Labels: 1.16, Assigned, Feature

#6861 [1.15] Fix Language.javaLocale parsing
  patches/minecraft/net/minecraft/client/resources/Language.java.patch
Labels: 1.15, Assigned, Bug, LTS Backport

#6848 Fix access levels being hardcoded to private via patch overriding AT entry
  patches/minecraft/net/minecraft/data/loot/EntityLootTables.java.patch
Labels: 1.16, Assigned, Bug, Regression

#6825 Make Type classes safe to use in concurrent loading
  src/main/java/net/minecraftforge/common/PlantType.java
  src/main/java/net/minecraftforge/common/ToolType.java
  src/main/java/net/minecraftforge/common/util/BlockSnapshot.java
Labels: 1.16

#6875 [1.16.x] Fix IItemHandler wrappers for chests not updating both chests
  patches/minecraft/net/minecraft/tileentity/ChestTileEntity.java.patch
Labels: 1.16, Assigned, Bug

#6862 [1.16] Fix Language.javaLocale parsing
  patches/minecraft/net/minecraft/client/resources/Language.java.patch
Labels: 1.16, Assigned, Bug

#6865 1.16 Fix datagen resolving tags and exploding.
  build.gradle
  patches/minecraft/net/minecraft/item/crafting/Ingredient.java.patch
  src/generated/resources/data/minecraft/loot_tables/blocks/nether_sprouts.json
  src/generated/resources/data/minecraft/loot_tables/blocks/twisting_vines.json
  src/generated/resources/data/minecraft/loot_tables/blocks/weeping_vines.json
  src/generated/resources/data/minecraft/recipes/chain.json
  src/generated/resources/data/minecraft/recipes/crimson_fence.json
  src/generated/resources/data/minecraft/recipes/crimson_fence_gate.json
  src/generated/resources/data/minecraft/recipes/crimson_sign.json
  src/generated/resources/data/minecraft/recipes/furnace.json
  src/generated/resources/data/minecraft/recipes/netherite_ingot.json
  src/generated/resources/data/minecraft/recipes/soul_campfire.json
  src/generated/resources/data/minecraft/recipes/soul_torch.json
  src/generated/resources/data/minecraft/recipes/warped_fence.json
  src/generated/resources/data/minecraft/recipes/warped_fence_gate.json
  src/generated/resources/data/minecraft/recipes/warped_sign.json
  src/main/java/net/minecraftforge/common/data/ForgeItemTagsProvider.java
  src/main/java/net/minecraftforge/common/data/ForgeRecipeProvider.java
  src/main/java/net/minecraftforge/fml/ModLoader.java
Labels: 1.16, Assigned, Bug, Regression

#6874 [1.15.x] Fix IItemHandler wrappers for chests not updating both chests
  patches/minecraft/net/minecraft/tileentity/ChestTileEntity.java.patch
Labels: 1.15, Assigned, Bug, LTS Backport

#6881 [1.16] Add senderUUID to ClientChatReceivedEvent
  patches/minecraft/net/minecraft/client/network/play/ClientPlayNetHandler.java.patch
  src/main/java/net/minecraftforge/client/event/ClientChatReceivedEvent.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: 1.16, Assigned, Feature

#6877 [1.16] Allow any armor to have custom knockback resistance
  patches/minecraft/net/minecraft/item/ArmorItem.java.patch
Labels: 1.16, Assigned, Feature

#6824 Fix forge loading screen
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/ClientVisualization.java
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/EarlyProgressVisualization.java
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/StartupMessageManager.java
  src/main/java/net/minecraftforge/fml/client/EarlyLoaderGUI.java
Labels: 1.16, Assigned, Bug

#6872 [1.16.x] Added Hoe to ToolType
  patches/minecraft/net/minecraft/item/HoeItem.java.patch
  src/main/java/net/minecraftforge/common/ToolType.java
Labels: 1.16, Assigned, Bug
