Repository MinecraftForge/MinecraftForge, pull requests merged in 2020-11, with the labels that each got.

#7216 [1.16.x] Render local player when the renderViewEntity is not the local player
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  src/test/java/net/minecraftforge/debug/client/rendering/RenderLocalPlayerTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16, Assigned, Feature

#7414 Call Harvest check event even if the block doesn't require any tool
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.16, Assigned, Feature

#7440 [1.16] Fix Banner.toItem causing crash on server
  src/main/resources/forge.sas
Labels: 1.16.2, Assigned, Bug

#7454 Don't overwrite PlayerAdvancement's player with a fake one
  patches/minecraft/net/minecraft/server/management/PlayerList.java.patch
Labels: 1.16, Assigned, Bug

#7442 Add Player context to AnvilUpdateEvent
  patches/minecraft/net/minecraft/inventory/container/RepairContainer.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/AnvilUpdateEvent.java
Labels: 1.16, Assigned, Feature

#7463 Allow for custom command argument types
  patches/minecraft/net/minecraft/command/arguments/ArgumentTypes.java.patch
  patches/minecraft/net/minecraft/network/play/server/SCommandListPacket.java.patch
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/network/CommandTreeCleaner.java
  src/main/java/net/minecraftforge/network/VanillaConnectionNetworkFilter.java
  src/main/java/net/minecraftforge/server/command/EnumArgument.java
  src/main/resources/forge.sas
Labels: 1.16, Assigned, Feature

#7445 Fix dims on servers not loading the first run
  patches/minecraft/net/minecraft/server/Main.java.patch
Labels: 1.16, 1.16.2, Assigned, Bug, Confirmed, Vanilla Bug

#7319 [1.15] Fix possible crash when using rendering regionCache
  src/main/java/net/minecraftforge/client/MinecraftForgeClient.java
  src/main/java/net/minecraftforge/client/model/animation/TileEntityRendererAnimation.java
Labels: 1.15, Bug, LTS Backport

#7482 Fix forge registry types that have private constructors (BlockStateProviderType, BlockPlacerType, FoliagePlacerType, TreeDecoratorType)
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.16, Assigned

#7483 Fix concurrency issue in StartupMessageManager
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/StartupMessageManager.java
Labels: 1.16, Assigned, Bug, LTS Backport

#7471 Fix #7363 (Removing structures causes worlds to be unsaveable)
  patches/minecraft/net/minecraft/world/chunk/storage/ChunkSerializer.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.16, Assigned, Bug, Vanilla Bug

#7446 Fix food bar not rendering when non-living entities are mounted
  src/main/java/net/minecraftforge/client/gui/ForgeIngameGui.java
Labels: 1.16, Assigned, Bug, Confirmed

#7441 Fix translucent blocks not rendering properly when moved by pistons on fabulous
  patches/minecraft/net/minecraft/client/renderer/tileentity/PistonTileEntityRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: 1.16, Assigned, Bug, Rendering

#7456 Add support for referencing forge's resources and specifying existing mods to data generators
  patches/minecraft/net/minecraft/data/Main.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/data_gen_test/tags/blocks/test.json
  src/main/java/net/minecraftforge/client/model/generators/ModelProvider.java
  src/main/java/net/minecraftforge/common/data/ExistingFileHelper.java
  src/main/java/net/minecraftforge/fml/DatagenModLoader.java
  src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
Labels: 1.16, Feature, Triage

#7448 Implement feature for mods to define new world types
  patches/minecraft/net/minecraft/client/gui/screen/BiomeGeneratorTypeScreens.java.patch
  patches/minecraft/net/minecraft/client/gui/screen/CreateWorldScreen.java.patch
  patches/minecraft/net/minecraft/client/gui/screen/WorldOptionsScreen.java.patch
  patches/minecraft/net/minecraft/world/gen/settings/DimensionGeneratorSettings.java.patch
  src/fmllauncher/java/net/minecraftforge/fml/loading/VersionSupportMatrix.java
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/ForgeWorldTypeScreens.java
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/world/ForgeWorldType.java
  src/main/java/net/minecraftforge/registries/ForgeRegistries.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/client/rendering/RenderLocalPlayerTest.java
  src/test/java/net/minecraftforge/debug/world/ForgeWorldTypeTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16, Feature
