Repository MinecraftForge/MinecraftForge, pull requests merged in 2020-05, with the labels that each got.

#6542 Fix allow values comment referencing disallowed values
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: 1.15, Assigned, Bug

#6573 Add fix for issue 6286. Changed null return to throw exception as per…
  src/main/java/net/minecraftforge/common/PlantType.java
  src/test/java/net/minecraftforge/debug/block/CustomPlantTypeTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.14, Assigned, Bug

#6579 Allow colors of tooltip to be specified in GuiUtils tooltip methods
  src/main/java/net/minecraftforge/fml/client/gui/GuiUtils.java
Labels: 1.15, Assigned, Feature

#6585 Add missing localization for attributes (1.15)
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.15, Assigned, Bug

#6609 Un-hardcoding milk bucket being universal effect cure
  patches/minecraft/net/minecraft/item/MilkBucketItem.java.patch
Labels: 1.15, Assigned, Bug

#6621 Change recipe condition log level to debug.
  patches/minecraft/net/minecraft/item/crafting/RecipeManager.java.patch
Labels: 1.15, Assigned, Cleanup

#6622 Fix loot table resource leak. #6248
  patches/minecraft/net/minecraft/world/storage/loot/LootTableManager.java.patch
Labels: 1.15, Assigned, Bug

#6628 ChunkDataEvent.Save: If chunk's world is null, use world from calling context
  patches/minecraft/net/minecraft/world/server/ChunkManager.java.patch
  src/main/java/net/minecraftforge/event/world/ChunkDataEvent.java
  src/main/java/net/minecraftforge/event/world/ChunkEvent.java
  src/test/java/net/minecraftforge/debug/world/ChunkDataEventSaveNullWorldTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.15, Assigned, Bug

#6631 Fix precheck for if an ItemHandler is full
  src/main/java/net/minecraftforge/items/VanillaInventoryCodeHooks.java
Labels: 1.15, Assigned, Bug

#6632 Make HarvestCheck always fire
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.15, Assigned, Bug

#6633 Fix issue with providing a null ItemStack to onPlayerDestroyItem
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.15, Assigned, Bug

#6638 [1.15] Fix IForgeBlock.removedByPlayer not firing on the client.
  patches/minecraft/net/minecraft/client/multiplayer/PlayerController.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
Labels: 1.15, Assigned, Bug

#6684 [1.15]Fixed FluidTank.drain calling onContentsChanged when simulating
  src/main/java/net/minecraftforge/fluids/capability/templates/FluidTank.java
Labels: 1.15, Bug, Fluids

#6682 Fix Minecraft screens escape key not matching done button behavior
  patches/minecraft/com/mojang/realmsclient/gui/screens/RealmsGenericErrorScreen.java.patch
  patches/minecraft/net/minecraft/client/gui/screen/MultiplayerScreen.java.patch
  patches/minecraft/net/minecraft/client/gui/screen/OptionsScreen.java.patch
Labels: 1.15, Vanilla Bug

#6680 GH-6594 Fire CropGrowEvents for Bamboo
  patches/minecraft/net/minecraft/block/BambooBlock.java.patch
Labels: 1.15, Bug

#6666 [1.14.x] Cherry-Pick: Fix Forge's tps and gen commands.
  src/main/java/net/minecraftforge/server/command/ChunkGenWorker.java
  src/main/java/net/minecraftforge/server/command/CommandTps.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.14, Assigned, Bug

#6662 Cherry-Pick of 1.15.x Advancement Recursion Fix
  patches/minecraft/net/minecraft/advancements/AdvancementList.java.patch
  patches/minecraft/net/minecraft/advancements/PlayerAdvancements.java.patch
  src/main/java/net/minecraftforge/common/AdvancementLoadFix.java
  src/main/java/net/minecraftforge/common/ForgeConfig.java
Labels: 1.14, Assigned, Bug

#6656 [1.15.2] Beehive validate in livingtick
  patches/minecraft/net/minecraft/entity/passive/BeeEntity.java.patch
Labels: 1.15, Feature

#6610 Backport: Fix ChunkDataEvent.Load not firing, it now fires in the aync thread. …
  patches/minecraft/net/minecraft/world/chunk/storage/ChunkSerializer.java.patch
  src/main/java/net/minecraftforge/event/world/ChunkDataEvent.java
Labels: 1.14, Assigned, Bug

#6600 Don't resolve symbolic links in ModDirTransformerDiscoverer
  src/fmllauncher/java/net/minecraftforge/fml/loading/ModDirTransformerDiscoverer.java
Labels: 1.15, Bug

#6644 Clear server config after server is shut down
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
  src/main/java/net/minecraftforge/fml/config/ConfigFileTypeHandler.java
  src/main/java/net/minecraftforge/fml/config/ConfigTracker.java
  src/main/java/net/minecraftforge/fml/server/ServerLifecycleHooks.java
Labels: 1.15, Bug

#6519 Fix ChunkWatchEvent.(Un)Watch not firing correctly
  patches/minecraft/net/minecraft/world/server/ChunkManager.java.patch
  src/main/java/net/minecraftforge/event/world/ChunkWatchEvent.java
  src/test/java/net/minecraftforge/debug/entity/GravityAttributeTest.java
  src/test/java/net/minecraftforge/debug/world/ChunkWatchEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.14, Assigned, Bug

#6582 Switch model generation from Object.toString() to IProperty.getName(T)
  src/main/java/net/minecraftforge/client/model/generators/MultiPartBlockStateBuilder.java
  src/main/java/net/minecraftforge/client/model/generators/VariantBlockStateBuilder.java
Labels: 1.15, Assigned, Bug

#6523 Add a way to create Music Discs without requiring a SoundEvent
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  patches/minecraft/net/minecraft/item/MusicDiscItem.java.patch
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/item/MusicDiscTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/music_disc_test/lang/en_us.json
  src/test/resources/assets/music_disc_test/models/item/test_music_disc.json
  src/test/resources/assets/music_disc_test/sounds.json
Labels: 1.15, Feature
