Repository MinecraftForge/MinecraftForge, pull requests merged in 2020-04, with the labels that each got.

#6571 Modded Hill Biomes
  patches/minecraft/net/minecraft/world/biome/Biome.java.patch
  patches/minecraft/net/minecraft/world/gen/layer/HillsLayer.java.patch
Labels: 1.15, Assigned, Feature

#6599 [1.15.x] Add fix for issue 6286. Changed null return to throw exception
  src/main/java/net/minecraftforge/common/PlantType.java
  src/test/java/net/minecraftforge/debug/block/CustomPlantTypeTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.15, Assigned, Bug

#6630 Patch EarlyProgressVisualization on mac
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/ClientVisualization.java
Labels: 1.15, Bug
