Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-02, with the labels that each got.

#7428 [1.16.x] Add loot table ID in Global Loot Modifiers
  patches/minecraft/net/minecraft/loot/LootContext.java.patch
  patches/minecraft/net/minecraft/loot/LootTable.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/forge/loot_modifiers/global_loot_modifiers.json
  src/generated_test/resources/data/global_loot_test/loot_modifiers/dungeon_loot.json
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/loot/LootTableIdCondition.java
  src/test/java/net/minecraftforge/debug/gameplay/loot/GlobalLootModifiersTest.java
Labels: 1.16, Assigned, Cleanup, Feature

#7618 Fix IAngerable entities crashing when reading nbt on client
  patches/minecraft/net/minecraft/entity/monster/EndermanEntity.java.patch
  patches/minecraft/net/minecraft/entity/monster/ZombifiedPiglinEntity.java.patch
  patches/minecraft/net/minecraft/entity/passive/BeeEntity.java.patch
  patches/minecraft/net/minecraft/entity/passive/IronGolemEntity.java.patch
  patches/minecraft/net/minecraft/entity/passive/PolarBearEntity.java.patch
  patches/minecraft/net/minecraft/entity/passive/WolfEntity.java.patch
Labels: 1.16, Assigned, Vanilla Bug

#7554 [1.16] Added multi part entity support
  patches/minecraft/net/minecraft/client/network/play/ClientPlayNetHandler.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/EntityRendererManager.java.patch
  patches/minecraft/net/minecraft/entity/boss/dragon/EnderDragonEntity.java.patch
  patches/minecraft/net/minecraft/entity/boss/dragon/EnderDragonPartEntity.java.patch
  patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch
  patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
  patches/minecraft/net/minecraft/world/server/ChunkManager.java.patch
  patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
  src/main/java/net/minecraftforge/entity/PartEntity.java
Labels: 1.16, Assigned, Feature

#7605 Prevent NullPointerException when adding new loot pool.
  patches/minecraft/net/minecraft/loot/LootTable.java.patch
Labels: 1.16, Assigned, Bug

#7607 Fix onBlockAdded being called twice for ItemEntity placing non-TE blocks
  patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.16, Assigned, Bug, Regression

#7635 Fix config spec in cases of enum class discrepancies
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: 1.16, Assigned, Bug

#7643 Fix a couple places returning an invalid capability from getCapability
  patches/minecraft/net/minecraft/entity/passive/horse/AbstractHorseEntity.java.patch
  patches/minecraft/net/minecraft/tileentity/ChestTileEntity.java.patch
Labels: 1.16, Assigned, Bug

#7642 Reinstate's Forge's Chunk Manager
  patches/minecraft/net/minecraft/server/MinecraftServer.java.patch
  patches/minecraft/net/minecraft/world/ForcedChunksSaveData.java.patch
  patches/minecraft/net/minecraft/world/server/ServerChunkProvider.java.patch
  patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch
  patches/minecraft/net/minecraft/world/server/TicketManager.java.patch
  src/main/java/net/minecraftforge/common/world/ForgeChunkManager.java
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/world/ForgeChunkManagerTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/forge_chunk_manager_test/blockstates/chunk_loader.json
  src/test/resources/assets/forge_chunk_manager_test/models/block/chunk_loader.json
  src/test/resources/assets/forge_chunk_manager_test/models/item/chunk_loader.json
Labels: 1.16, Assigned, Feature

#7515 Allow mods to use custom LootParameter when querying existing loot tables (e.g. blocks).
  patches/minecraft/net/minecraft/loot/LootContext.java.patch
Labels: 1.16, Assigned, Feature

#7648 Fix global cache not being a block render type
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/model/MultiLayerModel.java
Labels: Assigned

#7595 Added MultipartBakedModel.getModelData()
  patches/minecraft/net/minecraft/client/renderer/model/MultipartBakedModel.java.patch
  src/main/java/net/minecraftforge/client/model/data/MultipartModelData.java
Labels: Assigned

#7650 Fix ItemTextureQuadConverter.convertTexture generating wrong quads, fixes #7620
  src/main/java/net/minecraftforge/client/model/ItemTextureQuadConverter.java
  src/test/java/net/minecraftforge/debug/client/model/DynBucketModelTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/dyn_bucket_model_test/models/item/drip_bucket.json
  src/test/resources/assets/dyn_bucket_model_test/models/item/lava_obsidian.json
  src/test/resources/assets/dyn_bucket_model_test/textures/item/drip_bucket.png
  src/test/resources/assets/dyn_bucket_model_test/textures/item/lava_obsidian.png
Labels: Assigned

#7447 [1.15] Fix food bar not rendering when non-living entities are mounted
  src/main/java/net/minecraftforge/client/gui/ForgeIngameGui.java
Labels: 1.15, Assigned, Bug, Confirmed, LTS Backport

#7422 Fix a few FluidUtil issues that were causing DispenseFluidContainer to not function properly
  src/main/java/net/minecraftforge/fluids/FluidUtil.java
  src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockWrapper.java
  src/main/java/net/minecraftforge/fluids/capability/wrappers/BucketPickupHandlerWrapper.java
  src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBlockWrapper.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/fluid/NewFluidTest.java
Labels: 1.16.2, Bug, Cleanup, Fluids, Regression, Triage

#7646 Fix updateItemStackNBT not properly being called using a field transformer
  patches/minecraft/net/minecraft/item/ItemStack.java.patch
  src/main/resources/META-INF/fieldtomethodtransformers.js
Labels: 1.16, Triage, Work In Progress

#7608 Add support for caching of configuration values.
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
  src/main/java/net/minecraftforge/fml/config/ConfigFileTypeHandler.java
  src/test/java/net/minecraftforge/common/ForgeConfigSpecTest.java
Labels: 1.16, Assigned, Feature, Triage
