Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-08, with the labels that each got.

#7936 [1.17.1] Fix EntityInteractSpecific Event not being fired in server
  patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
Labels: 1.17, Assigned, Bug, Regression

#7937 Fix BaseRailBlock not implementing SimpleWaterloggedBlock
  patches/minecraft/net/minecraft/world/level/block/BaseRailBlock.java.patch
Labels: 1.17, Assigned, Bug, Regression

#7939 Rename potion registry fields to match the mojang names
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/registries/ForgeRegistries.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/test/java/net/minecraftforge/debug/misc/CustomTagTypesTest.java
Labels: 1.17, Assigned

#7974 [1.17.x] Add access transformer to make Features.Decorators class public
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Regression, Assigned, 1.17

#7912 [1.17.x] Add a send datapack data to client event
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
  src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
  src/test/java/net/minecraftforge/debug/misc/OnDatapackSynctEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: New Event, Assigned, 1.17

#8001 1.17 Remove neutral mob patches
  patches/minecraft/net/minecraft/world/entity/animal/Bee.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/IronGolem.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/PolarBear.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/Wolf.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/EnderMan.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/ZombifiedPiglin.java.patch
Labels: Cleanup, Assigned, 1.17

#7941 [1.17.1] Allow to check spawner block entity in events
  patches/minecraft/net/minecraft/world/level/BaseSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/SpawnerBlockEntity.java.patch
  src/test/java/net/minecraftforge/debug/entity/CheckSpawnEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Work In Progress, 1.17

#7973 Track the active mod within DeferredWorkQueue
  fmlcore/src/main/java/net/minecraftforge/fml/DeferredWorkQueue.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
  src/fmlcommon/java/net/minecraftforge/fml/event/lifecycle/ParallelDispatchEvent.java
Labels: Feature, BreakingChange, Assigned, 1.17

#7981 [1.17.1] Add custom attack sweep
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  src/main/java/net/minecraftforge/common/ToolActions.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
Labels: Feature, Assigned, 1.17

#7911 [1.17] Add support for forge's "remove" list to tag datagenerators
  build.gradle
  patches/minecraft/net/minecraft/tags/Tag.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/minecraft/tags/blocks/test_tag.json
  src/main/java/net/minecraftforge/common/extensions/IForgeRawTagBuilder.java
  src/main/java/net/minecraftforge/common/extensions/IForgeTagAppender.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/RemoveTagDatagenTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.17

#8021 Add RegisterCapabilitiesEvent
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/capabilities/CapabilityManager.java
  src/main/java/net/minecraftforge/common/capabilities/RegisterCapabilitiesEvent.java
  src/main/java/net/minecraftforge/common/model/animation/CapabilityAnimation.java
  src/main/java/net/minecraftforge/energy/CapabilityEnergy.java
  src/main/java/net/minecraftforge/fluids/capability/CapabilityFluidHandler.java
  src/main/java/net/minecraftforge/items/CapabilityItemHandler.java
Labels: Triage, 1.17

#7884 1.17 minor pack related fixes
  mdk/src/main/resources/pack.mcmeta
  src/main/java/net/minecraftforge/fmllegacy/packs/ModFileResourcePack.java
  src/main/java/net/minecraftforge/fmllegacy/packs/ResourcePackLoader.java
  src/main/resources/pack.mcmeta
  src/test/resources/pack.mcmeta
Labels: Cleanup, Assigned, 1.17

#7997 [1.17] Add Shears ToolActions
  patches/minecraft/net/minecraft/world/item/ShearsItem.java.patch
  patches/minecraft/net/minecraft/world/item/enchantment/DiggingEnchantment.java.patch
  patches/minecraft/net/minecraft/world/level/block/BeehiveBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/PumpkinBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/TripWireBlock.java.patch
  src/generated/resources/data/minecraft/loot_tables/blocks/acacia_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/azalea_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/birch_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/cobweb.json
  src/generated/resources/data/minecraft/loot_tables/blocks/dark_oak_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/dead_bush.json
  src/generated/resources/data/minecraft/loot_tables/blocks/fern.json
  src/generated/resources/data/minecraft/loot_tables/blocks/flowering_azalea_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/grass.json
  src/generated/resources/data/minecraft/loot_tables/blocks/hanging_roots.json
  src/generated/resources/data/minecraft/loot_tables/blocks/jungle_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/large_fern.json
  src/generated/resources/data/minecraft/loot_tables/blocks/nether_sprouts.json
  src/generated/resources/data/minecraft/loot_tables/blocks/oak_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/seagrass.json
  src/generated/resources/data/minecraft/loot_tables/blocks/small_dripleaf.json
  src/generated/resources/data/minecraft/loot_tables/blocks/spruce_leaves.json
  src/generated/resources/data/minecraft/loot_tables/blocks/tall_grass.json
  src/generated/resources/data/minecraft/loot_tables/blocks/tall_seagrass.json
  src/generated/resources/data/minecraft/loot_tables/blocks/twisting_vines.json
  src/generated/resources/data/minecraft/loot_tables/blocks/vine.json
  src/generated/resources/data/minecraft/loot_tables/blocks/weeping_vines.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/ToolActions.java
  src/main/java/net/minecraftforge/common/data/ForgeLootTableProvider.java
  src/main/java/net/minecraftforge/common/loot/CanToolPerformAction.java
Labels: Feature, Assigned, 1.17

#7898 1.17 Cleanup Tag Loading
  patches/minecraft/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
  patches/minecraft/net/minecraft/data/tags/GameEventTagsProvider.java.patch
  patches/minecraft/net/minecraft/server/ServerResources.java.patch
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
  patches/minecraft/net/minecraft/tags/GameEventTags.java.patch
  patches/minecraft/net/minecraft/tags/StaticTagHelper.java.patch
  patches/minecraft/net/minecraft/tags/StaticTags.java.patch
  patches/minecraft/net/minecraft/tags/TagContainer.java.patch
  patches/minecraft/net/minecraft/tags/TagManager.java.patch
  patches/minecraft/net/minecraft/world/item/alchemy/Potion.java.patch
  patches/minecraft/net/minecraft/world/item/enchantment/Enchantment.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/BlockEntityType.java.patch
  patches/minecraft/net/minecraft/world/level/gameevent/GameEvent.java.patch
  src/generated_test/resources/data/custom_tag_types_test/tags/block_entity_types/storage.json
  src/main/java/net/minecraftforge/common/ForgeInternalHandler.java
  src/main/java/net/minecraftforge/common/ForgeTagHandler.java
  src/main/java/net/minecraftforge/common/data/ForgeRegistryTagsProvider.java
  src/main/java/net/minecraftforge/common/extensions/IForgeTagContainer.java
  src/main/java/net/minecraftforge/event/TagsUpdatedEvent.java
  src/main/java/net/minecraftforge/fmllegacy/network/FMLPlayMessages.java
  src/main/java/net/minecraftforge/fmllegacy/network/NetworkHooks.java
  src/main/java/net/minecraftforge/fmllegacy/network/NetworkInitialization.java
  src/main/java/net/minecraftforge/network/VanillaConnectionNetworkFilter.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/misc/CustomTagTypesTest.java
Labels: Bug, Regression, BreakingChange, Cleanup, Assigned, 1.17

#8012 Fix ScrollPanel render calls and usage
  src/main/java/net/minecraftforge/client/gui/ScrollPanel.java
  src/main/java/net/minecraftforge/fmlclient/gui/screen/ModListScreen.java
Labels: Bug, Rendering, Assigned, 1.17

#8040 [1.16.x] Fix all layers of ItemLayerModel being fullbright
  src/main/java/net/minecraftforge/client/model/ItemLayerModel.java
  src/test/resources/assets/new_model_loader_test/blockstates/obj_block.json
  src/test/resources/assets/new_model_loader_test/models/block/obj_block.json
  src/test/resources/assets/new_model_loader_test/models/item/item_layers.json
  src/test/resources/assets/new_model_loader_test/models/item/separate_perspective.json
  src/test/resources/data/forge/loot_modifiers/global_loot_modifiers.json
  src/test/resources/data/global_loot_test/loot_modifiers/smelting.json
  src/test/resources/data/global_loot_test/loot_modifiers/wheat_harvest.json
Labels: Bug, Cleanup, Rendering, Assigned, 1.16, LTS Backport

#8022 Fix ExtendedButton and LoadingErrorScreen rendering
  src/main/java/net/minecraftforge/fmlclient/gui/GuiUtils.java
  src/main/java/net/minecraftforge/fmlclient/gui/screen/LoadingErrorScreen.java
  src/main/java/net/minecraftforge/fmlclient/gui/widget/ExtendedButton.java
Labels: Bug, Rendering, Triage, 1.17

#7985 [1.16.5] Backport OnDatapackSyncEvent from 1.17.1
  patches/minecraft/net/minecraft/server/management/PlayerList.java.patch
  src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
  src/test/java/net/minecraftforge/debug/misc/OnDatapackSynctEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: New Event, Assigned, 1.16, LTS Backport
