Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-06, with the labels that each got.

#7750 Fix the multilayer model using the missing model when a layer isn't defined.
  src/main/java/net/minecraftforge/client/model/MultiLayerModel.java
Labels: 1.16, Bug, Rendering

#7802 Fix vanilla packet splitter remote detection and add advancement packet splitting
  src/main/java/net/minecraftforge/fml/network/NetworkHooks.java
  src/main/java/net/minecraftforge/fml/server/ServerLifecycleHooks.java
  src/main/java/net/minecraftforge/network/ForgeConnectionNetworkFilter.java
  src/main/java/net/minecraftforge/network/NetworkFilters.java
  src/main/java/net/minecraftforge/network/VanillaPacketSplitter.java
Labels: 1.16, Bug, Feature, Triage

#7792 [1.16.x] Add method to get the number of elements in a model builder
  src/main/java/net/minecraftforge/client/model/generators/ModelBuilder.java
Labels: 1.16, Assigned, Feature

#7818 [1.16] Add truncation to FMLStatusPing to work around protocol limits
  src/main/java/net/minecraftforge/fml/client/ClientHooks.java
  src/main/java/net/minecraftforge/fml/client/ExtendedServerListData.java
  src/main/java/net/minecraftforge/fml/network/FMLStatusPing.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.16, Bug, Triage
