Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-07, with the labels that each got.

#7822 Add custom TextureAtlasSprite loaders
  patches/minecraft/net/minecraft/client/renderer/texture/AtlasTexture.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/MinecraftForgeClient.java
  src/main/java/net/minecraftforge/client/extensions/IForgeTextureAtlasSprite.java
  src/main/java/net/minecraftforge/client/textures/ForgeTextureMetadata.java
  src/main/java/net/minecraftforge/client/textures/ITextureAtlasSpriteLoader.java
  src/test/java/net/minecraftforge/debug/client/CustomTASTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/custom_tas_test/models/item/test_item.json
  src/test/resources/assets/custom_tas_test/textures/item/test_item.png
  src/test/resources/assets/custom_tas_test/textures/item/test_item.png.mcmeta
Labels: 1.16, Assigned, Feature

#6982 [1.16] Add data generators for sounds.json
  build.gradle
  patches/minecraft/net/minecraft/data/Main.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/assets/data_gen_test/sounds.json
  src/main/java/net/minecraftforge/common/data/ExistingFileHelper.java
  src/main/java/net/minecraftforge/common/data/SoundDefinition.java
  src/main/java/net/minecraftforge/common/data/SoundDefinitionsProvider.java
  src/main/java/net/minecraftforge/common/data/package-info.java
  src/main/java/net/minecraftforge/fml/DatagenModLoader.java
  src/main/java/net/minecraftforge/fml/ModLoader.java
  src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
  src/userdev/java/net/minecraftforge/userdev/LaunchTesting.java
Labels: 1.16, Assigned, Feature

#7236 Removed sidedness from PacketBuffer methods.
  src/main/resources/forge.sas
Labels: 1.16.2, Assigned, Feature

#7697 Bypass chunk future chain when processing loads and getChunk called.
  patches/minecraft/net/minecraft/world/server/ChunkHolder.java.patch
  patches/minecraft/net/minecraft/world/server/ChunkManager.java.patch
  patches/minecraft/net/minecraft/world/server/ServerChunkProvider.java.patch
Labels: 1.16, Assigned, Bug

#7756 Changed AbstractFurnaceTileEntity's canBurn and burn functions to use…
  patches/minecraft/net/minecraft/tileentity/AbstractFurnaceTileEntity.java.patch
Labels: 1.16, Assigned, Cleanup

#7761 [1.16.x] Remove redundant mobgriefing check
  patches/minecraft/net/minecraft/entity/projectile/SmallFireballEntity.java.patch
Labels: 1.16, Assigned, Cleanup

#7762 [1.16.x] Use MobGriefingEvent for PiglinEntity
  patches/minecraft/net/minecraft/entity/monster/piglin/PiglinEntity.java.patch
Labels: 1.16, Assigned, Feature

#7771 Add IRecipeType parameter to burn time hooks
  patches/minecraft/net/minecraft/inventory/container/AbstractFurnaceContainer.java.patch
  patches/minecraft/net/minecraft/tileentity/AbstractFurnaceTileEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/furnace/FurnaceFuelBurnTimeEvent.java
Labels: 1.16, Assigned, Feature

#7782 Fixes voiding bug in tryFluidTransfer_Internal
  src/main/java/net/minecraftforge/fluids/FluidUtil.java
Labels: 1.16, Assigned, Cleanup

#7799 Synchronize `ResourcePackList#addPackFinder`
  patches/minecraft/net/minecraft/resources/ResourcePackList.java.patch
Labels: 1.16, Assigned, Cleanup, Confirmed

#7803 Fix vanilla rotation/mirroring issues
  patches/minecraft/net/minecraft/block/BeehiveBlock.java.patch
  patches/minecraft/net/minecraft/block/ChestBlock.java.patch
Labels: 1.16, Assigned, Cleanup, Vanilla Bug

#7804 Fix mod menu URL click bounds
  src/main/java/net/minecraftforge/fml/client/gui/screen/ModListScreen.java
Labels: 1.16, Assigned, Feature

#7806 Add vanilla attack knockback attribute to players
  patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch
  src/test/java/net/minecraftforge/debug/entity/player/PlayerAttackKnockbackTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/player_attack_knockback_test/lang/en_us.json
  src/test/resources/assets/player_attack_knockback_test/models/item/knockback_sword.json
  src/test/resources/assets/player_attack_knockback_test/textures/item/knockback_sword.png
Labels: 1.16, Assigned, Feature

#7811 Minor convenience/compat adjustment for PotionBrewing patch.
  patches/minecraft/net/minecraft/potion/PotionBrewing.java.patch
Labels: 1.16, Assigned, Feature

#7816 Let Trapdoors be climbable for custom ladders
  patches/minecraft/net/minecraft/block/TrapDoorBlock.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
Labels: 1.16, Assigned, Feature

#7817 Make DimensionSettings easier to use
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/world/DimensionSettingsTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/data/dimension_settings_test/dimension/test_overworld.json
Labels: 1.16, Assigned, Cleanup

#7824 [1.16] Allow blocks other than beds or respawn anchors to act as respawn points
  patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
  src/test/java/net/minecraftforge/debug/block/CustomRespawnTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16, Assigned, Feature

#7826 [1.16] Fix entities losing their scoreboard data when they are unloaded
  patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch
Labels: 1.16, Assigned, Bug

#7834 Updates MouseHelper to allow for Horizontal Scroll to be recognized as Vertical Scroll
  patches/minecraft/net/minecraft/client/MouseHelper.java.patch
Labels: 1.16, Cleanup, Feature

#7836 Corrects the assigning of mob kills
  patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch
Labels: 1.16, Assigned, Bug

#7840 Removes misleading Nullable annotation from canCreatureSpawn
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
Labels: 1.16, Assigned, Cleanup

#7841 Removes misapplied patch in Entity.closerThan
  patches/minecraft/net/minecraft/entity/Entity.java.patch
Labels: 1.16, Assigned, Bug

#7842 Fishing bobber projectile impact
  patches/minecraft/net/minecraft/entity/projectile/FishingBobberEntity.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/ProjectileImpactEvent.java
  src/test/java/net/minecraftforge/debug/entity/FishingBobberEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16, Assigned, Bug

#7845 Patch several mob classes to let them use modded versions of their ranged weapons
  patches/minecraft/net/minecraft/entity/ICrossbowUser.java.patch
  patches/minecraft/net/minecraft/entity/ai/brain/task/ShootTargetTask.java.patch
  patches/minecraft/net/minecraft/entity/ai/goal/RangedBowAttackGoal.java.patch
  patches/minecraft/net/minecraft/entity/ai/goal/RangedCrossbowAttackGoal.java.patch
  patches/minecraft/net/minecraft/entity/monster/AbstractSkeletonEntity.java.patch
  patches/minecraft/net/minecraft/entity/monster/IllusionerEntity.java.patch
  patches/minecraft/net/minecraft/entity/monster/PillagerEntity.java.patch
  patches/minecraft/net/minecraft/entity/monster/piglin/PiglinEntity.java.patch
  patches/minecraft/net/minecraft/entity/monster/piglin/PiglinTasks.java.patch
  patches/minecraft/net/minecraft/entity/projectile/ProjectileHelper.java.patch
  src/test/java/net/minecraftforge/debug/item/RangedMobsUseModdedWeaponsTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16, Assigned, Feature

#7849 Adds a damage float to LightningEntity to enable dynamic lightning damage
  patches/minecraft/net/minecraft/entity/Entity.java.patch
  patches/minecraft/net/minecraft/entity/effect/LightningBoltEntity.java.patch
Labels: 1.16, Assigned, Feature

#7871 [1.16 Hotfix] Fix missing userdev config for datagen runs
  build.gradle
Labels: 1.16, Bug, Regression, Triage

#7733 Fix FakePlayers having null `connection` and add FakePlayer test mod
  src/main/java/net/minecraftforge/common/util/FakePlayer.java
  src/test/java/net/minecraftforge/debug/misc/FakePlayerTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16, Assigned, Feature

#7886 1.17 Added back attribute patches
  patches/minecraft/net/minecraft/world/entity/ai/attributes/DefaultAttributes.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/entity/EntityAttributeCreationEvent.java
Labels: 1.17, Bug, Regression

#7895 [1.17.x] Expose RenderStateShard inner classes
  src/main/resources/META-INF/accesstransformer.cfg
Labels: 1.17

#7894 [1.17.x] Pass the 'includeName' flag to the ItemTossEvent
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
Labels: 1.17

#7897 Add modder-friendly way to edit the boat model / texture in custom boats
  patches/minecraft/net/minecraft/client/renderer/entity/BoatRenderer.java.patch
Labels: 1.17, Assigned, Feature, Rendering

#7931 [1.17.x] Fix typo in FluidBlockWrapper
  src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBlockWrapper.java
Labels: 1.17, Assigned, Bug

#7919 Fix userdev mod deps on the classpath
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ClasspathLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModDiscoverer.java
  fmlloader/src/main/resources/META-INF/services/net.minecraftforge.forgespi.locating.IModLocator
Labels: 1.17, Assigned, Bug, Regression
