Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-01, with the labels that each got.

#7534 Set WM_CLASS and WM_INSTANCE_NAME for early progress window
  src/fmllauncher/java/net/minecraftforge/fml/loading/FMLLoader.java
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/ClientVisualization.java
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/EarlyProgressVisualization.java
Labels: 1.16, Assigned, Bug

#7509 Fix crash when mods add goals to skeleton horses (MC-206338)
  patches/minecraft/net/minecraft/entity/ai/goal/TriggerSkeletonTrapGoal.java.patch
Labels: 1.16, Assigned, Vanilla Bug

#7525 Allow Chunk loading Tickets to opt-into forcing chunk ticks.
  patches/minecraft/net/minecraft/world/server/ServerChunkProvider.java.patch
  patches/minecraft/net/minecraft/world/server/Ticket.java.patch
  patches/minecraft/net/minecraft/world/server/TicketManager.java.patch
Labels: 1.16, Assigned, Feature

#7522 Added ability to do custom rain particle rendering
  patches/minecraft/net/minecraft/client/renderer/WorldRenderer.java.patch
  patches/minecraft/net/minecraft/client/world/DimensionRenderInfo.java.patch
  src/main/java/net/minecraftforge/client/IWeatherParticleRenderHandler.java
Labels: 1.16.2, Assigned, Feature

#7294 [1.16] Optionally add milk as a fluid to the vanilla bucket
  src/generated/resources/data/forge/tags/fluids/milk.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeFluidTagsProvider.java
  src/main/java/net/minecraftforge/fluids/FluidUtil.java
  src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBucketWrapper.java
  src/main/resources/assets/forge/lang/en_us.json
  src/main/resources/assets/forge/textures/block/milk_flowing.png
  src/main/resources/assets/forge/textures/block/milk_flowing.png.mcmeta
  src/main/resources/assets/forge/textures/block/milk_still.png
  src/main/resources/assets/forge/textures/block/milk_still.png.mcmeta
  src/test/java/net/minecraftforge/debug/fluid/MilkFluidTest.java
  src/test/resources/META-INF/mods.toml
Labels: 1.16.2, Assigned, Feature, Fluids

#7360 Add modded biomes to overworld biome list
  patches/minecraft/net/minecraft/world/biome/provider/OverworldBiomeProvider.java.patch
  src/main/java/net/minecraftforge/common/BiomeManager.java
Labels: 1.16, Assigned, Feature

#7599 Fix worlds that are missing vanilla dimensions in the level.dat
  patches/minecraft/net/minecraft/world/storage/SaveFormat.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: 1.16, Assigned, Confirmed, Feature

#7576 Fix existing file tag provider support looking in the wrong folder for custom tag types
  patches/minecraft/net/minecraft/data/TagsProvider.java.patch
  src/main/java/net/minecraftforge/common/data/ForgeRegistryTagsProvider.java
  src/main/resources/forge.exc
Labels: 1.16, Regression

#7579 Fix Translucent parts of MultiLayer-Models rendering as missing model during piston movement
  src/main/java/net/minecraftforge/client/model/MultiLayerModel.java
Labels: 1.16, Bug, Regression, Rendering

#7548 Add hook to allow modders to more easily control if endermen can place blocks on top of their blocks
  patches/minecraft/net/minecraft/entity/monster/EndermanEntity.java.patch
  src/generated/resources/data/forge/tags/blocks/enderman_place_on_blacklist.json
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeBlockTagsProvider.java
Labels: 1.16, Assigned, Feature
