Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-11, with the labels that each got.

#6927 Implement GUI Stacking feature.
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/gui/screen/Screen.java.patch
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/extensions/IForgeMinecraft.java
  src/test/java/net/minecraftforge/debug/client/GuiLayeringTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Rendering, Assigned, 1.16, LTS Backport

#8177 [1.17.x] Fix part entities not working at all
  patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch
  patches/minecraft/net/minecraft/world/level/Level.java.patch
  src/test/java/net/minecraftforge/debug/entity/PartEntityTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Regression, Assigned, 1.17

#8162 Fix the hopefully last issue with GAMELIBRARY loading
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java
Labels: Bug, Assigned, 1.17

#8072 Remove the remnants of the selective reload listener
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/gui/screens/LanguageSelectScreen.java.patch
  patches/minecraft/net/minecraft/client/gui/screens/recipebook/RecipeBookComponent.java.patch
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/LevelRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/BlockRenderDispatcher.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/ItemRenderer.java.patch
  patches/minecraft/net/minecraft/client/resources/language/LanguageManager.java.patch
  patches/minecraft/net/minecraft/client/searchtree/SearchRegistry.java.patch
  patches/minecraft/net/minecraft/server/packs/resources/ResourceManagerReloadListener.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/model/DynamicBucketModel.java
  src/main/java/net/minecraftforge/client/model/IModelLoader.java
  src/main/java/net/minecraftforge/client/model/b3d/B3DLoader.java
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/resource/IResourceType.java
  src/main/java/net/minecraftforge/resource/ReloadRequirements.java
  src/main/java/net/minecraftforge/resource/VanillaResourceType.java
Labels: Cleanup, Assigned, 1.17

#8184 [1.17.x] Remove Old LootPool Patches
  patches/minecraft/net/minecraft/world/level/storage/loot/LootPool.java.patch
Labels: Bug, Assigned, Triage, 1.17

#8129 [1.16.x] Make Broken Blocks Display Associated FluidState
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Bug, Assigned, 1.16, LTS Backport

#8138 [1.16.x] Ensure that all render targets in a PostChain use the same format
  patches/minecraft/net/minecraft/client/shader/ShaderGroup.java.patch
Labels: Bug, Rendering, Assigned, 1.16, LTS Backport

#8109 [1.16] Add accessor to an unmodifiable view of the fullPots map in FlowerPotBlock
  patches/minecraft/net/minecraft/block/FlowerPotBlock.java.patch
  src/test/java/net/minecraftforge/debug/block/FullPotsAccessorDemo.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/full_pots_accessor_demo/blockstates/diorite_pot.json
  src/test/resources/assets/full_pots_accessor_demo/models/block/diorite_pot.json
Labels: Feature, Assigned, 1.16, LTS Backport

#8161 [1.16.x] Fix blocks with flammable material catching fire from lava when they are marked as non-flammable
  patches/minecraft/net/minecraft/fluid/LavaFluid.java.patch
Labels: Bug, Assigned, 1.16, LTS Backport

#8107 [1.16] Pass IModelData through IForgeBakedModel#getModelData() before using it to get the particle texture
  patches/minecraft/net/minecraft/client/renderer/BlockModelShapes.java.patch
Labels: Feature, Rendering, Assigned, 1.16, LTS Backport

#7879 Implements Lazy ItemStack Capabilities
  patches/minecraft/net/minecraft/item/ItemStack.java.patch
  src/main/java/net/minecraftforge/common/capabilities/CapabilityProvider.java
  src/test/java/net/minecraftforge/common/capabilities/LazyCapabilitiesOnItemsTest.java
  src/test/resources/META-INF/mods.toml
Labels: Performance, Feature, Capabilities, Assigned, 1.16, LTS Backport

#7488 change the AdvancementProvider to make it possabible for mods to hook into it
  patches/minecraft/net/minecraft/advancements/Advancement.java.patch
  patches/minecraft/net/minecraft/data/AdvancementProvider.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeAdvancementBuilder.java
  src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
  src/test/resources/data/forge/advancements/dummy_parent.json
Labels: Feature, Assigned, 1.16, LTS Backport

#8179 [1.17.x] make ScrollPanel better usable by modders
  src/main/java/net/minecraftforge/client/gui/ScrollPanel.java
  src/test/java/net/minecraftforge/debug/block/FullPotsAccessorDemo.java
Labels: Feature, Assigned, Triage, 1.17

#8207 Apply window resizing to all gui layers
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: Bug, Rendering, 1.17

#8194 [1.17.x] Change expected type of LootTable fields to arrays
  src/main/java/net/minecraftforge/common/data/ForgeLootTableProvider.java
Labels: Bug, Regression, Assigned, 1.17

#8150 [1.16.x] Add ForgeSpawnEggItem to lazily handle EntityTypes
  patches/minecraft/net/minecraft/dispenser/IDispenseItemBehavior.java.patch
  patches/minecraft/net/minecraft/item/SpawnEggItem.java.patch
  src/main/java/net/minecraftforge/common/ForgeSpawnEggItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
  src/main/resources/forge.sas
  src/test/java/net/minecraftforge/debug/item/ForgeSpawnEggItemTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/forge_spawnegg_test/models/item/test_spawn_egg.json
Labels: Feature, Assigned, 1.16, LTS Backport

#8209 Backport #8207 (Apply window resizing to all gui layers)
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: Bug, Rendering, Assigned, 1.16, LTS Backport

#8140 Deprecate net.minecraftforge.common.util.Constants and inner classes to encourage usage of vanilla constants
  patches/minecraft/net/minecraft/world/effect/MobEffectInstance.java.patch
  src/main/java/net/minecraftforge/common/util/BlockSnapshot.java
  src/main/java/net/minecraftforge/common/util/Constants.java
  src/main/java/net/minecraftforge/common/world/ForgeChunkManager.java
  src/main/java/net/minecraftforge/fluids/FluidStack.java
  src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockWrapper.java
  src/main/java/net/minecraftforge/items/ItemStackHandler.java
Labels: Cleanup, Assigned, 1.17

#8176 Prospective BackgroundScanHandler Fix
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/BackgroundScanHandler.java
Labels: Bug, Assigned, 1.17

#8196 Fix death message for tamed animals
  patches/minecraft/net/minecraft/world/entity/TamableAnimal.java.patch
Labels: Bug, Assigned, 1.17

#8211 Fix potential issue with BackgroundScanHandler for users with slow disc IO
  src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/BackgroundScanHandler.java
Labels: Bug, Assigned, 1.16, LTS Backport

#8103 Fix onChunkUnloaded not gettting called correctly
  patches/minecraft/net/minecraft/world/level/Level.java.patch
  patches/minecraft/net/minecraft/world/level/chunk/LevelChunk.java.patch
Labels: Bug, Confirmed, Cleanup, Assigned, 1.17

#8114 [1.17.x] EntityMountEvent Infinite Client Loop Fix
  patches/minecraft/net/minecraft/client/player/LocalPlayer.java.patch
Labels: Bug, Triage, 1.17

#8158 Fix render pipeline lighting issue with small cubes
  patches/minecraft/com/mojang/math/Vector3f.java.patch
Labels: Bug, Rendering, Assigned, 1.17

#8213 Reorder image tooltip component to match vanilla
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: Bug, Rendering, Assigned, 1.17

#8214 Deprecate for removal the durability bar methods in Item extension
  patches/minecraft/net/minecraft/client/renderer/entity/ItemRenderer.java.patch
  patches/minecraft/net/minecraft/world/item/Item.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
Labels: Cleanup, Rendering, Assigned, 1.17

#8133 Changed control flow of post mouse events
  patches/minecraft/net/minecraft/client/MouseHandler.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/GuiScreenEvent.java
Labels: Assigned, 1.17

#8148 [1.17.x] Use HttpClient for VersionChecker
  fmlcore/src/main/java/net/minecraftforge/fml/VersionChecker.java
Labels: Feature, Assigned, 1.17

#8206 [1.17] Fix Spectating Part Entity (MC-46486)
  patches/minecraft/net/minecraft/server/level/ServerPlayer.java.patch
Labels: Bug, Vanilla Bug, Assigned, 1.17

#8215 [1.17] Forward Port MinecraftForge#7971 to 1.17 & update deprecation info
  src/main/java/net/minecraftforge/server/command/CommandSetDimension.java
Labels: Bug, Assigned, 1.17
