Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-09, with the labels that each got.

#8058 Add shebang to run.sh in server files
  server_files/run.sh
Labels: Assigned, 1.17

#7960 Changed Monster Requirement to Mob in RangedBowAttackGoal
  patches/minecraft/net/minecraft/world/entity/ai/goal/RangedBowAttackGoal.java.patch
Labels: Feature, Assigned, 1.17

#8023 [1.17.x]: Added SendPlayerPermissionLevelEvent
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/player/PermissionsChangedEvent.java
  src/test/java/net/minecraftforge/debug/entity/player/PermissionsChangedEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, New Event, Assigned, 1.17

#8041 Re-add missing patch for IForgeItem#getEquipmentSlot
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
Labels: Bug, Assigned, 1.17

#8050 Add workaround for pairs of `'` being stripped
  src/main/java/net/minecraftforge/fmllegacy/TextComponentMessageFormatHandler.java
Labels: Bug, Assigned, 1.17

#8055 Add new tool action for shield blocking, replacing `IForgeItem#isShield`
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/piglin/StopHoldingItemIfNoLongerAdmiring.java.patch
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  patches/minecraft/net/minecraft/world/item/ShieldItem.java.patch
  src/main/java/net/minecraftforge/common/ToolActions.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
  src/test/java/net/minecraftforge/debug/item/CustomShieldTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Regression, Assigned, 1.17

#8068 Remove old Log4j thread cache invalidation
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: Cleanup, Assigned, 1.17

#8060 Propagate all arguments passed to the server start scripts to the game
  server_files/run.bat
  server_files/run.sh
Labels: Feature, Assigned, 1.17

#8042 Re-add patch to release buffer in custom payload packet
  patches/minecraft/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
  patches/minecraft/net/minecraft/network/protocol/game/ClientboundCustomPayloadPacket.java.patch
Labels: Bug, Assigned, 1.17

#8033 Fix EntityJoinWorldEvent not firing as expected:
  patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch
  patches/minecraft/net/minecraft/world/level/entity/PersistentEntitySectionManager.java.patch
  src/main/java/net/minecraftforge/event/entity/EntityJoinWorldEvent.java
  src/main/resources/forge.exc
Labels: Bug, Regression, Assigned, 1.17

#7945 [1.17] Lazy capabilities on itemstacks.
  src/main/java/net/minecraftforge/common/capabilities/CapabilityProvider.java
  src/test/java/net/minecraftforge/debug/world/item/LazyCapabilitiesOnItemsTest.java
  src/test/resources/META-INF/mods.toml
Labels: Performance, Feature, Assigned, 1.17

#8085 [HotFix][1.17.x] Enable the Lazy Capabilities technology on ItemStacks
  patches/minecraft/net/minecraft/world/item/ItemStack.java.patch
Labels: Bug, Performance, Assigned, Triage, 1.17

#8089 Fix inverted hooks for PermissionsChangedEvent
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: Bug, Assigned, 1.17

#8096 Move ItemStack#forgeInit call earlier to allow earlier capability queries
  patches/minecraft/net/minecraft/world/item/ItemStack.java.patch
  src/main/java/net/minecraftforge/common/capabilities/CapabilityProvider.java
Labels: Bug, Assigned, 1.17

#8098 [1.16.5] Bump Mixin to 0.8.4
  build.gradle
  src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
  src/test/java/net/minecraftforge/debug/misc/OnDatapackSynctEventTest.java
Labels: Assigned, 1.16, LTS Backport

#8097 Prevent call to Item#initializeClient when in datagen
  patches/minecraft/net/minecraft/world/effect/MobEffect.java.patch
  patches/minecraft/net/minecraft/world/item/Item.java.patch
  patches/minecraft/net/minecraft/world/level/block/Block.java.patch
Labels: Bug, Work In Progress, 1.17

#8014 [1.17.x] implements canConnectRedstone(), Redstone dust now defers to the blockstate for determining connectivity
  patches/minecraft/net/minecraft/world/level/block/RedStoneWireBlock.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
  src/test/java/net/minecraftforge/debug/block/RedstoneSidedConnectivityTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/redstone_sided_connectivity_test/blockstates/test_east_redstone_connect.json
  src/test/resources/assets/redstone_sided_connectivity_test/lang/en_us.json
  src/test/resources/assets/redstone_sided_connectivity_test/models/block/test_east_redstone_connect.json
  src/test/resources/assets/redstone_sided_connectivity_test/models/item/test_east_redstone_connect.json
Labels: Feature, Assigned, 1.17

#8110 Allows pet death message to be cancelled along with death
  patches/minecraft/net/minecraft/world/entity/TamableAnimal.java.patch
Labels: Bug, Assigned, 1.17

#7923 [1.16.5] Backport MC-209819
  patches/minecraft/net/minecraft/entity/LivingEntity.java.patch
Labels: Vanilla Bug, Assigned, 1.16
