Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-12, with the labels that each got.

#8248 [1.18.x] Fix some test worldgen data breaking datapack imports in forgedev test
  src/test/resources/data/biome_loading_event_test/worldgen/biome/desert.json
  src/test/resources/data/dimension_settings_test/dimension/test_overworld.json
Labels: Bug, Cleanup, Triage, 1.18

#8237 Restore missing patch to LevelChunk
  patches/minecraft/net/minecraft/world/level/chunk/LevelChunk.java.patch
Labels: Bug, Regression, Assigned, 1.18

#8256 (1.18) Fixed KeyMappings only checking if they conflict with themselves.
  patches/minecraft/net/minecraft/client/gui/screens/controls/KeyBindsList.java.patch
Labels: Bug, Triage, 1.18

#8268 [HotFix] [CVE-2021-44228]: Update Log4J to fix the security issue inside it.
  build.gradle
  fmlloader/src/main/resources/log4j2.xml
  src/fmllauncher/resources/log4j2.xml
Labels: Bug, Regression, Vanilla Bug, Triage, 1.18

#8270 [1.16.x] [HotFix] [CVE-2021-44228]: Update Log4J to fix the security issue inside it
  build.gradle
  src/fmllauncher/resources/log4j2.xml
Labels: Bug, Regression, Vanilla Bug, 1.16

#8271 [1.15.x] [HotFix] [CVE-2021-44228]: Update Log4J to fix the security issue inside it
  build.gradle
  src/fmllauncher/resources/log4j2.xml
Labels: Bug, Regression, Vanilla Bug, 1.15

#8272 [1.14.x] [CVE-2021-44228]: Update Log4J to fix the security issue inside it.
  Jenkinsfile
  build.gradle
  src/fmllauncher/resources/log4j2.xml
Labels: Bug, Regression, Vanilla Bug, 1.14

#8273 [CVE-2021-44228]: Update Log4J to fix the security issue inside it.
  Jenkinsfile
  build.gradle
  src/fmllauncher/resources/log4j2.xml
Labels: Bug, Regression, Vanilla Bug, 1.13

#8277 Patch the jenkinsfile so it publishes using the correct credentials provided by Jenkins.
  build.gradle
Labels: Cleanup, 1.14

#8279 Fix an issue with the version number generation as well as the logging pattern output.
  Jenkinsfile
  build.gradle
  src/main/resources/log4j2.xml
  src/main/resources/log4j2_server.xml
Labels: Bug, Cleanup, 1.12

#8286 Update Installer to 2.1.+ and fix logging on server
  build.gradle
  mdk/build.gradle
  src/main/resources/log4j2_server.xml
Labels: Bug, Cleanup, 1.12

#8288 [1.13.x] Update Installer to 2.1.+
  build.gradle
  mdk/build.gradle
  src/main/resources/META-INF/mods.toml
Labels: Cleanup, 1.13

#8289 [1.14.x] Update Installer to 2.1.+
  build.gradle
  docs/README.md
  mdk/build.gradle
  src/main/resources/META-INF/mods.toml
Labels: Cleanup, 1.14

#8290 [1.15.x] Update Installer to 2.1.+
  build.gradle
  docs/README.md
  mdk/build.gradle
  src/main/resources/META-INF/mods.toml
Labels: Cleanup, 1.15

#8293 [1.12.x] Remove log4j-slf4j18-impl
  build.gradle
Labels: Cleanup, 1.12

#8267 Fix wrong stage being declared in ModStateProvider
  src/fmlcommon/java/net/minecraftforge/fml/core/ModStateProvider.java
Labels: Bug, Regression, Assigned, 1.18

#8249 Fix datagen test for sounds definitions provider
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/assets/data_gen_test/sounds.json
  src/generated_test/resources/data/data_gen_test/advancements/obtain_dirt.json
  src/generated_test/resources/data/minecraft/advancements/good_parent.json
  src/generated_test/resources/data/minecraft/advancements/obtain_diamond_block.json
  src/generated_test/resources/data/minecraft/advancements/story/root.json
  src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
Labels: Bug, Cleanup, Assigned, 1.18

#8218 [1.18] Log missing mandatory dependencies
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java
Labels: Feature, Assigned, 1.18

#8231 Adds tag support for MobEffects
  patches/minecraft/net/minecraft/world/effect/MobEffect.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/custom_tag_types_test/tags/mob_effects/beacon.json
  src/main/java/net/minecraftforge/registries/GameData.java
  src/test/java/net/minecraftforge/debug/misc/CustomTagTypesTest.java
Labels: Feature, Assigned, 1.18

#8254 Add a RenderArmEvent
  patches/minecraft/net/minecraft/client/renderer/entity/player/PlayerRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/RenderArmEvent.java
Labels: New Event, Assigned, 1.18

#8299 Add a RenderArmEvent (LTS Backport of #8254)
  patches/minecraft/net/minecraft/client/renderer/entity/PlayerRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/RenderArmEvent.java
Labels: New Event, Rendering, Assigned, 1.16, LTS Backport

#8257 (1.16) Fixed KeyMappings only checking if they conflict with themselves.
  patches/minecraft/net/minecraft/client/gui/widget/list/KeyBindingList.java.patch
Labels: Bug, Regression, Assigned, 1.16, LTS Backport

#7780 1.18: Revamp & Extension of the PermissionAPI
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/server/ServerLifecycleHooks.java
  src/main/java/net/minecraftforge/server/permission/DefaultPermissionHandler.java
  src/main/java/net/minecraftforge/server/permission/IPermissionHandler.java
  src/main/java/net/minecraftforge/server/permission/PermissionAPI.java
  src/main/java/net/minecraftforge/server/permission/context/AreaContext.java
  src/main/java/net/minecraftforge/server/permission/context/BlockPosContext.java
  src/main/java/net/minecraftforge/server/permission/context/Context.java
  src/main/java/net/minecraftforge/server/permission/context/ContextKey.java
  src/main/java/net/minecraftforge/server/permission/context/ContextKeys.java
  src/main/java/net/minecraftforge/server/permission/context/IContext.java
  src/main/java/net/minecraftforge/server/permission/context/TargetContext.java
  src/main/java/net/minecraftforge/server/permission/context/WorldContext.java
  src/main/java/net/minecraftforge/server/permission/context/package-info.java
  src/main/java/net/minecraftforge/server/permission/events/PermissionGatherEvent.java
  src/main/java/net/minecraftforge/server/permission/exceptions/UnregisteredPermissionException.java
  src/main/java/net/minecraftforge/server/permission/handler/DefaultPermissionHandler.java
  src/main/java/net/minecraftforge/server/permission/handler/IPermissionHandler.java
  src/main/java/net/minecraftforge/server/permission/handler/IPermissionHandlerFactory.java
  src/main/java/net/minecraftforge/server/permission/nodes/PermissionDynamicContext.java
  src/main/java/net/minecraftforge/server/permission/nodes/PermissionDynamicContextKey.java
  src/main/java/net/minecraftforge/server/permission/nodes/PermissionNode.java
  src/main/java/net/minecraftforge/server/permission/nodes/PermissionType.java
  src/main/java/net/minecraftforge/server/permission/nodes/PermissionTypes.java
  src/main/java/net/minecraftforge/server/permission/package-info.java
  src/test/java/net/minecraftforge/debug/PermissionTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Cleanup, New Event, Assigned, 1.18

#8317 Fixed incorrect generic in PermissionAPI
  src/main/java/net/minecraftforge/server/permission/PermissionAPI.java
  src/test/java/net/minecraftforge/debug/PermissionTest.java
Labels: Bug, 1.18
