Repository MinecraftForge/MinecraftForge, pull requests merged in 2021-04, with the labels that each got.

#7719 Fix ClientVisualization crashing on systems without monitors
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/ClientVisualization.java
Labels: 1.16, Bug, Triage

#7710 Check version ranges of optional dependencies when present
  src/fmllauncher/java/net/minecraftforge/fml/loading/ModSorter.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.16, Assigned, Bug, Cleanup

#7705 [1.16.5] Pass BlockPos to BlockParticleData used for "fall impact" particle
  patches/minecraft/net/minecraft/entity/LivingEntity.java.patch
Labels: 1.16, Assigned, Feature

#7677 [1.16] Add missing Multipart Blockstate Builder feature: Nested condition groups
  src/main/java/net/minecraftforge/client/model/generators/MultiPartBlockStateBuilder.java
Labels: 1.16, Assigned

#7739 Fix #7738
  src/main/java/net/minecraftforge/fml/client/ClientHooks.java
Labels: 1.16, Assigned, Bug

#7718 Fix shears not properly breaking tripwire (MC-129055)
  patches/minecraft/net/minecraft/block/TripWireHookBlock.java.patch
Labels: 1.16, Assigned, Confirmed, Vanilla Bug
