Repository MinecraftForge/MinecraftForge, pull requests merged in 2022-06, with the labels that each got.

#8635 Add ItemStack context to Enchantment#getDamageBonus
  patches/minecraft/net/minecraft/world/item/enchantment/Enchantment.java.patch
  patches/minecraft/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeEnchantment.java
Labels: Feature, Assigned, 1.18

#8654 [1.18.x] Fix wrong position in LevelAccessor#hasChunk() call in IForgeBlockGetter
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockGetter.java
Labels: Bug, Assigned, 1.18

#8650 [1.18] Fix reload listener registration in ModelLoaderRegistry
  patches/minecraft/net/minecraft/server/packs/resources/ReloadableResourceManager.java.patch
  src/main/java/net/minecraftforge/client/event/ModelRegistryEvent.java
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
  src/main/java/net/minecraftforge/client/model/ModelLoaderRegistry.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
Labels: Bug, Rendering, Triage, 1.18

#8648 [1.18] Allow custom rarities to directly modify the style
  patches/minecraft/net/minecraft/client/gui/Gui.java.patch
  patches/minecraft/net/minecraft/world/item/ItemStack.java.patch
  patches/minecraft/net/minecraft/world/item/Rarity.java.patch
  src/test/java/net/minecraftforge/debug/misc/CustomRarityTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Triage, 1.18

#8630 1.18.x Custom datapack registries, round three-ish
  build.gradle
  patches/minecraft/net/minecraft/core/RegistryAccess.java.patch
  patches/minecraft/net/minecraft/resources/RegistryResourceAccess.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/data_pack_registries_test/data_pack_registries_test/unsyncable/datagen_test.json
  src/main/java/net/minecraftforge/network/HandshakeHandler.java
  src/main/java/net/minecraftforge/network/HandshakeMessages.java
  src/main/java/net/minecraftforge/network/NetworkConstants.java
  src/main/java/net/minecraftforge/network/NetworkRegistry.java
  src/main/java/net/minecraftforge/registries/DataPackRegistriesHooks.java
  src/main/java/net/minecraftforge/registries/NewRegistryEvent.java
  src/main/java/net/minecraftforge/registries/RegistryBuilder.java
  src/main/java/net/minecraftforge/registries/RegistryManager.java
  src/main/java/net/minecraftforge/server/ServerLifecycleHooks.java
  src/main/resources/assets/forge/lang/en_us.json
  src/test/java/net/minecraftforge/debug/misc/DataPackRegistriesTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/data/data_pack_registries_test/data_pack_registries_test/syncable/test.json
  src/test/resources/data/data_pack_registries_test/data_pack_registries_test/unsyncable/test.json
  src/test/resources/data/data_pack_registries_test/tags/data_pack_registries_test/syncable/test.json
  src/test/resources/data/data_pack_registries_test/tags/data_pack_registries_test/unsyncable/test.json
Labels: Feature, Assigned, 1.18

#8629 [1.18.x] Enable "Experimental Forge Light Pipeline" by default
  src/main/java/net/minecraftforge/client/model/pipeline/ForgeBlockModelRenderer.java
  src/main/java/net/minecraftforge/common/ForgeConfig.java
Labels: Feature, Rendering, Assigned, 1.18

#8605 [1.16] Multipart entity id desync fix
  patches/minecraft/net/minecraft/client/network/play/ClientPlayNetHandler.java.patch
  patches/minecraft/net/minecraft/entity/Entity.java.patch
  patches/minecraft/net/minecraft/entity/boss/dragon/EnderDragonEntity.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Vanilla Bug, Assigned, 1.16, LTS Backport

#8606 [1.16] Fix entity parts being ignored when collecting entities in an AABB
  patches/minecraft/net/minecraft/client/world/ClientWorld.java.patch
  patches/minecraft/net/minecraft/world/World.java.patch
  patches/minecraft/net/minecraft/world/chunk/Chunk.java.patch
  patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeWorld.java
Labels: Bug, Assigned, 1.16, LTS Backport

#8564 1.18.x Port BiomeDictionary over to biome tags
  src/generated/resources/data/forge/tags/worldgen/biome/is_beach.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_cold.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_cold/end.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_cold/overworld.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_coniferous.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_dense.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_dense/overworld.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_dry.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_dry/end.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_dry/nether.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_dry/overworld.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_end.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_hot.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_hot/nether.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_hot/overworld.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_lush.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_mushroom.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_overworld.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_peak.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_plains.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_plateau.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_rare.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_sandy.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_savanna.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_slope.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_snowy.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_sparse.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_sparse/overworld.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_spooky.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_swamp.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_underground.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_void.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_wasteland.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_water.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_wet.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_wet/overworld.json
  src/generated/resources/data/minecraft/tags/worldgen/biome/is_mountain.json
  src/main/java/net/minecraftforge/common/BiomeDictionary.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeBiomeTagsProvider.java
Labels: Feature, 1.18

#8530 [1.18.x] Fix Banner Pattern Extension
  patches/minecraft/net/minecraft/client/gui/screens/inventory/LoomScreen.java.patch
  patches/minecraft/net/minecraft/world/inventory/LoomMenu.java.patch
  patches/minecraft/net/minecraft/world/item/BannerItem.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/BannerPattern.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/block/BannerPatternTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Triage, 1.18

#8644 [1.18.x] Add checkJarCompatibility task
  build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/DownloadBaseCompatibilityBinPatches.groovy
Labels: Feature, Triage, 1.18

#8633 Low code language provider
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonClientLaunchHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonDevLaunchHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonServerLaunchHandler.java
  lowcodelanguage/build.gradle
  lowcodelanguage/src/main/java/net/minecraftforge/fml/lowcodemod/LowCodeModContainer.java
  lowcodelanguage/src/main/java/net/minecraftforge/fml/lowcodemod/LowCodeModLanguageProvider.java
  lowcodelanguage/src/main/resources/META-INF/services/net.minecraftforge.forgespi.language.IModLanguageProvider
  settings.gradle
Labels: Feature, Triage, 1.18

#8638 Fix tags command suggestions to include dynamic registries
  src/main/java/net/minecraftforge/server/command/TagsCommand.java
Labels: Bug, Triage, 1.18

#8616 Fix command redirects by replacing Commands#fillUsableCommands
  patches/minecraft/net/minecraft/commands/Commands.java.patch
  src/main/java/net/minecraftforge/client/ClientCommandHandler.java
  src/main/java/net/minecraftforge/server/command/CommandHelper.java
Labels: Vanilla Bug, Triage, 1.18

#8595 Allow sound instances to customize stream source
  patches/minecraft/net/minecraft/client/audio/ISound.java.patch
  patches/minecraft/net/minecraft/client/audio/SoundEngine.java.patch
  src/test/java/net/minecraftforge/debug/client/AudioStreamTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/audio_stream_test/sounds.json
  src/test/resources/assets/audio_stream_test/sounds/empty.ogg
Labels: Feature, Assigned, 1.16, LTS Backport

#8476 Avoid exclusive synchronisation in block render type lookups
  patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch
Labels: Performance, Rendering, Triage, 1.18

#8402 [1.18.x] Added new Disconnection screen to display better channel/registry mismatch information
  patches/minecraft/net/minecraft/client/multiplayer/ClientHandshakePacketListenerImpl.java.patch
  src/main/java/net/minecraftforge/client/gui/ModMismatchDisconnectedScreen.java
  src/main/java/net/minecraftforge/network/ConnectionData.java
  src/main/java/net/minecraftforge/network/HandshakeHandler.java
  src/main/java/net/minecraftforge/network/HandshakeMessages.java
  src/main/java/net/minecraftforge/network/NetworkConstants.java
  src/main/java/net/minecraftforge/network/NetworkEvent.java
  src/main/java/net/minecraftforge/network/NetworkHooks.java
  src/main/java/net/minecraftforge/network/NetworkInitialization.java
  src/main/java/net/minecraftforge/network/NetworkRegistry.java
  src/main/java/net/minecraftforge/network/simple/IndexedMessageCodec.java
  src/main/java/net/minecraftforge/network/simple/SimpleChannel.java
  src/main/resources/assets/forge/lang/en_us.json
  src/test/java/net/minecraftforge/debug/misc/ModMismatchTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Triage, 1.18

#8625 [1.18.x] Fix 2 crossbow animations not applying to custom variants
  patches/minecraft/net/minecraft/client/renderer/ItemInHandRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/player/PlayerRenderer.java.patch
Labels: Bug, Confirmed, Work In Progress, 1.18

#8659 Fix eager loading of model loaders during datagen causing NPE
  src/main/java/net/minecraftforge/client/model/ModelLoaderRegistry.java
Labels: Bug, Regression, Triage, 1.18

#8666 [1.18.x] Fix #8530 (Banner Pattern) NPE
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Bug, Assigned, 1.18

#8682 Add method with pre/post wrap to allow setting/clearing mod context. …
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/RegistryManager.java
Labels: Bug, Confirmed, 1.19

#8677 Fire registry events in the order vanilla registers to registries
  patches/minecraft/net/minecraft/core/MappedRegistry.java.patch
  src/main/java/net/minecraftforge/registries/ForgeRegistries.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/NamespacedDefaultedWrapper.java
  src/main/java/net/minecraftforge/registries/NamespacedWrapper.java
Labels: Cleanup, Triage, 1.19

#8678 Fix getting entity data serializer id crashing due to improper port to new registry system
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Regression, Triage, 1.19

#8675 [1.19.x] Update MDK for 1.19 changes
  mdk/README.txt
  mdk/build.gradle
  mdk/src/main/java/com/example/examplemod/ExampleMod.java
Labels: Cleanup, Assigned, 1.19

#8679 Override initialize
  src/main/java/net/minecraftforge/items/SlotItemHandler.java
Labels: Bug, Assigned, 1.19

#8702 Fixes setPos to syncPacketPositionCodec
  src/main/java/net/minecraftforge/network/PlayMessages.java
Labels: Regression, Assigned, 1.19

#8704 [1.19.x] Fix readAdditionalLevelSaveData
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/WorldOpenFlows.java.patch
Labels: Regression, Assigned, 1.19

#8705 Move patch invalidateCaps in Entity
  patches/minecraft/net/minecraft/world/entity/Entity.java.patch
Labels: Regression, Assigned, 1.19

#8692 Now for 1.19: Make IVertexConsumers such as the lighting pipeline, be aware of which format they are dealing with.
  patches/minecraft/com/mojang/blaze3d/vertex/BufferBuilder.java.patch
  patches/minecraft/com/mojang/blaze3d/vertex/SheetedDecalTextureGenerator.java.patch
  patches/minecraft/com/mojang/blaze3d/vertex/VertexMultiConsumer.java.patch
  patches/minecraft/net/minecraft/client/renderer/OutlineBufferSource.java.patch
  patches/minecraft/net/minecraft/client/renderer/SpriteCoordinateExpander.java.patch
  src/main/java/net/minecraftforge/client/extensions/IForgeVertexConsumer.java
  src/main/java/net/minecraftforge/client/gui/ModMismatchDisconnectedScreen.java
  src/main/java/net/minecraftforge/client/model/pipeline/ForgeBlockModelRenderer.java
  src/main/java/net/minecraftforge/client/model/pipeline/VertexBufferConsumer.java
  src/main/java/net/minecraftforge/common/data/ForgeBiomeTagsProvider.java
  src/main/java/net/minecraftforge/server/command/CommandHelper.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/misc/ModMismatchTest.java
Labels: Feature, Rendering, Triage, 1.19

#8665 Make IVertexConsumers such as the lighting pipeline, be aware of which format they are dealing with
  patches/minecraft/com/mojang/blaze3d/vertex/BufferBuilder.java.patch
  patches/minecraft/com/mojang/blaze3d/vertex/SheetedDecalTextureGenerator.java.patch
  patches/minecraft/com/mojang/blaze3d/vertex/VertexMultiConsumer.java.patch
  patches/minecraft/net/minecraft/client/renderer/OutlineBufferSource.java.patch
  patches/minecraft/net/minecraft/client/renderer/SpriteCoordinateExpander.java.patch
  src/main/java/net/minecraftforge/client/extensions/IForgeVertexConsumer.java
  src/main/java/net/minecraftforge/client/gui/ModMismatchDisconnectedScreen.java
  src/main/java/net/minecraftforge/client/model/pipeline/ForgeBlockModelRenderer.java
  src/main/java/net/minecraftforge/client/model/pipeline/VertexBufferConsumer.java
  src/main/java/net/minecraftforge/common/data/ForgeBiomeTagsProvider.java
  src/main/java/net/minecraftforge/server/command/CommandHelper.java
  src/test/java/net/minecraftforge/debug/block/BannerPatternTest.java
  src/test/java/net/minecraftforge/debug/misc/ModMismatchTest.java
Labels: Feature, Rendering, Assigned, 1.18

#8696 Update forgeSPI to v5
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/LanguageLoadingProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModDiscoverer.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModValidator.java
  src/main/java/net/minecraftforge/server/command/ModListCommand.java
Labels: Feature, Triage, 1.19

#8656 displayTest option in mods.toml
  fmlcore/src/main/java/net/minecraftforge/fml/IExtensionPoint.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
  mdk/src/main/resources/META-INF/mods.toml
  src/main/java/net/minecraftforge/network/NetworkConstants.java
Labels: Feature, Triage, 1.19

#8670 Implement a simple feature system for Forge
  build.gradle
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Feature, Triage, 1.19

#8709 Only rewrite datagen cache when needed
  patches/minecraft/net/minecraft/data/HashCache.java.patch
Labels: Triage, 1.19

#8716 [1.19.x] Add CommandBuildContext to Register Command Events
  patches/minecraft/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
  patches/minecraft/net/minecraft/commands/Commands.java.patch
  src/main/java/net/minecraftforge/client/ClientCommandHandler.java
  src/main/java/net/minecraftforge/client/event/RegisterClientCommandsEvent.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/RegisterCommandsEvent.java
Labels: Feature, BreakingChange, Assigned, 1.19

#8727 [1.19.x] Fix experimental confirmation screen
  build.gradle
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/WorldOpenFlows.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/resources/forge.exc
Labels: Bug, Assigned, 1.19

#8693 [1.19.x] Fix mods' worldgen data not being loaded when creating new singleplayer worlds
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch
Labels: Bug, Assigned, 1.19

#8699 Fix Reach Distance / Attack Range being clamped at 6.0
  patches/minecraft/net/minecraft/server/level/ServerPlayerGameMode.java.patch
  patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
Labels: Regression, Assigned, 1.19

#8700 Replace support bot with support action
  .github/support.yml
  .github/workflows/support.yml
Labels: Cleanup, Assigned, 1.19

#8733 Fix wrong patch in LootItemRandomChanceCondition
  patches/minecraft/net/minecraft/world/level/storage/loot/predicates/LootItemRandomChanceCondition.java.patch
Labels: Bug, Assigned, 1.19

#8707 [1.19.x] Use stack sensitive translation key by default
  src/main/java/net/minecraftforge/fluids/FluidAttributes.java
Labels: Bug, Assigned, 1.19

#8717 Replace non-functional StructureSpawnListGatherEvent with StructureModifiers
  build.gradle
  patches/minecraft/net/minecraft/world/level/NaturalSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/structure/Structure.java.patch
  src/generated_test/resources/data/structure_modifiers_test/forge/structure_modifier/modify_stronghold.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/data/JsonCodecProvider.java
  src/main/java/net/minecraftforge/common/world/BiomeModifier.java
  src/main/java/net/minecraftforge/common/world/ModifiableStructureInfo.java
  src/main/java/net/minecraftforge/common/world/NoneStructureModifier.java
  src/main/java/net/minecraftforge/common/world/StructureModifier.java
  src/main/java/net/minecraftforge/common/world/StructureSettingsBuilder.java
  src/main/java/net/minecraftforge/common/world/StructureSpawnManager.java
  src/main/java/net/minecraftforge/event/world/StructureSpawnListGatherEvent.java
  src/main/java/net/minecraftforge/registries/ForgeDeferredRegistriesSetup.java
  src/main/java/net/minecraftforge/registries/ForgeRegistries.java
  src/main/java/net/minecraftforge/server/ServerLifecycleHooks.java
  src/main/resources/coremods/field_to_method.js
  src/test/java/net/minecraftforge/debug/world/BiomeModifierTest.java
  src/test/java/net/minecraftforge/debug/world/StructureModifierTest.java
  src/test/java/net/minecraftforge/debug/world/StructureSpawnListGatherEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, BreakingChange, Assigned, 1.19

#8697 [1.19.x] Add stock biome modifier types for adding features and spawns
  src/generated_test/resources/data/biome_modifiers_test/forge/biome_modifier/add_basalt.json
  src/generated_test/resources/data/biome_modifiers_test/forge/biome_modifier/add_magma_cubes.json
  src/generated_test/resources/data/biome_modifiers_test/forge/biome_modifier/modify_badlands.json
  src/generated_test/resources/data/biome_modifiers_test/forge/biome_modifier/remove_forest_skeletons.json
  src/generated_test/resources/data/biome_modifiers_test/forge/biome_modifier/remove_forest_trees.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/data/JsonCodecProvider.java
  src/main/java/net/minecraftforge/common/world/ForgeBiomeModifiers.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/world/BiomeModifierTest.java
Labels: Feature, Assigned, 1.19

#8719 [1.19] Add support for items to add enchantments without setting them in NBT
  patches/minecraft/net/minecraft/advancements/critereon/ItemPredicate.java.patch
  patches/minecraft/net/minecraft/world/inventory/GrindstoneMenu.java.patch
  patches/minecraft/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/gameplay/loot/GlobalLootModifiersTest.java
  src/test/resources/data/global_loot_test/loot_modifiers/silk_touch_bamboo.json
Labels: Feature, BreakingChange, Triage, 1.19

#8737 [1.19.x] Affect ItemEntity Motion in Custom Fluids
  patches/minecraft/net/minecraft/world/entity/item/ItemEntity.java.patch
Labels: Bug, Fluids, Assigned, 1.19

#8738 [1.19.x] Fix Player Dive and Surface Animations in Custom Fluids
  patches/minecraft/net/minecraft/client/renderer/entity/player/PlayerRenderer.java.patch
Labels: Bug, Fluids, Assigned, 1.19

#8724 [1.19] Fix data-gen output path of custom data-pack registries
  patches/minecraft/net/minecraft/data/info/WorldgenRegistryDumpReport.java.patch
  patches/minecraft/net/minecraft/resources/RegistryResourceAccess.java.patch
  patches/minecraft/net/minecraft/tags/TagManager.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Bug, Assigned, 1.19

#8715 [1.19] Jar-In-Jar
  build.gradle
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java
  fmlloader/build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/EarlyLoadingException.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/UniqueModListBuilder.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractJarFileDependencyLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractJarFileModLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractJarFileModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ClasspathLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/MavenDirectoryLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/MinecraftLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModDiscoverer.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModValidator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModsFolderLocator.java
  fmlloader/src/main/resources/META-INF/services/net.minecraftforge.forgespi.locating.IDependencyLocator
  src/main/java/net/minecraftforge/client/gui/LoadingErrorScreen.java
  src/main/java/net/minecraftforge/client/gui/ModListScreen.java
  src/main/resources/assets/forge/lang/en_us.json
  src/test/resources/META-INF/jarjar/ForgeJiJTestMod-1.2.jar
  src/test/resources/META-INF/jarjar/metadata.json
  src/test/resources/META-INF/mods.toml
Labels: Feature, Triage, 1.19

#8728 Fix EnumArgument to use enum names for suggestions
  src/main/java/net/minecraftforge/server/command/EnumArgument.java
Labels: Bug, Assigned, 1.19

#8236 Change ConfigValue#get() to throw if called before config loaded
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Feature, BreakingChange, Assigned, 1.19

#8756 Remove ForgeWorldPreset and related code
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/world/ForgeWorldPreset.java
  src/main/java/net/minecraftforge/registries/ForgeDeferredRegistriesSetup.java
  src/main/java/net/minecraftforge/registries/ForgeRegistries.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/test/java/net/minecraftforge/debug/world/ForgeWorldTypeTest.java
  src/test/resources/META-INF/mods.toml
Labels: BreakingChange, Cleanup, Triage, 1.19

#8757 Fix SP-Devtime world loading crash due to missing server configs
  patches/minecraft/net/minecraft/world/item/crafting/ShapelessRecipe.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Bug, Cleanup, Assigned, 1.19

#8749 Sanity check the version specified in the mod file
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/LoadingModList.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractJarFileDependencyLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractJarFileModLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ExplodedDirectoryLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/InvalidModFileException.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/MinecraftLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModDiscoverer.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModValidator.java
Labels: Bug, Assigned, 1.19

#8774 Update SJH to 2.0.2..
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ExplodedDirectoryLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java
Labels: Feature, Assigned, 1.19

#8759 Add "send to mods in order" method to ModList and use it
  fmlcore/src/main/java/net/minecraftforge/fml/ModList.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java
  src/main/java/net/minecraftforge/forge/event/lifecycle/GatherDataEvent.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/RegistryManager.java
Labels: Feature, Assigned, 1.19

#8776 Make Forge ConfigValues implement Supplier.
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Feature, Triage, 1.19

#8681 Make fishing rods use tool actions for relevant logic
  patches/minecraft/net/minecraft/client/renderer/entity/FishingHookRenderer.java.patch
  patches/minecraft/net/minecraft/world/entity/projectile/FishingHook.java.patch
  patches/minecraft/net/minecraft/world/item/FishingRodItem.java.patch
  src/main/java/net/minecraftforge/common/ToolActions.java
Labels: Feature, Assigned, 1.19

#8684 Add biome tag entries for 1.19 biomes
  src/generated/resources/data/forge/tags/worldgen/biome/is_hot.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_hot/overworld.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_overworld.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_rare.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_spooky.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_swamp.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_underground.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_wet.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_wet/overworld.json
  src/main/java/net/minecraftforge/common/data/ForgeBiomeTagsProvider.java
Labels: Feature, Assigned, 1.19

#8686 [1.19] Add callback after a BlockState was changed
  patches/minecraft/net/minecraft/world/level/Level.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
Labels: Feature, Assigned, Needs Rebase, 1.19

#8761 [1.19.x] Fix TagsProviders for datapack registries not recognizing existing files
  patches/minecraft/net/minecraft/data/tags/TagsProvider.java.patch
  patches/minecraft/net/minecraft/tags/TagEntry.java.patch
Labels: Bug, Assigned, 1.19

#8765 [1.19.x] The ServerTickEvent will now contain a reference to the MinecraftServer.
  patches/minecraft/net/minecraft/server/MinecraftServer.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/TickEvent.java
Labels: Feature, Assigned, 1.19

#8766 Method parity between vanilla registries and Forge registry wrappers
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
  src/main/java/net/minecraftforge/registries/NamespacedDefaultedWrapper.java
  src/main/java/net/minecraftforge/registries/NamespacedHolderHelper.java
  src/main/java/net/minecraftforge/registries/NamespacedWrapper.java
Labels: Bug, Cleanup, Assigned, 1.19

#8767 [1.19] Fix default audio device error
  patches/minecraft/net/minecraft/client/Options.java.patch
Labels: Bug, Assigned, 1.19

#8775 Fix ticking chunk tickets from forge's chunk manager not causing chunks to fully tick
  patches/minecraft/net/minecraft/server/level/DistanceManager.java.patch
  patches/minecraft/net/minecraft/server/level/ServerChunkCache.java.patch
  src/main/java/net/minecraftforge/common/world/ForgeChunkManager.java
  src/main/resources/forge.exc
Labels: Bug, Regression, BreakingChange, Assigned, 1.19

#8778 Fix BlockToolModificationEvent cancelability
  src/main/java/net/minecraftforge/event/world/BlockEvent.java
Labels: Regression, Cleanup, Assigned, 1.19

#8781 [1.19.x] Add getter for correct BiomeSpecialEffectsBuilder to BiomeInfo$Builder
  src/main/java/net/minecraftforge/common/world/ModifiableBiomeInfo.java
Labels: Bug, Cleanup, Assigned, 1.19

#8787 [1.19] Chest Boat Item Handler
  patches/minecraft/net/minecraft/world/entity/vehicle/ChestBoat.java.patch
Labels: Bug, Assigned, 1.19

#8747 Fire ChunkWatchEvents after sending packets
  patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/world/ChunkWatchEvent.java
Labels: Feature, BreakingChange, Assigned, 1.19

#8792 Add MC-105317 fix into patch to rotate entities in structures properly
  patches/minecraft/net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplate.java.patch
Labels: Bug, Assigned, 1.19

#8799 Remove the configuration option for handling empty tags in ingredients.
  patches/minecraft/net/minecraft/world/item/crafting/Ingredient.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Bug, BreakingChange, Assigned, 1.19

#8802 Fix crash after loading error due to fluid texture gathering and config lookup
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
Labels: Bug, Assigned, 1.19

#8685 [1.19] Allow safely registering RenderType predicates at any time
  patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch
  src/main/java/net/minecraftforge/client/extensions/ForgeItemBlockRenderTypes.java
Labels: Performance, Feature, Rendering, Assigned, 1.19

#8780 [1.19] Fix certain user-configured options being overwritten
  patches/minecraft/net/minecraft/client/Options.java.patch
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
  src/main/resources/forge.exc
Labels: Bug, Triage, 1.19

#8671 [1.18.x] Allow safely registering RenderType predicates at any time
  patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch
Labels: Performance, Rendering, Assigned, LTS Backport, 1.18
