Repository MinecraftForge/MinecraftForge, pull requests merged in 2022-03, with the labels that each got.

#8500 Add missing module exports arg to server arguments list
  build.gradle
  server_files/args.txt
Labels: Bug, Cleanup, Triage, 1.18

#8238 Introduce system mods to mod loading
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java
  src/main/resources/META-INF/MANIFEST.MF
Labels: Feature, Triage, 1.18

#8483 Add event for controlling potion indicators size
  patches/minecraft/net/minecraft/client/gui/screens/inventory/EffectRenderingInventoryScreen.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/ScreenEvent.java
  src/test/java/net/minecraftforge/debug/client/PotionSizeEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, New Event, Rendering, Assigned, 1.18

#8482 Fix item durability dar to respect custom max damage
  patches/minecraft/net/minecraft/world/item/Item.java.patch
Labels: Bug, Rendering, Assigned, 1.18

#8470 Provide access to the haveTime supplier in WorldTickEvent and ServerTickEvent
  patches/minecraft/net/minecraft/server/MinecraftServer.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/TickEvent.java
Labels: Feature, Assigned, 1.18

#8431 [1.18.x] Use wither as griefing entity for roses
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
Labels: Feature, Assigned, 1.18

#8486 Use UTF-8 charset for Java compilation
  build.gradle
  mdk/build.gradle
Labels: Feature, Cleanup, Assigned, 1.18

#8493 Re-expose server resources to reload listener event
  patches/minecraft/net/minecraft/server/ReloadableServerResources.java.patch
  src/main/java/net/minecraftforge/event/AddReloadListenerEvent.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: Regression, Triage, 1.18

#8468 [1.16.x] Prevent setting window icon on OSX
  patches/minecraft/net/minecraft/client/MainWindow.java.patch
  src/fmllauncher/java/net/minecraftforge/fml/loading/progress/ClientVisualization.java
Labels: Vanilla Bug, Rendering, Triage, 1.16

#8502 Clear local variable table on RuntimeEnumExtender transformation
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/RuntimeEnumExtender.java
Labels: Bug, Assigned, 1.18

#8340 Clear local variable table on RuntimeEnumExtender transformation
  src/fmllauncher/java/net/minecraftforge/common/asm/RuntimeEnumExtender.java
Labels: Bug, Assigned, 1.16, LTS Backport

#8512 [1.18.x] Fix FMLOnly in forgedev and userdev
  fmlonly/src/main/java/net/minecraftforge/fmlonly/FMLOnlyBindings.java
  fmlonly/src/main/java/net/minecraftforge/fmlonly/FMLOnlyMod.java
  fmlonly/src/main/java/net/minecraftforge/fmlonlyclient/ClientModLoader.java
  fmlonly/src/main/resources/META-INF/mods.toml
Labels: Regression, Triage, 1.18

#8300 [1.18.x] Allow blocks to hide faces on a neighboring block
  patches/minecraft/net/minecraft/world/level/BlockGetter.java.patch
  patches/minecraft/net/minecraft/world/level/block/Block.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockGetter.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
  src/test/java/net/minecraftforge/debug/block/HideNeighborFaceTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/hide_neighbor_face_test/blockstates/glass_slab.json
  src/test/resources/assets/hide_neighbor_face_test/models/block/glass_slab.json
  src/test/resources/assets/hide_neighbor_face_test/models/block/glass_slab_top.json
Labels: Feature, Rendering, Assigned, Triage, 1.18

#7606 Fix MC-176559 Breaking animation and process resets when a pickaxe enchanted with Mending mends by XP / Mending slows down breaking blocks again
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
Labels: Vanilla Bug, Assigned, Triage, 1.18

#8417 Lower custom item entity replacement from highest to high so mods can cancel it during a specific tick
  src/main/java/net/minecraftforge/common/ForgeInternalHandler.java
Labels: Feature, Assigned, 1.19

#8495 [1.18.2] Fix tags for custom forge registries
  patches/minecraft/net/minecraft/core/Holder.java.patch
  patches/minecraft/net/minecraft/core/MappedRegistry.java.patch
  patches/minecraft/net/minecraft/data/tags/BiomeTagsProvider.java.patch
  patches/minecraft/net/minecraft/data/tags/BlockTagsProvider.java.patch
  patches/minecraft/net/minecraft/data/tags/ConfiguredStructureTagsProvider.java.patch
  patches/minecraft/net/minecraft/data/tags/EntityTypeTagsProvider.java.patch
  patches/minecraft/net/minecraft/data/tags/FluidTagsProvider.java.patch
  patches/minecraft/net/minecraft/data/tags/GameEventTagsProvider.java.patch
  patches/minecraft/net/minecraft/data/tags/ItemTagsProvider.java.patch
  patches/minecraft/net/minecraft/data/tags/TagsProvider.java.patch
  patches/minecraft/net/minecraft/tags/TagManager.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/WorldGenSettings.java.patch
  src/main/java/net/minecraftforge/client/ForgeWorldPresetScreens.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/ForgeStatesProvider.java
  src/main/java/net/minecraftforge/common/ForgeTagHandler.java
  src/main/java/net/minecraftforge/common/data/ForgeRegistryTagsProvider.java
  src/main/java/net/minecraftforge/common/loot/LootModifierManager.java
  src/main/java/net/minecraftforge/common/world/ForgeWorldPreset.java
  src/main/java/net/minecraftforge/event/RegistryEvent.java
  src/main/java/net/minecraftforge/network/filters/VanillaConnectionNetworkFilter.java
  src/main/java/net/minecraftforge/registries/DeferredRegister.java
  src/main/java/net/minecraftforge/registries/ForgeDeferredRegistriesSetup.java
  src/main/java/net/minecraftforge/registries/ForgeRegistries.java
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
  src/main/java/net/minecraftforge/registries/ForgeRegistryTag.java
  src/main/java/net/minecraftforge/registries/ForgeRegistryTagManager.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/IForgeRegistry.java
  src/main/java/net/minecraftforge/registries/IHolderHelperHolder.java
  src/main/java/net/minecraftforge/registries/NamespacedDefaultedWrapper.java
  src/main/java/net/minecraftforge/registries/NamespacedHolderHelper.java
  src/main/java/net/minecraftforge/registries/NamespacedWrapper.java
  src/main/java/net/minecraftforge/registries/NewRegistryEvent.java
  src/main/java/net/minecraftforge/registries/RegistryBuilder.java
  src/main/java/net/minecraftforge/registries/RegistryManager.java
  src/main/java/net/minecraftforge/registries/RegistryObject.java
  src/main/java/net/minecraftforge/registries/tags/IReverseTag.java
  src/main/java/net/minecraftforge/registries/tags/ITag.java
  src/main/java/net/minecraftforge/registries/tags/ITagManager.java
  src/main/java/net/minecraftforge/server/command/ForgeCommand.java
  src/main/java/net/minecraftforge/server/command/TagsCommand.java
  src/main/resources/assets/forge/lang/en_us.json
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/DeferredRegistryTest.java
  src/test/java/net/minecraftforge/debug/DuplicateOptionalTagTest.java
  src/test/java/net/minecraftforge/debug/RegistryObjectTest.java
  src/test/java/net/minecraftforge/debug/entity/AddEntityAttributeTest.java
  src/test/java/net/minecraftforge/debug/gameplay/loot/GlobalLootModifiersTest.java
  src/test/java/net/minecraftforge/debug/item/CustomShieldTest.java
Labels: Regression, BreakingChange, Cleanup, Assigned, 1.18

#8516 Add onServerChatEvent null check
  patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
Labels: Bug, Assigned, 1.18

#8295 Allow sound instances to play custom audio streams
  patches/minecraft/net/minecraft/client/MouseHandler.java.patch
  patches/minecraft/net/minecraft/client/resources/sounds/SoundInstance.java.patch
  patches/minecraft/net/minecraft/client/sounds/SoundEngine.java.patch
  src/test/java/net/minecraftforge/debug/client/AudioStreamTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/audio_stream_test/sounds.json
  src/test/resources/assets/audio_stream_test/sounds/empty.ogg
Labels: Feature, Assigned, 1.18

#8380 Add patches to enable MobEffects with IDs > 255
  patches/minecraft/net/minecraft/client/multiplayer/ClientPacketListener.java.patch
  patches/minecraft/net/minecraft/world/effect/MobEffectInstance.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/MushroomCow.java.patch
  patches/minecraft/net/minecraft/world/item/SuspiciousStewItem.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/test/java/net/minecraftforge/debug/ManyMobEffectsTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.18

#8515 [1.18.x] Update Forge Auto Renaming Tool to 0.1.22
  build.gradle
Labels: Cleanup, Assigned, 1.18

#8492 Rework fog events
  patches/minecraft/net/minecraft/client/renderer/FogRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/EntityViewRenderEvent.java
Labels: Feature, Cleanup, Rendering, Assigned, 1.18

#8351 [1.18] Make it easier to register custom skull blocks models
  patches/minecraft/net/minecraft/client/renderer/blockentity/SkullBlockRenderer.java.patch
  src/main/java/net/minecraftforge/client/event/EntityRenderersEvent.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/block/CustomHeadTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/custom_head_test/blockstates/blaze_head.json
  src/test/resources/assets/custom_head_test/blockstates/blaze_wall_head.json
  src/test/resources/assets/custom_head_test/models/item/blaze_head.json
Labels: Feature, Rendering, Assigned, 1.18

#7971 [1.16.x] Account for `/forge setdimension` command arguments
  src/main/java/net/minecraftforge/server/command/CommandSetDimension.java
Labels: Bug, Assigned, 1.16

#7125 EntityMountEvent Infinite Client Loop Fix
  patches/minecraft/net/minecraft/client/entity/player/ClientPlayerEntity.java.patch
Labels: Bug, Assigned, 1.16, LTS Backport

#8532 Fix incorrect method used in getStream
  patches/minecraft/net/minecraft/client/resources/sounds/SoundInstance.java.patch
Labels: Regression, Assigned, 1.18

#8490 Re-add access transformer for RecipeProvider#has with tag argument
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Feature, Cleanup, Assigned, 1.18

#8514 [1.18.2] Add hook for making custom boots that can walk on powdered snow
  patches/minecraft/net/minecraft/world/level/block/PowderSnowBlock.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
  src/test/java/net/minecraftforge/debug/item/SnowBootsTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.18

#7275 Add option to auto-confirm the experimental settings screen and an icon in world list for experimental settings.
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/WorldSelectionList.java.patch
  patches/minecraft/net/minecraft/world/level/LevelSettings.java.patch
  patches/minecraft/net/minecraft/world/level/storage/LevelSummary.java.patch
  patches/minecraft/net/minecraft/world/level/storage/PrimaryLevelData.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/resources/assets/forge/lang/en_us.json
  src/main/resources/assets/forge/textures/gui/experimental_warning.png
  src/main/resources/forge.exc
Labels: Feature, Assigned, 1.18

#8322 [1.18.x] Add an event when a living entity gets a projectile item stack to be fired
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/Monster.java.patch
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/entity/living/LivingGetProjectileEvent.java
  src/test/java/net/minecraftforge/debug/entity/living/LivingGetProjectileEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, New Event, Assigned, 1.18

#8517 [1.18.x] Add 3 new ingredient types, and make existing ingredients compatible with datagen
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/data_gen_test/advancements/recipes/building_blocks/compound_ingredient_custom_types.json
  src/generated_test/resources/data/data_gen_test/advancements/recipes/building_blocks/compound_ingredient_only_vanilla.json
  src/generated_test/resources/data/data_gen_test/advancements/recipes/building_blocks/intersection_ingredient.json
  src/generated_test/resources/data/data_gen_test/advancements/recipes/tools/contains_nbt_ingredient_item_set.json
  src/generated_test/resources/data/data_gen_test/advancements/recipes/tools/contains_nbt_ingredient_single_item.json
  src/generated_test/resources/data/data_gen_test/advancements/recipes/tools/difference_ingredient.json
  src/generated_test/resources/data/data_gen_test/advancements/recipes/tools/exact_nbt_ingredient.json
  src/generated_test/resources/data/data_gen_test/recipes/compound_ingredient_custom_types.json
  src/generated_test/resources/data/data_gen_test/recipes/compound_ingredient_only_vanilla.json
  src/generated_test/resources/data/data_gen_test/recipes/contains_nbt_ingredient_item_set.json
  src/generated_test/resources/data/data_gen_test/recipes/contains_nbt_ingredient_single_item.json
  src/generated_test/resources/data/data_gen_test/recipes/difference_ingredient.json
  src/generated_test/resources/data/data_gen_test/recipes/exact_nbt_ingredient.json
  src/generated_test/resources/data/data_gen_test/recipes/intersection_ingredient.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/crafting/AbstractIngredient.java
  src/main/java/net/minecraftforge/common/crafting/CompoundIngredient.java
  src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java
  src/main/java/net/minecraftforge/common/crafting/DifferenceIngredient.java
  src/main/java/net/minecraftforge/common/crafting/IntersectionIngredient.java
  src/main/java/net/minecraftforge/common/crafting/NBTIngredient.java
  src/main/java/net/minecraftforge/common/crafting/PartialNBTIngredient.java
  src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
Labels: Feature, Assigned, 1.18

#8028 1.18 Allow mod menus to have their own recipebook
  patches/minecraft/net/minecraft/client/ClientRecipeBook.java.patch
  patches/minecraft/net/minecraft/client/RecipeBookCategories.java.patch
  patches/minecraft/net/minecraft/stats/RecipeBookSettings.java.patch
  patches/minecraft/net/minecraft/world/inventory/RecipeBookType.java.patch
  src/main/java/net/minecraftforge/client/RecipeBookRegistry.java
  src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookExtensionClientHelper.java
  src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookExtensionTest.java
  src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookTestMenu.java
  src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookTestRecipe.java
  src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookTestRecipeSerializer.java
  src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookTestScreen.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/data/recipe_book_extension_test/advancements/recipes/recipe_book_extension_advancment.json
  src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_1.json
  src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_2.json
  src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_3.json
  src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_4.json
  src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_5.json
Labels: Feature, Assigned, 1.18

#8533 [1.18.x] Fix lost validation of registry data on singleplayer world load
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/data/tags/TagsProvider.java.patch
  patches/minecraft/net/minecraft/server/Main.java.patch
  patches/minecraft/net/minecraft/server/MinecraftServer.java.patch
  patches/minecraft/net/minecraft/world/item/HorseArmorItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeFluid.java
  src/main/resources/forge.exc
Labels: Regression, Assigned, 1.18

#8534 [1.18.x] Allow Brewing Stand to Properly Handle Stacked Items in Bottle Slots
  patches/minecraft/net/minecraft/world/inventory/BrewingStandMenu.java.patch
  src/main/java/net/minecraftforge/common/brewing/BrewingRecipeRegistry.java
Labels: Bug, Assigned, 1.18

#8539 Remove cut copper from copper storage blocks tag
  src/generated/resources/data/forge/tags/blocks/storage_blocks/copper.json
  src/generated/resources/data/forge/tags/items/storage_blocks/copper.json
  src/main/java/net/minecraftforge/common/data/ForgeBlockTagsProvider.java
Labels: Bug, Assigned, 1.18
