Repository MinecraftForge/MinecraftForge, pull requests merged in 2022-09, with the labels that each got.

#9007 Fix failed entity interactions consuming the click.
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
Labels: Bug, Triage, 1.19

#9005 [1.19.2] fix misplaced patch in sapling block
  patches/minecraft/net/minecraft/world/level/block/SaplingBlock.java.patch
Labels: Bug, Assigned, 1.19

#9000 [1.19.x] Moved Player.resetAttackStrengthTicker() to the end of Player.attack()
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
Labels: Feature, Assigned, 1.19

#8999 [1.19.x] Add IForgeBlock#onTreeGrow to replace IForgeBlock#onPlantGrow from 1.16
  patches/minecraft/net/minecraft/world/level/levelgen/feature/trunkplacers/TrunkPlacer.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
  src/test/java/net/minecraftforge/debug/block/OnTreeGrowBlockTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/on_tree_grow_block_test/blockstates/test_dirt.json
  src/test/resources/assets/on_tree_grow_block_test/blockstates/test_grass_block.json
  src/test/resources/assets/on_tree_grow_block_test/models/block/test_dirt.json
  src/test/resources/assets/on_tree_grow_block_test/models/block/test_grass_block.json
  src/test/resources/assets/on_tree_grow_block_test/models/item/test_dirt.json
  src/test/resources/assets/on_tree_grow_block_test/models/item/test_grass_block.json
  src/test/resources/assets/on_tree_grow_block_test/textures/blocks/test_dirt.png
  src/test/resources/assets/on_tree_grow_block_test/textures/blocks/test_grass_block_side.png
  src/test/resources/assets/on_tree_grow_block_test/textures/blocks/test_grass_block_side_overlay.png
  src/test/resources/assets/on_tree_grow_block_test/textures/blocks/test_grass_block_top.png
  src/test/resources/data/on_tree_grow_block_test/tags/blocks/dirt.json
Labels: Feature, Assigned, 1.19

#8975 Backport #8881 to 1.18
  fmlcore/src/main/java/net/minecraftforge/fml/VersionChecker.java
Labels: Feature, Assigned, LTS Backport, 1.18

#8954 [1.19.x] Make LivingSetAttackTargetEvent compatible with the Brain/Behavior system. (Port of PR #8918)
  patches/minecraft/net/minecraft/world/entity/Mob.java.patch
  patches/minecraft/net/minecraft/world/entity/ai/behavior/StartAttacking.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/entity/living/LivingChangeTargetEvent.java
  src/main/java/net/minecraftforge/event/entity/living/LivingSetAttackTargetEvent.java
  src/test/java/net/minecraftforge/debug/entity/living/LivingSetAttackTargetEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.19

#8860 [1.19.x] Block Model Builder Root Transform Support
  src/main/java/net/minecraftforge/client/model/generators/BlockModelBuilder.java
  src/main/java/net/minecraftforge/common/util/TransformationHelper.java
Labels: Feature, Assigned, 1.19

#8872 [1.19] Add hook for items to remain in the hotbar when picking blocks/entities
  patches/minecraft/net/minecraft/world/entity/player/Inventory.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
Labels: Feature, Assigned, 1.19

#9008 LTS Backport of #9007 (Entity reach distance fix)
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
Labels: Bug, Triage, LTS Backport, 1.18

#8827 Default IItemHandler capability for shulker box itemstacks
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/items/wrapper/ShulkerItemStackInvWrapper.java
Labels: Feature, Capabilities, Triage, 1.19

#8360 [1.19.X] Adding more precise events for Advancements
  patches/minecraft/net/minecraft/server/PlayerAdvancements.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/player/AdvancementEvent.java
  src/test/java/net/minecraftforge/debug/entity/player/AdvancementEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, New Event, Assigned, 1.18

#8956 [1.19.x] add methods with more context to tree growers
  patches/minecraft/net/minecraft/world/level/block/grower/AbstractMegaTreeGrower.java.patch
  patches/minecraft/net/minecraft/world/level/block/grower/AbstractTreeGrower.java.patch
Labels: Feature, Assigned, 1.19

#9004 Fix `tryEmptyContainerAndStow` duping fluids with stackable containers
  src/main/java/net/minecraftforge/client/event/RegisterItemDecorationsEvent.java
  src/main/java/net/minecraftforge/fluids/FluidUtil.java
  src/test/java/net/minecraftforge/debug/FluidUtilTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Fluids, Assigned, 1.19

#9014 Fix Transform Origin serialized names
  src/main/java/net/minecraftforge/client/model/generators/BlockModelBuilder.java
Labels: Regression, Assigned, 1.19

#8934 Grindstone Event
  patches/minecraft/net/minecraft/world/inventory/GrindstoneMenu.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/GrindstoneEvent.java
Labels: Feature, New Event, Triage, 1.19

#9021 Allow mods to specify shader import namespace
  patches/minecraft/net/minecraft/client/renderer/ShaderInstance.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/test/java/net/minecraftforge/debug/client/rendering/ShaderResourcesTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/shader_resources_test/shaders/core/vertex_cubemap.fsh
  src/test/resources/assets/shader_resources_test/shaders/core/vertex_cubemap.json
  src/test/resources/assets/shader_resources_test/shaders/core/vertex_cubemap.vsh
  src/test/resources/assets/shader_resources_test/shaders/include/cubemap_includes.glsl
Labels: Feature, Rendering, Assigned, 1.19

#9017 Create a Forge EntityType Tag for Bosses
  src/generated/resources/data/forge/tags/entity_types/bosses.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeEntityTypeTagsProvider.java
Labels: Feature, Assigned, 1.19

#9010 LTS Backport of ModMistachEvent (#8989)
  patches/minecraft/net/minecraft/world/level/storage/LevelStorageSource.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/ModMismatchEvent.java
Labels: Feature, New Event, Assigned, LTS Backport, 1.18

#8991 Added Bookshelves block tag
  src/generated/resources/data/forge/tags/blocks/bookshelves.json
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeBlockTagsProvider.java
Labels: Feature, Assigned, 1.19

#8981 [1.19.x] Added event for growing fungus
  patches/minecraft/net/minecraft/world/level/block/FungusBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/MushroomBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/SaplingBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/grower/AbstractMegaTreeGrower.java.patch
  patches/minecraft/net/minecraft/world/level/block/grower/AbstractTreeGrower.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/level/SaplingGrowTreeEvent.java
  src/test/java/net/minecraftforge/debug/world/BlockGrowFeatureTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.19

#8936 Update fence_gates/wooden
  src/generated/resources/data/forge/tags/blocks/fence_gates/wooden.json
  src/generated/resources/data/forge/tags/items/fence_gates/wooden.json
  src/main/java/net/minecraftforge/common/data/ForgeBlockTagsProvider.java
Labels: Bug, Assigned, 1.19

#8876 [1.19.x] Recipe ID-based grouping between modded and vanilla recipes.
  patches/minecraft/net/minecraft/client/ClientRecipeBook.java.patch
Labels: Feature, Assigned, 1.19

#9019 Allow faces of an "elements" model to have disabled ambient occlusion
  patches/minecraft/net/minecraft/client/renderer/block/ModelBlockRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/model/BakedQuad.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/model/BlockElementFace.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/model/FaceBakery.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/model/IQuadTransformer.java
  src/main/java/net/minecraftforge/client/model/generators/ModelBuilder.java
  src/main/java/net/minecraftforge/client/model/lighting/ForgeModelBlockRenderer.java
  src/main/java/net/minecraftforge/client/model/pipeline/QuadBakingVertexConsumer.java
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/client/AmbientOcclusionElementsTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/ambient_occlusion_elements_test/blockstates/ambient_occlusion_no_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/blockstates/ambient_occlusion_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/blockstates/no_ambient_occlusion_no_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/blockstates/no_ambient_occlusion_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/models/block/ambient_occlusion_no_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/models/block/ambient_occlusion_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/models/block/no_ambient_occlusion_no_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/models/block/no_ambient_occlusion_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/models/item/ambient_occlusion_no_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/models/item/ambient_occlusion_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/models/item/no_ambient_occlusion_no_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/models/item/no_ambient_occlusion_shade.json
  src/test/resources/assets/ambient_occlusion_elements_test/textures/block/solid.png
Labels: Feature, Rendering, Triage, 1.19

#8998 [1.18.x] Backport #8981 to 1.18
  patches/minecraft/net/minecraft/world/level/block/FungusBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/MushroomBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/SaplingBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/grower/AbstractMegaTreeGrower.java.patch
  patches/minecraft/net/minecraft/world/level/block/grower/AbstractTreeGrower.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/world/SaplingGrowTreeEvent.java
  src/test/java/net/minecraftforge/debug/world/BlockGrowFeatureTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Triage, LTS Backport, 1.18

#9026 [1.18] Revert resource caching
  patches/minecraft/net/minecraft/server/packs/VanillaPackResources.java.patch
  patches/minecraft/net/minecraft/server/packs/resources/FallbackResourceManager.java.patch
  patches/minecraft/net/minecraft/server/packs/resources/MultiPackResourceManager.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/common/extensions/IForgePackResources.java
  src/main/java/net/minecraftforge/resource/DelegatingResourcePack.java
  src/main/java/net/minecraftforge/resource/PathResourcePack.java
  src/main/java/net/minecraftforge/resource/ResourceCacheManager.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/forge/lang/en_us.json
Labels: Performance, Regression, Triage, 1.18

#9033 [1.19] Fix minecarts on rails not properly slowing down in water
  patches/minecraft/net/minecraft/world/entity/vehicle/AbstractMinecart.java.patch
Labels: Bug, Assigned, 1.19

#9038 [1.19.x] Use owner for SmallFireball mobGriefing event
  patches/minecraft/net/minecraft/world/entity/projectile/SmallFireball.java.patch
Labels: Regression, Assigned, 1.19

#9051 Fix Tags (b0caea8e204a7f026646396558d6d58a02bff9d6)
  src/generated/resources/data/forge/tags/worldgen/biome/is_desert.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_hot.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_wet.json
  src/main/java/net/minecraftforge/common/data/ForgeBiomeTagsProvider.java
Labels: Bug, Assigned, 1.19

#9057 Fix `KeyMapping` Control Modifier on Mac to not be Alt
  src/main/java/net/minecraftforge/client/settings/KeyModifier.java
Labels: Bug, Assigned, 1.19

#9056 [1.19.2] Make comment field be a List, make comment() behavior be append-only
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Feature, Assigned, 1.19
