Repository MinecraftForge/MinecraftForge, pull requests merged in 2022-10, with the labels that each got.

#9074 [1.19.x] Fix NPE when feeding wolves and cats
  patches/minecraft/net/minecraft/world/entity/animal/Cat.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/Wolf.java.patch
Labels: Bug, 1.19

#9029 [1.19]: Fix performance issue and logging when resource caching is enabled
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
  fmlloader/src/main/resources/log4j2.xml
  patches/minecraft/net/minecraft/server/packs/VanillaPackResources.java.patch
  patches/minecraft/net/minecraft/server/packs/resources/FallbackResourceManager.java.patch
  src/fmllauncher/resources/log4j2.xml
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/resource/PathPackResources.java
  src/main/java/net/minecraftforge/resource/ResourceCacheManager.java
Labels: Bug, Regression, Assigned, 1.19

#9069 Add a cancellable event that gets fired when a Totem of Undying is used
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/entity/living/LivingUseTotemEvent.java
Labels: Feature, New Event, Assigned, 1.19, hacktoberfest-accepted

#9076 [1.19] Fix Vanilla Minecart interactions with Water
  patches/minecraft/net/minecraft/world/entity/vehicle/AbstractMinecart.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBaseRailBlock.java
Labels: Bug, Fluids, Assigned, 1.19, hacktoberfest-accepted

#9077 [1.19.x] Rename fluid type milk translation keys
  src/main/resources/assets/forge/lang/en_us.json
Labels: Bug, Regression, Fluids, Assigned, 1.19, hacktoberfest-accepted

#9079 [1.19.x] Fixed the PlayerInteractEvent.EntityInteractSpecific not respecting cancelled status on server side
  patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
Labels: Bug, Assigned, 1.19

#9075 [1.18.x] Fix NPE when feeding cats and wolves
  patches/minecraft/net/minecraft/world/entity/animal/Cat.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/Wolf.java.patch
Labels: Bug, Assigned, LTS Backport, 1.18, hacktoberfest-accepted

#9082 [1.18.x] Fix TileFluidHandler not invalidating the lazy optional properly
  src/main/java/net/minecraftforge/fluids/capability/TileFluidHandler.java
Labels: Bug, Assigned, 1.18

#9046 [1.19.2] Do not cache default value returned by supplier in ForgeConfigSpec$ValueSpec
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Bug, Triage, 1.19

#8984 [1.18.x] Backport #8876 to 1.18.
  patches/minecraft/net/minecraft/client/ClientRecipeBook.java.patch
Labels: Feature, Assigned, LTS Backport, 1.18

#8918 [1.18.x] Make LivingSetAttackTargetEvent compatible with the Brain/Behavior system.
  patches/minecraft/net/minecraft/world/entity/Mob.java.patch
  patches/minecraft/net/minecraft/world/entity/ai/behavior/StartAttacking.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/entity/living/LivingChangeTargetEvent.java
  src/main/java/net/minecraftforge/event/entity/living/LivingSetAttackTargetEvent.java
  src/test/java/net/minecraftforge/debug/entity/living/LivingSetAttackTargetEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Triage, LTS Backport, 1.18

#9091 Remove structures slave map to Feature registry
  src/main/java/net/minecraftforge/registries/GameData.java
Labels: Cleanup, Assigned, 1.19

#9087 Use GitHub action to lock issues with the `spam` label
  .github/workflows/spam-label.yml
Labels: Cleanup

#9097 Fix ClientModEvents example not subscribing to client-sided events in the mdk
  mdk/src/main/java/com/example/examplemod/ExampleMod.java
Labels: Bug, Assigned, 1.19
