Repository MinecraftForge/MinecraftForge, pull requests merged in 2022-04, with the labels that each got.

#8527 [1.18.x] Allow using DeferredRegisters for vanilla registries
  patches/minecraft/net/minecraft/core/RegistryAccess.java.patch
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/registries/DeferredRegister.java
  src/main/java/net/minecraftforge/registries/ForgeRegistries.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
  src/main/java/net/minecraftforge/registries/RegistryObject.java
  src/main/java/net/minecraftforge/registries/VanillaRegisterEvent.java
  src/main/resources/META-INF/coremods.json
  src/main/resources/coremods/registry_object_binary_compat.js
  src/test/java/net/minecraftforge/debug/DeferredRegistryTest.java
  src/test/java/net/minecraftforge/debug/RegistryObjectTest.java
Labels: Feature, Assigned, 1.18

#8546 Add ICondition.IContext, fix TagEmptyCondition
  patches/minecraft/net/minecraft/advancements/Advancement.java.patch
  patches/minecraft/net/minecraft/server/ReloadableServerResources.java.patch
  patches/minecraft/net/minecraft/server/ServerAdvancementManager.java.patch
  patches/minecraft/net/minecraft/world/item/crafting/RecipeManager.java.patch
  patches/minecraft/net/minecraft/world/item/crafting/RecipeSerializer.java.patch
  src/generated_test/resources/.cache/cache
  src/generated_test/resources/data/data_gen_test/advancements/recipes/conditional3.json
  src/generated_test/resources/data/data_gen_test/recipes/conditional3.json
  src/main/java/net/minecraftforge/common/crafting/ConditionalAdvancement.java
  src/main/java/net/minecraftforge/common/crafting/ConditionalRecipe.java
  src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java
  src/main/java/net/minecraftforge/common/crafting/conditions/AndCondition.java
  src/main/java/net/minecraftforge/common/crafting/conditions/ConditionContext.java
  src/main/java/net/minecraftforge/common/crafting/conditions/ICondition.java
  src/main/java/net/minecraftforge/common/crafting/conditions/IConditionBuilder.java
  src/main/java/net/minecraftforge/common/crafting/conditions/NotCondition.java
  src/main/java/net/minecraftforge/common/crafting/conditions/OrCondition.java
  src/main/java/net/minecraftforge/common/crafting/conditions/TagEmptyCondition.java
  src/main/java/net/minecraftforge/common/extensions/IForgeRecipeSerializer.java
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
Labels: Bug, Feature, Triage, 1.18

#8508 Implement IPlantable in BambooBlock
  patches/minecraft/net/minecraft/world/level/block/BambooBlock.java.patch
Labels: Feature, Assigned, 1.18

#8543 [1.18.x] Simplfy default behavior of isSimple
  patches/minecraft/net/minecraft/world/item/crafting/Ingredient.java.patch
Labels: Bug, Cleanup, Assigned, 1.18

#8549 Fix return value of Recipe#isIncomplete being inaccurate for empty tags
  patches/minecraft/net/minecraft/world/item/crafting/Recipe.java.patch
  patches/minecraft/net/minecraft/world/item/crafting/ShapedRecipe.java.patch
  patches/minecraft/net/minecraft/world/item/crafting/UpgradeRecipe.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Bug, Triage, 1.18

#8548 [1.18.x] Expose `getHolder()` method on RegistryObject
  patches/minecraft/net/minecraft/core/MappedRegistry.java.patch
  src/main/java/net/minecraftforge/registries/RegistryObject.java
Labels: Feature, Assigned, 1.18

#8406 [1.18.x] [event] add EnderManAngerEvent
  patches/minecraft/net/minecraft/world/entity/monster/EnderMan.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/entity/living/EnderManAngerEvent.java
Labels: Feature, New Event, Assigned, 1.18

#8550 Fix issues with custom forge ingredients causing sub ingredients to be prematurely and invalidly cached
  patches/minecraft/net/minecraft/world/item/crafting/ShapelessRecipe.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/common/crafting/CompoundIngredient.java
  src/main/java/net/minecraftforge/common/crafting/DifferenceIngredient.java
  src/main/java/net/minecraftforge/common/crafting/IntersectionIngredient.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Bug, Triage, 1.18

#8561 Remove bad patch for AbstractFurnaceBlockEntity
  patches/minecraft/net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity.java.patch
Labels: Regression, Cleanup, Triage, 1.18

#8567 Add Gzip support to version checker (partial backport of #8148 from 1.17)
  src/main/java/net/minecraftforge/fml/VersionChecker.java
Labels: Feature, Triage, 1.16, LTS Backport

#8557 [1.18.x] Add use context and simulate flag to getToolModifiedState
  patches/minecraft/net/minecraft/world/item/AxeItem.java.patch
  patches/minecraft/net/minecraft/world/item/HoeItem.java.patch
  patches/minecraft/net/minecraft/world/item/ShovelItem.java.patch
  src/main/java/net/minecraftforge/common/ToolAction.java
  src/main/java/net/minecraftforge/common/ToolActions.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/player/UseHoeEvent.java
  src/main/java/net/minecraftforge/event/world/BlockEvent.java
  src/test/java/net/minecraftforge/debug/block/ToolInteractTest.java
  src/test/java/net/minecraftforge/debug/item/CustomShieldTest.java
Labels: Feature, Assigned, 1.18

#8496 Replace outdated Slider class with a more modern implementation
  src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java
  src/main/java/net/minecraftforge/client/gui/widget/Slider.java
Labels: Feature, Cleanup, Rendering, Triage, 1.18

#8555 Load Modded Dimensions on Dedicated Server Start
  patches/minecraft/net/minecraft/server/Main.java.patch
  src/test/java/net/minecraftforge/debug/world/ServerWorldCreationTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/data/server_world_creation_test/dimension/server_world_creation_test.json
  src/test/resources/data/server_world_creation_test/dimension_type/server_world_creation_test.json
  src/test/resources/data/server_world_creation_test/worldgen/noise_settings/server_world_creation_test_noise.json
Labels: Regression, Assigned, 1.18

#8571 Add event for hooking into StructuresBecomeConfiguredFix
  patches/minecraft/net/minecraft/util/datafix/fixes/StructuresBecomeConfiguredFix.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/RegisterStructureConversionsEvent.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Bug, Triage, 1.18
