Repository MinecraftForge/MinecraftForge, pull requests merged in 2022-08, with the labels that each got.

#8931 [1.19] [HotFix] Fix the dedicated server not having access to the JiJ filesystems.
  build.gradle
  fmlloader/build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
Labels: Bug, Assigned, 1.19

#8919 [1.19] Fix misplaced patch in ItemEntityRenderer breaking ItemEntityRenderer#shouldBob()
  patches/minecraft/net/minecraft/client/renderer/entity/ItemEntityRenderer.java.patch
Labels: Regression, Rendering, Assigned, 1.19

#8712 [1.19] Re-add PotentialSpawns event
  patches/minecraft/net/minecraft/world/level/NaturalSpawner.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/level/LevelEvent.java
  src/test/java/net/minecraftforge/debug/world/PotentialSpawnsEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Regression, Feature, New Event, Assigned, 1.19

#8909 Add an event for when the chunk ticket level is updated
  patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/level/ChunkTicketLevelUpdatedEvent.java
Labels: Feature, New Event, Assigned, 1.19

#8921 [1.19.1]: Let isRemotePresent check minecraft:register for packet ids from other mod loaders.
  src/main/java/net/minecraftforge/network/MCRegisterPacketHandler.java
  src/main/java/net/minecraftforge/network/NetworkHooks.java
  src/main/java/net/minecraftforge/network/NetworkInstance.java
Labels: Feature, Assigned, 1.19

#8892 add Biomes.BEACH to Tags
  src/generated/resources/data/forge/tags/worldgen/biome/is_sandy.json
  src/generated/resources/data/forge/tags/worldgen/biome/is_wet/overworld.json
  src/main/java/net/minecraftforge/common/data/ForgeBiomeTagsProvider.java
Labels: Feature, Assigned, 1.19

#8914 [1.19] Add forge tags for tools and armors
  src/generated/resources/data/forge/tags/items/armors.json
  src/generated/resources/data/forge/tags/items/armors/boots.json
  src/generated/resources/data/forge/tags/items/armors/chestplates.json
  src/generated/resources/data/forge/tags/items/armors/helmets.json
  src/generated/resources/data/forge/tags/items/armors/leggings.json
  src/generated/resources/data/forge/tags/items/tools.json
  src/generated/resources/data/forge/tags/items/tools/axes.json
  src/generated/resources/data/forge/tags/items/tools/bows.json
  src/generated/resources/data/forge/tags/items/tools/crossbows.json
  src/generated/resources/data/forge/tags/items/tools/fishing_rods.json
  src/generated/resources/data/forge/tags/items/tools/hoes.json
  src/generated/resources/data/forge/tags/items/tools/pickaxes.json
  src/generated/resources/data/forge/tags/items/tools/shields.json
  src/generated/resources/data/forge/tags/items/tools/shovels.json
  src/generated/resources/data/forge/tags/items/tools/swords.json
  src/generated/resources/data/forge/tags/items/tools/tridents.json
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeItemTagsProvider.java
Labels: Feature, Assigned, 1.19

#8927 Remove calls to getStepHeight in Player#maybeBackOffFromEdge
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
Labels: Bug, Assigned, 1.19

#8944 [1.18.x] Backport: Re-add PotentialSpawns event
  patches/minecraft/net/minecraft/world/level/NaturalSpawner.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/world/WorldEvent.java
  src/test/java/net/minecraftforge/debug/world/PotentialSpawnsEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Regression, Feature, New Event, Assigned, LTS Backport, 1.18

#8868 [1.18.x] Cache resource listing calls in resource packs
  patches/minecraft/net/minecraft/server/packs/VanillaPackResources.java.patch
  patches/minecraft/net/minecraft/server/packs/resources/FallbackResourceManager.java.patch
  patches/minecraft/net/minecraft/server/packs/resources/MultiPackResourceManager.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/common/extensions/IForgePackResources.java
  src/main/java/net/minecraftforge/resource/DelegatingResourcePack.java
  src/main/java/net/minecraftforge/resource/PathResourcePack.java
  src/main/java/net/minecraftforge/resource/ResourceCacheManager.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/main/resources/assets/forge/lang/en_us.json
Labels: Performance, Feature, Assigned, LTS Backport, 1.18

#8350 Load custom ITransformationServices from the classpath in dev
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ClasspathLocatorUtils.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ClasspathTransformerDiscoverer.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ClasspathLocator.java
  fmlloader/src/main/resources/META-INF/services/cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService
Labels: Feature, Assigned, LTS Backport, 1.18

#8925 Fix certain particles not updating their bounding box when their position changes
  patches/minecraft/net/minecraft/client/particle/EnchantmentTableParticle.java.patch
  patches/minecraft/net/minecraft/client/particle/PortalParticle.java.patch
  patches/minecraft/net/minecraft/client/particle/ReversePortalParticle.java.patch
  patches/minecraft/net/minecraft/client/particle/VibrationSignalParticle.java.patch
Labels: Bug, Rendering, Assigned, 1.19

#8928 [1.19.x] Custom Holderset Types
  patches/minecraft/net/minecraft/core/HolderSet.java.patch
  patches/minecraft/net/minecraft/resources/HolderSetCodec.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/extensions/IForgeHolderSet.java
  src/main/java/net/minecraftforge/registries/ForgeDeferredRegistriesSetup.java
  src/main/java/net/minecraftforge/registries/ForgeRegistries.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/holdersets/AndHolderSet.java
  src/main/java/net/minecraftforge/registries/holdersets/AnyHolderSet.java
  src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java
  src/main/java/net/minecraftforge/registries/holdersets/HolderSetType.java
  src/main/java/net/minecraftforge/registries/holdersets/ICustomHolderSet.java
  src/main/java/net/minecraftforge/registries/holdersets/NotHolderSet.java
  src/main/java/net/minecraftforge/registries/holdersets/OrHolderSet.java
Labels: Feature, Assigned, 1.19

#8933 `LivingEntity#isBlocking` use `ToolActions#SHIELD_BLOCK` instead of `UseAnim#BLOCK`
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
Labels: Feature, Assigned, 1.19

#8905 AnvilUpdateEvent fix
  patches/minecraft/net/minecraft/world/inventory/AnvilMenu.java.patch
  src/main/java/net/minecraftforge/event/AnvilUpdateEvent.java
  src/test/java/net/minecraftforge/debug/misc/AnvilUpdateEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Assigned, 1.19

#8945 Fix comments and documentation that were missed during the review of …
  src/main/java/net/minecraftforge/event/level/LevelEvent.java
  src/test/java/net/minecraftforge/debug/world/PotentialSpawnsEventTest.java
Labels: Cleanup, Assigned, 1.19

#8959 Fix worlds with removed dimension types unable to load.
  patches/minecraft/net/minecraft/resources/RegistryLoader.java.patch
  patches/minecraft/net/minecraft/world/level/storage/LevelStorageSource.java.patch
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Bug, Triage, 1.19

#8967 [HotFix] Fix a corner case where the UMLB can not extract a version from a library.
  fmlloader/src/main/java/net/minecraftforge/fml/loading/UniqueModListBuilder.java
Labels: Bug, Triage, 1.19

#8973 Remove reflective implementation of ICustomPacket.
  patches/minecraft/net/minecraft/network/protocol/game/ClientboundCustomPayloadPacket.java.patch
  patches/minecraft/net/minecraft/network/protocol/game/ServerboundCustomPayloadPacket.java.patch
  patches/minecraft/net/minecraft/network/protocol/login/ClientboundCustomQueryPacket.java.patch
  patches/minecraft/net/minecraft/network/protocol/login/ServerboundCustomQueryPacket.java.patch
  src/main/java/net/minecraftforge/network/ICustomPacket.java
  src/main/java/net/minecraftforge/network/LoginWrapper.java
  src/main/java/net/minecraftforge/network/NetworkDirection.java
  src/main/java/net/minecraftforge/network/simple/IndexedMessageCodec.java
Labels: Bug, BreakingChange, Cleanup, Triage, 1.19

#8948 Fix Enchantment#doPostHurt and Enchantment#doPostAttack being called twice for players
  patches/minecraft/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch
Labels: Vanilla Bug, Assigned, 1.19

#8951 Modify ScreenEvent.RenderInventoryMobEffects to allow shifting the effect stack
  patches/minecraft/net/minecraft/client/gui/screens/inventory/EffectRenderingInventoryScreen.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/ScreenEvent.java
  src/test/java/net/minecraftforge/debug/client/PotionSizeEventTest.java
Labels: Feature, Rendering, Assigned, 1.19

#8952 Add cancellable event firing when Toasts are added (1.19)
  patches/minecraft/net/minecraft/client/gui/components/toasts/ToastComponent.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/ToastAddEvent.java
Labels: Feature, New Event, Assigned, 1.19

#8961 Add alternate version of renderEntityInInventory to allow for directly specifying the angles
  patches/minecraft/net/minecraft/client/gui/screens/inventory/InventoryScreen.java.patch
  src/main/resources/forge.exc
Labels: Feature, Rendering, Assigned, 1.19

#8963 Allow FakePlayer to report its position
  src/main/java/net/minecraftforge/common/util/FakePlayer.java
Labels: Feature, Assigned, 1.19

#8947 Redirect checks for entity selector use to a permission
  patches/minecraft/net/minecraft/commands/arguments/EntityArgument.java.patch
  patches/minecraft/net/minecraft/commands/arguments/MessageArgument.java.patch
  patches/minecraft/net/minecraft/commands/arguments/selector/EntitySelector.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/ForgeMod.java
Labels: Feature, Assigned, 1.19

#8938 [1.19] Allow custom outline rendering on EntityRenderers and BlockEntityRenderers
  patches/minecraft/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockEntity.java
  src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Feature, Rendering, Assigned, 1.19

#8880 Allow registering custom `ColorResolver`s
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/multiplayer/ClientLevel.java.patch
  src/main/java/net/minecraftforge/client/ColorResolverManager.java
  src/main/java/net/minecraftforge/client/event/RegisterColorHandlersEvent.java
  src/test/java/net/minecraftforge/debug/client/CustomColorResolverTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/custom_color_resolver_test/blockstates/test_block.json
  src/test/resources/assets/custom_color_resolver_test/models/block/block.json
Labels: Feature, Rendering, Assigned, 1.19

#8932 [1.19.x] Custom usage animations for items
  patches/minecraft/net/minecraft/client/model/HumanoidModel.java.patch
  patches/minecraft/net/minecraft/client/renderer/ItemInHandRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/player/PlayerRenderer.java.patch
  patches/minecraft/net/minecraft/world/item/UseAnim.java.patch
  src/main/java/net/minecraftforge/client/IArmPoseTransformer.java
  src/main/java/net/minecraftforge/client/extensions/common/IClientItemExtensions.java
  src/test/java/net/minecraftforge/debug/entity/player/ItemUseAnimationTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Rendering, Assigned, 1.19

#8794 Added ItemDecorator Map
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/renderer/entity/ItemRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/IItemDecorator.java
  src/main/java/net/minecraftforge/client/ItemDecoratorHandler.java
  src/main/java/net/minecraftforge/client/event/RegisterItemDecorationsEvent.java
  src/test/java/net/minecraftforge/debug/client/rendering/CustomItemDecorationsTest.java
Labels: Feature, Rendering, Assigned, 1.19

#8972 Add ability to Auto register capabilities via annotation
  lowcodelanguage/src/main/java/net/minecraftforge/fml/lowcodemod/LowCodeModLanguageProvider.java
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/horse/AbstractHorse.java.patch
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  patches/minecraft/net/minecraft/world/entity/vehicle/AbstractMinecartContainer.java.patch
  patches/minecraft/net/minecraft/world/entity/vehicle/ChestBoat.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/BaseContainerBlockEntity.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/BrewingStandBlockEntity.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/ChestBlockEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/capabilities/AutoRegisterCapability.java
  src/main/java/net/minecraftforge/common/capabilities/CapabilityManager.java
  src/main/java/net/minecraftforge/common/capabilities/CapabilityProvider.java
  src/main/java/net/minecraftforge/common/capabilities/ForgeCapabilities.java
  src/main/java/net/minecraftforge/common/capabilities/ICapabilityProviderImpl.java
  src/main/java/net/minecraftforge/energy/CapabilityEnergy.java
  src/main/java/net/minecraftforge/energy/IEnergyStorage.java
  src/main/java/net/minecraftforge/fluids/FluidUtil.java
  src/main/java/net/minecraftforge/fluids/capability/CapabilityFluidHandler.java
  src/main/java/net/minecraftforge/fluids/capability/FluidHandlerBlockEntity.java
  src/main/java/net/minecraftforge/fluids/capability/IFluidHandler.java
  src/main/java/net/minecraftforge/fluids/capability/IFluidHandlerItem.java
  src/main/java/net/minecraftforge/fluids/capability/templates/FluidHandlerItemStack.java
  src/main/java/net/minecraftforge/fluids/capability/templates/FluidHandlerItemStackSimple.java
  src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBucketWrapper.java
  src/main/java/net/minecraftforge/items/CapabilityItemHandler.java
  src/main/java/net/minecraftforge/items/IItemHandler.java
  src/main/java/net/minecraftforge/items/VanillaInventoryCodeHooks.java
  src/test/java/net/minecraftforge/debug/misc/GameTestTest.java
Labels: Feature, Capabilities, Assigned, 1.19

#8987 Hotfix for 1.19.2 item animation bug
  patches/minecraft/net/minecraft/client/model/HumanoidModel.java.patch
  src/test/java/net/minecraftforge/debug/entity/player/ItemUseAnimationTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Rendering, Assigned, 1.19

#8995 Fix entity selector permission check to check original source
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Bug, Triage, 1.19

#8996 [1.18] Fix circular dependency in static init of RecipeBookRegistry
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  src/main/java/net/minecraftforge/client/RecipeBookRegistry.java
Labels: Bug, Assigned, 1.18
