Repository MinecraftForge/MinecraftForge, pull requests merged in 2022-11, with the labels that each got.

#9115 Add missing semi-colon near the Dist import statement.
  mdk/src/main/java/com/example/examplemod/ExampleMod.java
Labels: Bug, Assigned, 1.19

#9111 Throw aggregate exception for erroneous registry event dispatch
  src/main/java/net/minecraftforge/registries/GameData.java
Labels: Bug, Assigned, 1.19

#9135 [1.19.x] Add HitResult to `EntityTeleportEvent$EnderPearl`
  patches/minecraft/net/minecraft/world/entity/projectile/ThrownEnderpearl.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/EntityTeleportEvent.java
Labels: Feature, Assigned, Triage, 1.19

#9120 Fix launch handler minecraft classpath locator
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FileUtils.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonDevLaunchHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonUserdevLaunchHandler.java
Labels: Bug, Assigned, 1.19

#9130 [1.19] Improve extensibility of DetectorRailBlock and PoweredRailBlock
  patches/minecraft/net/minecraft/world/level/block/BaseRailBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/DetectorRailBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/PoweredRailBlock.java.patch
  src/main/resources/forge.exc
Labels: Feature, Assigned, 1.19

#9108 [1.18] Improve logging of missing or unsupported dependencies
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java
Labels: Feature, Assigned, LTS Backport, 1.18

#9157 [1.19.x] Fix invalidated modded packets when on LAN
  patches/minecraft/net/minecraft/network/protocol/game/ClientboundCustomPayloadPacket.java.patch
Labels: Bug, Triage, 1.19

#9066 Add simple block appearance API
  patches/minecraft/net/minecraft/client/renderer/chunk/RenderChunkRegion.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
Labels: Feature, Rendering, 1.19, hacktoberfest-accepted

#9065 Rendering tweaks and fixes: Part 4
  patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/model/BlockModel.java.patch
  src/main/java/net/minecraftforge/client/model/CompositeModel.java
  src/main/java/net/minecraftforge/client/model/ElementsModel.java
  src/main/java/net/minecraftforge/client/model/QuadTransformers.java
  src/main/java/net/minecraftforge/client/model/geometry/UnbakedGeometryHelper.java
  src/main/java/net/minecraftforge/client/model/obj/ObjModel.java
  src/main/java/net/minecraftforge/client/model/pipeline/QuadBakingVertexConsumer.java
  src/test/java/net/minecraftforge/debug/client/model/NewModelLoaderTest.java
Labels: Bug, Feature, Cleanup, Rendering, Assigned, 1.19, hacktoberfest-accepted

#9155 Make `Util.memoize` thread-safe
  patches/minecraft/net/minecraft/Util.java.patch
Labels: Vanilla Bug, Assigned, 1.19

#9163 [1.19.2] Call baked model's `getModelData` before `getRenderTypes`
  patches/minecraft/net/minecraft/client/renderer/block/BlockRenderDispatcher.java.patch
  patches/minecraft/net/minecraft/client/renderer/block/ModelBlockRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/chunk/ChunkRenderDispatcher.java.patch
  src/main/resources/forge.exc
Labels: Bug, Rendering, Assigned, 1.19

#9089 [1.19] Fix several bugs in the original grindstone PR related to canceling the event
  patches/minecraft/net/minecraft/world/inventory/GrindstoneMenu.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/GrindstoneEvent.java
  src/test/java/net/minecraftforge/debug/misc/GrindstoneEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Assigned, 1.19

#9139 [1.19.x] Add supplier to FlowerBlock so it works with custom MobEffects
  patches/minecraft/net/minecraft/world/level/block/FlowerBlock.java.patch
  src/main/resources/forge.exc
Labels: Feature, Assigned, 1.19

#9142 [1.19.x] BaseFireBlock.java.patch to use IForgeBlockState#isPortalFrame
  patches/minecraft/net/minecraft/world/level/block/BaseFireBlock.java.patch
Labels: Regression, Assigned, 1.19

#9147 Check source permission level before selector permission
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Bug, Assigned, 1.19

#9160 [1.18] Enable additional build types to handle pull request validation.
  .teamcity/settings.kts
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/DownloadBaseCompatibilityBinPatches.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/MergeJars.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/SetupCheckJarCompatibility.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/Util.groovy
  gradle/wrapper/gradle-wrapper.properties
Labels: Cleanup, Assigned, 1.18

#9113 [1.19.2] Make Datapack Registries support ICondition(s)
  patches/minecraft/net/minecraft/resources/RegistryLoader.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java
  src/main/java/net/minecraftforge/common/crafting/conditions/ICondition.java
  src/main/java/net/minecraftforge/common/data/JsonCodecProvider.java
  src/test/java/net/minecraftforge/debug/world/BiomeModifierTest.java
  src/test/resources/data/forge/forge/biome_modifier/test_datapackreg_conditions.json
  src/test/resources/data/forge/forge/biome_modifier/test_datapackreg_conditions_error.json
Labels: Feature, Assigned, 1.19

#9143 Add support for discovering modular services
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ModDirTransformerDiscoverer.java
Labels: Bug, Assigned, 1.19
