Repository MinecraftForge/MinecraftForge, pull requests merged in 2023-11, with the labels that each got.

#9768 [1.20.x] Improve mod description formatting in mods screen
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  src/main/resources/META-INF/mods.toml
Labels: Assigned, 1.20

#9769 [1.20.1] Improve mod description formatting in mods screen
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  src/main/resources/META-INF/mods.toml
Labels: Triage, 1.20

#9752 [1.20.1] Minor MDK changes
  mdk/README.txt
  mdk/settings.gradle
  settings.gradle
Labels: Assigned, 1.20

#9757 [1.20.1] CrashReportAnalyser
  patches/minecraft/net/minecraft/CrashReport.java.patch
  src/main/java/net/minecraftforge/logging/CrashReportAnalyser.java
Labels: Assigned, 1.20

#9770 [1.19.x] Improve mod description formatting in mods screen
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  src/main/resources/META-INF/mods.toml
Labels: Triage, LTS, 1.19

#9756 [1.19.4] CrashReportAnalyser
  patches/minecraft/net/minecraft/CrashReport.java.patch
  src/main/java/net/minecraftforge/logging/CrashReportAnalyser.java
Labels: Assigned, LTS, 1.19

#9758 [1.19.2] CrashReportAnalyser
  patches/minecraft/net/minecraft/CrashReport.java.patch
  src/main/java/net/minecraftforge/logging/CrashReportAnalyser.java
Labels: Assigned, LTS, 1.19

#9771 [1.19.2] Improve mod description formatting in mods screen
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  src/main/resources/META-INF/mods.toml
Labels: Triage, LTS, 1.19

#9754 [1.19.2] Update to FG6 and Gradle 8, backport 1.20 MDK
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/BytecodeFinder.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/Util.groovy
  gradle/wrapper/gradle-wrapper.properties
  mdk/README.txt
  mdk/build.gradle
  mdk/gradle.properties
  mdk/settings.gradle
  mdk/src/main/java/com/example/examplemod/Config.java
  mdk/src/main/java/com/example/examplemod/ExampleMod.java
  mdk/src/main/resources/META-INF/mods.toml
  mdk/src/main/resources/pack.mcmeta
  settings.gradle
Labels: Assigned, LTS, 1.19

#9759 [1.18.2] CrashReportAnalyser
  patches/minecraft/net/minecraft/CrashReport.java.patch
  src/main/java/net/minecraftforge/logging/CrashReportAnalyser.java
Labels: Assigned, LTS, 1.18

#9755 [1.18.x] Minor MDK changes
  mdk/README.txt
Labels: Assigned, LTS, 1.18, Trivial

#9688 Invalidate Ingredients on tags update, make getItems() check ingredient invalidation
  patches/minecraft/net/minecraft/world/item/crafting/Ingredient.java.patch
  src/main/java/net/minecraftforge/common/ForgeMod.java
Labels: Triage, 1.20

#9778 Gradle 8.4
  build.gradle
  build_clean.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  mdk/build.gradle
Labels: Triage, 1.20

#9767 Fix texture UV values for obj models. Closes #9737
  src/main/java/net/minecraftforge/client/model/obj/ObjModel.java
  src/main/java/net/minecraftforge/client/textures/UnitTextureAtlasSprite.java
Labels: Assigned, 1.20

#9790 Update/fix ChunkWatchEvent to match their docs, and clean docs a little
  patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch
  patches/minecraft/net/minecraft/server/network/PlayerChunkSender.java.patch
  src/main/java/net/minecraftforge/event/level/ChunkWatchEvent.java
Labels: Triage, 1.20

#9798 [1.20.x] Fix rare crash with early display window, fixes #9673
  build.gradle
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
Labels: Assigned, 1.20

#9799 [1.20.1] Fix rare crash with early display window, fixes #9673
  build.gradle
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
Labels: Assigned, 1.20

#9800 [1.20.x] Don't turn off VSync when rendering from Minecraft context
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
Labels: Triage, 1.20

#9801 [1.20.1] Don't turn off VSync when rendering from Minecraft context
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
Labels: Triage, 1.20

#9807 addOptionalTag/s methods that allow passing the TagKey itself instead of passing the location
  src/main/java/net/minecraftforge/common/extensions/IForgeTagAppender.java
Labels: Triage, 1.20
