Repository MinecraftForge/MinecraftForge, pull requests merged in 2023-10, with the labels that each got.

#9747 Fix Melon/Pumpkin stems remain after trampling the farmland, produce …
  src/main/java/net/minecraftforge/common/IPlantable.java
Labels: Assigned, LTS, 1.19

#9732 CrashReportAnalyser that tries to identify the mod that crashed the game, implements #9717
  patches/minecraft/net/minecraft/CrashReport.java.patch
  src/main/java/net/minecraftforge/logging/CrashReportAnalyser.java
Labels: Assigned, 1.20

#9751 [1.20.x] Improve mod loading error message for errors inside mod constructors
  javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
Labels: Assigned, 1.20

#9750 [1.20.x] Minor MDK changes
  mdk/README.txt
  mdk/settings.gradle
  settings.gradle
Labels: Assigned, 1.20

#9749 Optimise registries
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
  src/main/java/net/minecraftforge/registries/GameData.java
Labels: Performance, BreakingChange, Triage, 1.20

#9753 [1.19.x] Update to FG6 and Gradle 8, backport 1.20 MDK
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/BytecodeFinder.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/TeamcityRequests.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/Util.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckTask.groovy
  gradle/wrapper/gradle-wrapper.properties
  mdk/README.txt
  mdk/build.gradle
  mdk/gradle.properties
  mdk/settings.gradle
  mdk/src/main/java/com/example/examplemod/Config.java
  mdk/src/main/java/com/example/examplemod/ExampleMod.java
  mdk/src/main/resources/META-INF/mods.toml
  settings.gradle
  src/generated_mdk/resources/pack.mcmeta
  src/test/java/net/minecraftforge/mdk/MdkDatagen.java
Labels: Assigned, LTS, 1.19
