Repository MinecraftForge/MinecraftForge, pull requests merged in 2023-06, with the labels that each got.

#9235 [1.18.2] Add new helper without duplicate neighbor update call
  patches/minecraft/net/minecraft/world/inventory/BeaconMenu.java.patch
  patches/minecraft/net/minecraft/world/level/Level.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/BlockEntity.java.patch
  src/main/resources/forge.exc
Labels: Bug, Triage, LTS, 1.18

#9520 Fix erroneous getLevel call when firing SpecialSpawn
  patches/minecraft/net/minecraft/world/entity/monster/Strider.java.patch
  patches/minecraft/net/minecraft/world/level/BaseSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/NaturalSpawner.java.patch
Labels: Bug, LTS, 1.19

#9521 [1.20] Fix duplicate Map writes
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
Labels: Assigned, 1.20

#9528 Fix `getArmorModelHook` patch
  patches/minecraft/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch
  src/main/resources/forge.exc
Labels: Bug, Rendering, Assigned, 1.20

#9530 [1.20.x] Use Spinning Effect Intensity instead of Partial Tick for Portal Overlay
  src/main/java/net/minecraftforge/client/gui/overlay/VanillaGuiOverlay.java
Labels: Bug, Rendering, Assigned, 1.20

#9531 [1.20.x] Move #initCapabilities back to the constructor in ServerLevel
  patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch
Labels: Bug, Assigned, 1.20

#9539 [1.20] Fix incorrect depth test state in debug graph rendering
  src/main/java/net/minecraftforge/client/gui/overlay/ForgeGui.java
Labels: Bug, Assigned, 1.20

#9544 [1.20] fix wrong variable passed into enchantmentclue lookup
  patches/minecraft/net/minecraft/client/gui/screens/inventory/EnchantmentScreen.java.patch
Labels: Bug, Assigned, 1.20

#9537 [1.20] Fix issues in the deserialization of empty ingredients
  src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java
  src/main/java/net/minecraftforge/common/crafting/DifferenceIngredient.java
  src/main/java/net/minecraftforge/common/crafting/IntersectionIngredient.java
Labels: Assigned, 1.20

#9536 [1.20] Re-implement missing level-sensitive block light hook in ChunkAccess
  patches/minecraft/net/minecraft/world/level/chunk/ChunkAccess.java.patch
  patches/minecraft/net/minecraft/world/level/chunk/ImposterProtoChunk.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
  src/main/resources/forge.exc
  src/test/java/net/minecraftforge/debug/block/LevelSensitiveLightBlockTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/level_sensitive_light_block_test/blockstates/light_block.json
  src/test/resources/assets/level_sensitive_light_block_test/models/item/light_block.json
Labels: Assigned, 1.20

#9550 [1.20.x] Reorder Gui Overlay Layers to Match Vanilla
  src/main/java/net/minecraftforge/client/gui/overlay/VanillaGuiOverlay.java
Labels: Bug, Triage, 1.20

#9555 [1.20] Add `AFTER_LEVEL` render level stage
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/minecraft/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/minecraftforge/client/event/RenderLevelStageEvent.java
Labels: Assigned, 1.20

#9556 [1.20] Fix JAR compatibility checks
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/TeamcityRequests.groovy
Labels: Assigned, 1.20

#9547 [1.20.x] Update Armor Layer Implementation to Match Vanilla
  patches/minecraft/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch
  src/main/resources/forge.exc
Labels: Bug, Triage, 1.20

#9575 Make the scheduled thread factory setDaemon on it's threads.
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
Labels: Triage, 1.20

#9572 Fix custom geometry in parent models not being resolved
  patches/minecraft/net/minecraft/client/renderer/block/model/BlockModel.java.patch
Labels: Rendering, Triage, 1.20

#9574 Make IItemDecorator a functional interface again
  src/main/java/net/minecraftforge/client/IItemDecorator.java
Labels: Assigned, 1.20

#9566 Fix forge registries not being accessible in GatherDataEvent's HolderLookup
  src/main/java/net/minecraftforge/data/loading/DatagenModLoader.java
Labels: Bug, Confirmed, Assigned, 1.20

#9553 [1.20] Add missing calls to level-sensitive block SoundType getter
  patches/minecraft/net/minecraft/world/entity/Entity.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/camel/Camel.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/sniffer/Sniffer.java.patch
Labels: Bug, Assigned, 1.20

#9538 [1.20] make piston push reaction overridable in the block again
  patches/minecraft/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
Labels: Assigned, 1.20

#9474 Log a proper duplicate mod(s) error message
  fmlloader/src/main/java/net/minecraftforge/fml/loading/UniqueModListBuilder.java
Labels: Bug, Assigned, 1.19

#9577 Update default configs to match standard expectations.
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLConfig.java
Labels: Assigned, 1.20

#9585 More tweaks to the mod loading callbacks to make loading bars work better
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModWorkManager.java
  fmlcore/src/main/java/net/minecraftforge/fml/StartupMessageManager.java
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/RenderElement.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLConfig.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ImmediateWindowHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/progress/StartupNotificationManager.java
  fmlloader/src/main/resources/META-INF/defaultfmlconfig.toml
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
  src/main/java/net/minecraftforge/client/loading/ForgeLoadingOverlay.java
  src/main/java/net/minecraftforge/client/loading/NoVizFallback.java
Labels: Triage, 1.20

#9591 Auto generate names for modded loot pools. Fixes #9589
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Triage, 1.20

#9595 Timer to try and fix possible hangs on early window creation
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLConfig.java
Labels: Triage, 1.20

#9469 [1.20] Add events for checking spawn conditions (SpawnPlacementCheck and PositionCheck)
  patches/minecraft/net/minecraft/util/SpawnUtil.java.patch
  patches/minecraft/net/minecraft/world/entity/SpawnPlacements.java.patch
  patches/minecraft/net/minecraft/world/level/BaseSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/NaturalSpawner.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java
Labels: Feature, New Event, Assigned, 1.19, Queued

#9562 Expose EntityRendererProvider.Context to AddLayers event
  patches/minecraft/net/minecraft/client/renderer/entity/EntityRenderDispatcher.java.patch
  src/main/java/net/minecraftforge/client/event/EntityRenderersEvent.java
Labels: Rendering, Assigned, 1.20, Queued

#9564 Fix SpriteCoordinateExpander not working with chained methods
  patches/minecraft/net/minecraft/client/renderer/SpriteCoordinateExpander.java.patch
Labels: Vanilla Bug, Rendering, Assigned, 1.20, Queued

#9568 [1.20] Fix gametest collection potentially causing secondary crash in loading error state
  src/main/java/net/minecraftforge/gametest/ForgeGameTestHooks.java
Labels: Assigned, 1.20, Queued

#9580 Expose holder lookup registry provider as a helper in RegistriesDatapackGenerator
  patches/minecraft/net/minecraft/data/registries/RegistriesDatapackGenerator.java.patch
Labels: Assigned, 1.20, Queued

#9581 Add missing damage type tag provider modid, existing file helper constructor overload
  patches/minecraft/net/minecraft/data/tags/DamageTypeTagsProvider.java.patch
  src/main/resources/forge.exc
Labels: Assigned, 1.20, Queued

#9583 Fix ignoring maxUpStep method overrides on entities
  patches/minecraft/net/minecraft/world/entity/Entity.java.patch
  patches/minecraft/net/minecraft/world/level/pathfinder/WalkNodeEvaluator.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Bug, BreakingChange, Assigned, 1.20, Queued

#9587 [1.20.x] Item Handler capability for Chiseled Bookshelf
  patches/minecraft/net/minecraft/world/level/block/entity/ChiseledBookShelfBlockEntity.java.patch
Labels: Assigned, 1.20, Queued

#9588 Fix not dropping xp for player sourced explosions and various other cases when xp should drop
  patches/minecraft/net/minecraft/world/level/block/Block.java.patch
  patches/minecraft/net/minecraft/world/level/block/state/BlockBehaviour.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/resources/forge.exc
Labels: Bug, Assigned, 1.20, Queued

#9592 [1.20.x] Lazily configure MDK tasks, improve IDE support
  mdk/build.gradle
Labels: Assigned, 1.20, Queued

#9593 [1.20.x] Reduce verbosity of prepareRuns doc in MDK
  mdk/build.gradle
Labels: Assigned, 1.20, Queued

#9594 [1.20.x] Demonstrate `configureEach` in run configs
  mdk/build.gradle
Labels: Assigned, 1.20, Queued

#9596 [1.20.x] Add example usage for configs to the MDK
  mdk/src/main/java/com/example/examplemod/Config.java
  mdk/src/main/java/com/example/examplemod/ExampleMod.java
Labels: Assigned, 1.20, Queued

#9602 Remove amount from FluidStack hashCode to fix the equal/hashCode java contract
  src/main/java/net/minecraftforge/fluids/FluidStack.java
  src/test/java/net/minecraftforge/debug/CodecsTest.java
Labels: Assigned, 1.20, Queued

#9606 Try and be a bit nicer about handling bad [feature] definitions
  build.gradle
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/MinecraftLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFileInfo.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFileParser.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/NightConfigWrapper.java
  mdk/src/main/resources/META-INF/mods.toml
  src/main/java/net/minecraftforge/common/ForgeI18n.java
  src/main/java/net/minecraftforge/common/util/MavenVersionStringHelper.java
  src/main/resources/META-INF/mods.toml
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.20
