Repository MinecraftForge/MinecraftForge, pull requests merged in 2023-03, with the labels that each got.

#9343 [1.19.3] Add onStopUsing hook to IForgeItem
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
  src/test/java/net/minecraftforge/debug/item/StopUsingItemTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.19

#9344 [1.19.3] Fix continuing to use items after dropping or when a shield breaks (MC-231097, MC-168573)
  patches/minecraft/net/minecraft/client/player/LocalPlayer.java.patch
  patches/minecraft/net/minecraft/server/level/ServerPlayer.java.patch
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
Labels: Vanilla Bug, Assigned, 1.19

#9375 Fix experimental warning screen appearing everytime a world is created or opened
  patches/minecraft/net/minecraft/core/registries/BuiltInRegistries.java.patch
  src/main/java/net/minecraftforge/registries/NamespacedWrapper.java
Labels: Bug, Assigned, 1.19

#9381 Fix mobs not always taking damage
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
Labels: Bug, Assigned, 1.19

#9338 [1.19.2] Fix StemBlock patch, backport StemGrownBlock patch
  patches/minecraft/net/minecraft/world/level/block/StemBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/StemGrownBlock.java.patch
Labels: Bug, Assigned, LTS Backport, 1.19

#9387 Fix wrong parameters in `Screen#renderTooltipInternal` patch
  patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch
Labels: Bug, Rendering, Triage, 1.19

#9391 [1.19.4] Fix misaligned text render type patch
  patches/minecraft/net/minecraft/client/renderer/RenderType.java.patch
Labels: Triage, 1.19

#9398 Fixed ModMismatchDisconnectedScreen displaying missing mods wrongly
  src/main/java/net/minecraftforge/client/gui/ModMismatchDisconnectedScreen.java
Labels: Bug, Assigned, 1.19

#9401 Fix incorrect boolean used for glint effect
  patches/minecraft/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch
Labels: Bug, Rendering, Triage, 1.19

#9403 Fix incorrect variable used for swimming check
  patches/minecraft/net/minecraft/client/player/LocalPlayer.java.patch
Labels: Bug, Assigned, 1.19

#9402 Fix hardcoded precipitation in ClimateSettingsBuilder
  src/main/java/net/minecraftforge/common/world/ClimateSettingsBuilder.java
Labels: Bug, Triage, 1.19

#9348 Remove DistExecutor calls in PistonEventTest
  src/test/java/net/minecraftforge/debug/block/PistonEventTest.java
Labels: Cleanup, Assigned, 1.19

#9369 Add `ChunkEvent.Load#isNewChunk`
  patches/minecraft/net/minecraft/client/multiplayer/ClientChunkCache.java.patch
  patches/minecraft/net/minecraft/server/level/ChunkMap.java.patch
  src/main/java/net/minecraftforge/event/level/ChunkEvent.java
  src/test/java/net/minecraftforge/debug/world/ChunkEventLoadNewChunkTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.19

#9372 [1.19.3] Add option to completely hide a crash-callable depending on a runtime value
  fmlcore/src/main/java/net/minecraftforge/fml/CrashReportCallables.java
  fmlcore/src/main/java/net/minecraftforge/fml/ISystemReportExtender.java
  src/main/java/net/minecraftforge/logging/CrashReportExtender.java
  src/test/java/net/minecraftforge/debug/CrashCallableTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.19

#9386 [1.19.4] Add BlockSetType#register to accesstransformer.cfg to make public
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Feature, Assigned, 1.19

#9406 Make ForgeSlider use the new vanilla texture
  src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Bug, Rendering, Assigned, 1.19

#9407 [1.19.4] Fix infinite BE render bounds failing frustum intersection test
  patches/minecraft/net/minecraft/client/renderer/culling/Frustum.java.patch
Labels: Regression, Rendering, Assigned, 1.19

#9404 [1.19.4] Rebuild ItemEntity patch
  patches/minecraft/net/minecraft/world/entity/item/ItemEntity.java.patch
Labels: Bug, Cleanup, Triage, 1.19

#9133 [1.19.4+] Revamp and fix spawn events
  build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/BytecodePredicateFinder.groovy
  patches/minecraft/net/minecraft/world/entity/EntityType.java.patch
  patches/minecraft/net/minecraft/world/entity/Mob.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/CatSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/BaseSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/NaturalSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/PatrolSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/ForgeInternalHandler.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/living/LivingSpawnEvent.java
  src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java
  src/main/resources/META-INF/coremods.json
  src/main/resources/coremods/finalize_spawn_targets.json
  src/main/resources/coremods/method_redirector.js
  src/test/java/net/minecraftforge/debug/entity/CheckSpawnEventTest.java
Labels: Bug, Feature, BreakingChange, Cleanup, Triage, 1.19

#9414 Update pack versions
  mdk/src/main/resources/pack.mcmeta
  src/main/resources/pack.mcmeta
  src/test/resources/pack.mcmeta
Labels: Bug, Assigned, 1.19

#9388 Rename RegisterParticleProviderEvent's register methods to describe what kind of particle providers they register (deprecating old methods to avoid breaking) and minor docs tweaks
  src/main/java/net/minecraftforge/client/event/RegisterParticleProvidersEvent.java
Labels: Feature, Cleanup, Assigned, 1.19

#9424 Remove duplicate line in FoodData patch
  patches/minecraft/net/minecraft/world/food/FoodData.java.patch
Labels: Bug, Assigned, 1.19

#9377 [1.19.4] Restore ability to change message in ClientChatEvent
  src/main/java/net/minecraftforge/client/event/ClientChatEvent.java
  src/test/java/net/minecraftforge/debug/chat/ClientChatEventTest.java
Labels: Triage, 1.19

#9421 Loosen access for BucketItem's canBlockContainFluid
  patches/minecraft/net/minecraft/world/item/BucketItem.java.patch
Labels: Feature, Fluids, Assigned, 1.19

#9420 Fix FinalizeSpawn not blocking spawns during worldgen
  patches/minecraft/net/minecraft/server/level/WorldGenRegion.java.patch
  src/main/java/net/minecraftforge/event/entity/living/MobSpawnEvent.java
Labels: Bug, Confirmed, Assigned, 1.19

#9431 Fix ScreenEvent.Init.[Pre/Post] not working correctly
  patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch
Labels: Bug, Triage, 1.19

#9432 [1.19.x] Add default bucket sounds for milk
  src/generated/resources/assets/minecraft/sounds.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/data/VanillaSoundDefinitionsProvider.java
Labels: Bug, Fluids, Triage, 1.19

#9361 [1.19.x] Remove Attack Range and Reach Distance and add Block Reach and Entity Reach
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/gui/Gui.java.patch
  patches/minecraft/net/minecraft/client/multiplayer/MultiPlayerGameMode.java.patch
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
  patches/minecraft/net/minecraft/server/level/ServerPlayerGameMode.java.patch
  patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  patches/minecraft/net/minecraft/world/item/Item.java.patch
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/extensions/IForgePlayer.java
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.19

#9367 [1.19.x] Split the login packet
  patches/minecraft/net/minecraft/network/CompressionEncoder.java.patch
  src/main/java/net/minecraftforge/network/filters/ForgeConnectionNetworkFilter.java
  src/main/java/net/minecraftforge/network/filters/VanillaPacketSplitter.java
  src/test/java/net/minecraftforge/debug/client/rendering/RenderLevelStagesTest.java
  src/test/java/net/minecraftforge/debug/world/LoginPacketSplitTest.java
  src/test/java/net/minecraftforge/eventtest/internal/TestFramework.java
  src/test/java/net/minecraftforge/eventtest/tests/forge/client/EntityJoinedWorldTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Triage, 1.19
