Repository MinecraftForge/MinecraftForge, pull requests merged in 2023-12, with the labels that each got.

#9808 [1.20.1] Backport #9807 addOptionalTag/s methods that allow passing the TagKey itself instead of passing the location
  src/main/java/net/minecraftforge/common/extensions/IForgeTagAppender.java
Labels: Assigned, 1.20

#9802 Add impl. of `IModFileInfo#showAsDataPack`
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFileInfo.java
  settings.gradle
Labels: Feature, Triage, 1.20

#9824 [1.20.1] Optimise ForgeConfigSpec and make Range public
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Triage, LTS, 1.20

#9822 [1.20.x] Make common DisplayTest registration tasks easier
  fmlcore/src/main/java/net/minecraftforge/fml/IExtensionPoint.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
Labels: Feature, Triage, 1.20

#9823 [1.20.1] Make common DisplayTest registration tasks easier
  fmlcore/src/main/java/net/minecraftforge/fml/IExtensionPoint.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
Labels: Feature, Triage, LTS, 1.20

#9836 [1.20.x] Improve server panel compatibility
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/InstallerJar.groovy
  build_forge.gradle
  docs/README.md
  server_files/args.txt
  src/main/resources/forge.exc
Labels: Assigned, 1.20

#9826 [1.19.x] Optimise ForgeConfigSpec and make Range public
  build.gradle
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Assigned, LTS, 1.19

#9827 [1.19.2] Optimise ForgeConfigSpec and make Range public
  build.gradle
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Assigned, LTS, 1.19

#9828 [1.18.x] Optimise ForgeConfigSpec and make Range public
  build.gradle
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Assigned, LTS, 1.18

#9837 [1.19.x] Make common DisplayTest registration tasks easier
  fmlcore/src/main/java/net/minecraftforge/fml/IExtensionPoint.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
Labels: Feature, Assigned, LTS, 1.19

#9838 [1.19.2] Make common DisplayTest registration tasks easier
  docs/README.md
  fmlcore/src/main/java/net/minecraftforge/fml/IExtensionPoint.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
Labels: Feature, Assigned, LTS, 1.19

#9839 [1.18.x] Make common DisplayTest registration tasks easier
  docs/README.md
  fmlcore/src/main/java/net/minecraftforge/fml/IExtensionPoint.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
Labels: Feature, Assigned, LTS, 1.18

#9840 [1.18.x] Improve mod description formatting in mods screen
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java
  src/main/resources/META-INF/mods.toml
Labels: Assigned, LTS, 1.18
