Repository MinecraftForge/MinecraftForge, pull requests merged in 2023-05, with the labels that each got.

#9466 [1.19.2] Fix forge grindstone hooks allowing stacks of non-stackable items
  patches/minecraft/net/minecraft/world/inventory/GrindstoneMenu.java.patch
  patches/minecraft/net/minecraft/world/item/BundleItem.java.patch
Labels: Bug, Triage, LTS Backport, 1.19

#9480 [1.19.2] Fix incorrect SpecialSpawn fire location
  patches/minecraft/net/minecraft/world/entity/EntityType.java.patch
Labels: Bug, Triage, LTS Backport, 1.19

#9450 [1.19.x] Fix `NamespacedWrapper#wrapAsHolder`
  src/main/java/net/minecraftforge/registries/NamespacedWrapper.java
Labels: Bug, Assigned, 1.19

#9449 [1.19.x] Collect and log exceptions occurring in DeferredWorkQueue tasks
  fmlcore/src/main/java/net/minecraftforge/fml/DeferredWorkQueue.java
  src/test/java/net/minecraftforge/debug/DeferredWorkQueueTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Assigned, 1.19

#9445 Fix fluids without sound event causing exception in tryFillContainer and tryEmptyContainer
  src/main/java/net/minecraftforge/fluids/FluidUtil.java
Labels: Bug, Fluids, Assigned, 1.19

#9485 [1.19.+] Fix SaplingGrowTreeEvent#setFeature being ignored in FungusBlock
  patches/minecraft/net/minecraft/world/level/block/FungusBlock.java.patch
Labels: Bug, Triage, 1.19

#9484 [1.19.2] Fix SaplingGrowTreeEvent#setFeature being ignored in FungusBlock
  patches/minecraft/net/minecraft/world/level/block/FungusBlock.java.patch
Labels: Bug, Triage, 1.19

#9489 Add missing AT lines to allow registering custom game rule value types
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/java/net/minecraftforge/debug/CustomGameRuleTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, Assigned, 1.19

#9496 [1.19.x] Fix root transform matrix format and allow using all four root transform formats
  src/main/java/net/minecraftforge/client/model/ExtendedBlockModelDeserializer.java
  src/main/java/net/minecraftforge/common/util/TransformationHelper.java
  src/test/resources/assets/composite_model_test/models/block/composite_block.json
Labels: Assigned, 1.19

#9454 Remove unneeded extra reload of datapacks on world creation screen
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/CreateWorldScreen.java.patch
Labels: Cleanup, Assigned, 1.19

#9436 API for registering custom world preset editors
  build.gradle
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/PresetEditor.java.patch
  patches/minecraft/net/minecraft/client/gui/screens/worldselection/WorldCreationUiState.java.patch
  src/generated_test/resources/data/custom_preset_editor_test/worldgen/world_preset/custom_preset_editor_test.json
  src/main/java/net/minecraftforge/client/DimensionSpecialEffectsManager.java
  src/main/java/net/minecraftforge/client/EntitySpectatorShaderManager.java
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/ItemDecoratorHandler.java
  src/main/java/net/minecraftforge/client/NamedRenderTypeManager.java
  src/main/java/net/minecraftforge/client/PresetEditorManager.java
  src/main/java/net/minecraftforge/client/RecipeBookManager.java
  src/main/java/net/minecraftforge/client/event/RegisterPresetEditorsEvent.java
  src/main/java/net/minecraftforge/client/gui/ClientTooltipComponentManager.java
  src/main/java/net/minecraftforge/client/gui/overlay/GuiOverlayManager.java
  src/main/java/net/minecraftforge/client/model/geometry/GeometryLoaderManager.java
  src/main/java/net/minecraftforge/client/textures/TextureAtlasSpriteLoaderManager.java
  src/main/java/net/minecraftforge/registries/GameData.java
  src/main/java/net/minecraftforge/registries/RegistryManager.java
  src/test/java/net/minecraftforge/debug/client/CustomPresetEditorTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/custom_preset_editor_test/lang/en_us.json
  src/test/resources/data/minecraft/tags/worldgen/world_preset/normal.json
Labels: Feature, New Event, Assigned, 1.19

#9497 [1.19.x] Re-implement RenderTooltipEvent.Color
  patches/minecraft/net/minecraft/client/gui/screens/Screen.java.patch
  patches/minecraft/net/minecraft/client/gui/screens/inventory/tooltip/TooltipRenderUtil.java.patch
  src/main/java/net/minecraftforge/client/event/RenderTooltipEvent.java
  src/main/resources/forge.exc
Labels: Rendering, Assigned, 1.19

#9506 [1.18.x] Make mixins work with JarJar
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/TeamcityRequests.groovy
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/Util.groovy
  fmlloader/build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
  server_files/args.txt
  src/test/resources/META-INF/jarjar/ForgeJiJTestMod-1.5.jar
  src/test/resources/META-INF/jarjar/metadata.json
Labels: Bug, Confirmed, 1.18

#9481 [1.18.2] Fix incorrect SpecialSpawn fire location
  patches/minecraft/net/minecraft/world/entity/EntityType.java.patch
Labels: Bug, Assigned, LTS Backport, 1.18

#9429 Loosen access for BucketItem's canBlockContainFluid
  patches/minecraft/net/minecraft/world/item/BucketItem.java.patch
Labels: Feature, Fluids, Assigned, LTS, 1.19

#9494 [1.18.x] Fixed PlayerInteractEvent.EntityInteractSpecific being called too late
  patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
  src/test/java/net/minecraftforge/debug/entity/player/EntityInteractSpecificEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Bug, Assigned, LTS, 1.18

#9341 [1.18.2] fix inconsistent vaporization in BucketItem & FluidType
  patches/minecraft/net/minecraft/core/dispenser/DispenseItemBehavior.java.patch
  patches/minecraft/net/minecraft/world/item/BucketItem.java.patch
  patches/minecraft/net/minecraft/world/item/DispensibleContainerItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeDispensibleContainerItem.java
  src/main/resources/forge.exc
Labels: Bug, Fluids, Assigned, LTS, 1.18

#9475 [1.19.x] Log error when Sheets is class-loaded before registration is completed
  fmlcore/src/main/java/net/minecraftforge/fml/ModLoader.java
  fmlcore/src/main/java/net/minecraftforge/fml/ModStateManager.java
  patches/minecraft/net/minecraft/client/renderer/Sheets.java.patch
Labels: Feature, Assigned, 1.19

#9499 Add method to GatherDataEvent to obtain collection of all input paths.
  src/main/java/net/minecraftforge/data/event/GatherDataEvent.java
Labels: Feature, Assigned, 1.19

#9513 [1.18.x] Add Forge "bosses" tag
  src/generated/resources/data/forge/tags/entity_types/bosses.json
  src/main/java/net/minecraftforge/common/ForgeMod.java
  src/main/java/net/minecraftforge/common/Tags.java
  src/main/java/net/minecraftforge/common/data/ForgeEntityTypeTagsProvider.java
Labels: Feature, LTS, 1.18

#9515 [1.18.x] Make sure that fluids don't evaporate when placed unless they're in a warm dimension
  patches/minecraft/net/minecraft/world/item/BucketItem.java.patch
Labels: Bug, Fluids, Assigned, 1.18

#9482 [1.19.2] Fix the rest of the spawn event calls
  patches/minecraft/net/minecraft/server/commands/SummonCommand.java.patch
  patches/minecraft/net/minecraft/util/SpawnUtil.java.patch
  patches/minecraft/net/minecraft/world/entity/Mob.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/Strider.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/CatSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/BaseSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/NaturalSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/PatrolSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/structure/structures/OceanMonumentPieces.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/structure/structures/WoodlandMansionPieces.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplate.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/EntityJoinLevelEvent.java
  src/main/java/net/minecraftforge/event/entity/living/LivingSpawnEvent.java
Labels: Bug, Triage, LTS, 1.19
