Repository MinecraftForge/MinecraftForge, pull requests merged in 2023-09, with the labels that each got.

#9702 [1.20.x] Keep order of sources in PackRepository
  patches/minecraft/net/minecraft/server/packs/repository/PackRepository.java.patch
Labels: Triage, 1.20

#9703 [1.19.4] Keep order of sources in PackRepository
  patches/minecraft/net/minecraft/server/packs/repository/PackRepository.java.patch
Labels: Triage, LTS, 1.19

#9700 [1.19.x] Fix `Level` leak in debug HUD
  src/main/java/net/minecraftforge/client/gui/overlay/ForgeGui.java
Labels: Assigned, LTS, 1.19

#9722 [1.20.x] Fix double message encoding in `Channel#toVanillaPacket` #9721
  src/main/java/net/minecraftforge/network/Channel.java
  src/main/java/net/minecraftforge/network/packets/OpenContainer.java
Labels: Triage, 1.20

#9715 [1.20.x] Optimise `ForgeRegistry#validateContent`
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
Labels: Triage, 1.20

#9728 Update ForgeEventFactory.java to fix Traveling to Dimensions
  patches/minecraft/net/minecraft/server/level/ServerPlayer.java.patch
  patches/minecraft/net/minecraft/world/entity/Entity.java.patch
Labels: Assigned, 1.20

#9729 [1.20.x] `PlayerDestroyItemEvent` now trigger for Fishing Rods
  patches/minecraft/net/minecraft/world/item/FishingRodItem.java.patch
Labels: Bug, Triage, 1.20

#9735 [1.20.2] Fix `ignitedByLava` block property making blocks permanently flammable
  patches/minecraft/net/minecraft/world/level/material/LavaFluid.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
Labels: Triage, 1.20

#9707 [1.20.1] Improve mod loading error message for errors inside mod constructors
  javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
  src/test/java/net/minecraftforge/debug/ConstructorThrowTest.java
  src/test/resources/META-INF/mods.toml
Labels: Assigned, 1.20

#9710 [1.20.x] Optimise path filter in mod loading
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ExplodedDirectoryLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModJarMetadata.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonClientLaunchHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonServerLaunchHandler.java
Labels: Assigned, 1.20

#9708 [1.19.4] Improve mod loading error message for errors inside mod constructors
  javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
  src/test/java/net/minecraftforge/debug/ConstructorThrowTest.java
  src/test/resources/META-INF/mods.toml
Labels: Assigned, LTS, 1.19

#9711 [1.19.4] Optimise path filter in mod loading
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ExplodedDirectoryLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModJarMetadata.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonClientLaunchHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonServerLaunchHandler.java
Labels: Triage, LTS, 1.19

#9709 [1.19.2] Improve mod loading error message for errors inside mod constructors
  javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
  src/test/java/net/minecraftforge/debug/ConstructorThrowTest.java
  src/test/resources/META-INF/mods.toml
Labels: Assigned, LTS, 1.19

#9712 [1.19.2] Optimise path filter in mod loading
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ExplodedDirectoryLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModJarMetadata.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonClientLaunchHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonServerLaunchHandler.java
Labels: Triage, LTS, 1.19

#9736 [1.20.x] Fix Slot Index for Inventory Ticking Items
  patches/minecraft/net/minecraft/world/entity/player/Inventory.java.patch
Labels: Triage, 1.20
