Repository MinecraftForge/MinecraftForge, pull requests merged in 2023-07, with the labels that each got.

#9615 Fix ShieldBlockEvent performing damage with incorrect state
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
Labels: Triage, 1.20

#9604 [1.20.x] Make overloads consistent for defineListAllowEmpty in ForgeConfigSpec.Builder
  mdk/src/main/java/com/example/examplemod/Config.java
  src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
Labels: Triage, 1.20

#9619 Fix Early Loading window FPS snafu where it could spam unlimited screen updates
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
Labels: Triage, 1.20

#9612 Improve Creative Tab ordering
  src/main/java/net/minecraftforge/common/CreativeModeTabRegistry.java
  src/test/java/net/minecraftforge/debug/CreativeModeTabTest.java
Labels: Triage, 1.20

#9613 Expose loaded RegistryAccess through AddReloadListenerEvent
  patches/minecraft/net/minecraft/server/ReloadableServerResources.java.patch
  src/main/java/net/minecraftforge/event/AddReloadListenerEvent.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: Triage, 1.20

#9586 [1.20.x] Enable placing fluids into waterlogged blocks with FluidUtil::tryPlaceFluid
  src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockWrapper.java
  src/test/java/net/minecraftforge/debug/item/CustomFluidContainerTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/custom_fluid_container_test/models/item/custom_fluid_container.json
Labels: Triage, 1.20

#9618 [1.20.x] Improve logging for server connections
  patches/minecraft/net/minecraft/client/gui/screens/ConnectScreen.java.patch
  src/main/java/net/minecraftforge/common/MinecraftForge.java
  src/main/java/net/minecraftforge/network/DualStackUtils.java
Labels: Triage, 1.20

#9625 [1.19.2] Log a proper duplicate mod(s) error message
  fmlloader/src/main/java/net/minecraftforge/fml/loading/UniqueModListBuilder.java
Labels: Triage, LTS, 1.19

#9623 [1.19.2] Improve logging for server connections
  patches/minecraft/net/minecraft/client/gui/screens/ConnectScreen.java.patch
  src/main/java/net/minecraftforge/common/MinecraftForge.java
  src/main/java/net/minecraftforge/network/DualStackUtils.java
Labels: Triage, LTS, 1.19

#9519 [1.19.x] Enable placing fluids into waterlogged blocks with FluidUtil::tryPlaceFluid
  src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockWrapper.java
  src/test/java/net/minecraftforge/debug/item/CustomFluidContainerTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/custom_fluid_container_test/models/item/custom_fluid_container.json
Labels: Feature, Fluids, Triage, 1.19

#9622 [1.19.4] Improve logging for server connections
  patches/minecraft/net/minecraft/client/gui/screens/ConnectScreen.java.patch
  src/main/java/net/minecraftforge/common/MinecraftForge.java
  src/main/java/net/minecraftforge/network/DualStackUtils.java
Labels: Triage, LTS, 1.19

#9638 Add missing null check for TagsProvider#existingFileHelper
  patches/minecraft/net/minecraft/data/tags/TagsProvider.java.patch
Labels: Bug, Assigned, 1.20

#9633 Fix sources jar on non-official mappings
  src/main/java/net/minecraftforge/client/loading/ForgeLoadingOverlay.java
Labels: 1.20, Queued

#9637 [1.20.1] AlterGroundEvent for modifying block placement performed by AlterGroundDecorator
  patches/minecraft/net/minecraft/world/level/levelgen/feature/treedecorators/AlterGroundDecorator.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/level/AlterGroundEvent.java
  src/test/java/net/minecraftforge/debug/AlterGroundEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, New Event, Triage, 1.20

#9636 [1.19.4] AlterGroundEvent for modifying block placement performed by AlterGroundDecorator
  patches/minecraft/net/minecraft/world/level/levelgen/feature/treedecorators/AlterGroundDecorator.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/level/AlterGroundEvent.java
  src/test/java/net/minecraftforge/debug/AlterGroundEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, New Event, Triage, LTS, 1.19

#9635 [1.19.2] AlterGroundEvent for modifying block placement performed by AlterGroundDecorator
  patches/minecraft/net/minecraft/world/level/levelgen/feature/treedecorators/AlterGroundDecorator.java.patch
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/level/AlterGroundEvent.java
  src/test/java/net/minecraftforge/debug/AlterGroundEventTest.java
  src/test/resources/META-INF/mods.toml
Labels: Feature, New Event, Triage, LTS, 1.19

#9624 [1.18.2] Improve logging for server connections
  patches/minecraft/net/minecraft/client/gui/screens/ConnectScreen.java.patch
  src/main/java/net/minecraftforge/common/MinecraftForge.java
  src/main/java/net/minecraftforge/network/DualStackUtils.java
Labels: Triage, LTS, 1.18

#9535 [1.20] Fix EntityEvent.Size not being fired
  patches/minecraft/net/minecraft/world/entity/Entity.java.patch
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  patches/minecraft/net/minecraft/world/level/portal/PortalShape.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/EntityEvent.java
Labels: Triage, 1.20

#9525 [1.20] LivingBreatheEvent and LivingDrownEvent
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/entity/living/LivingBreatheEvent.java
  src/main/java/net/minecraftforge/event/entity/living/LivingDrownEvent.java
Labels: Feature, New Event, Triage, 1.20

#9510 [1.19.x] Particle Description Data Provider
  src/generated_test/resources/assets/minecraft/particles/cloud.json
  src/generated_test/resources/assets/minecraft/particles/dripping_lava.json
  src/generated_test/resources/assets/minecraft/particles/enchant.json
  src/generated_test/resources/assets/minecraft/particles/fishing.json
  src/main/java/net/minecraftforge/common/data/ParticleDescriptionProvider.java
  src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
Labels: Feature, Assigned, LTS, 1.19

#9644 Add PlayerSpawnPhantomsEvent, utilized to block or forcefully allow PhantomSpawner to spawn phantoms
  patches/minecraft/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch
  src/main/java/net/minecraftforge/event/entity/player/PlayerSpawnPhantomsEvent.java
Labels: Feature, New Event, Triage, 1.20

#9647 Fix EyeHeight event being fired twice
  patches/minecraft/net/minecraft/world/entity/Entity.java.patch
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
Labels: Assigned, 1.20

#9648 Make item name rendering and status bar rendering respect left and right height
  patches/minecraft/net/minecraft/client/gui/Gui.java.patch
  src/main/java/net/minecraftforge/client/gui/overlay/ForgeGui.java
  src/main/java/net/minecraftforge/client/gui/overlay/VanillaGuiOverlay.java
  src/main/resources/forge.exc
Labels: Triage, 1.20

#9487 Add `EmptyEnergyStorage`
  src/main/java/net/minecraftforge/energy/EmptyEnergyStorage.java
Labels: Feature, Triage, 1.19

#9446 [1.19.x] The tint on block breaking particles is now handled in IForgeBlock
  patches/minecraft/net/minecraft/client/particle/TerrainParticle.java.patch
  src/main/java/net/minecraftforge/client/extensions/common/IClientBlockExtensions.java
Labels: Feature, Rendering, 1.19

#9428 [1.19.x] Properly Handle Fluid Updates while in a Boat
  patches/minecraft/net/minecraft/world/entity/Entity.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeBoat.java
  src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
  src/main/java/net/minecraftforge/common/extensions/IForgeFluid.java
  src/main/java/net/minecraftforge/common/extensions/IForgeFluidState.java
  src/main/java/net/minecraftforge/fluids/FluidType.java
Labels: Bug, Fluids, Triage, 1.19

#9649 Fixed AdvancementsScreen.java.patch buttons not rendering
  patches/minecraft/net/minecraft/client/gui/screens/advancements/AdvancementsScreen.java.patch
Labels: Triage, 1.20

#9650 Fixed AdvancementsScreen.java to render next/previous page buttons now.
  patches/minecraft/net/minecraft/client/gui/screens/advancements/AdvancementsScreen.java.patch
Labels: Triage, LTS, 1.19

#9651 Fix the Emissive Rendering for Experimental Light Pipeline
  src/main/java/net/minecraftforge/client/model/lighting/FlatQuadLighter.java
  src/main/java/net/minecraftforge/client/model/lighting/QuadLighter.java
  src/main/java/net/minecraftforge/client/model/lighting/SmoothQuadLighter.java
Labels: Assigned, 1.20

#9652 [1.20.1] Re-add in-game mod menu
  patches/minecraft/net/minecraft/client/gui/screens/PauseScreen.java.patch
Labels: Regression, Feature, Triage, 1.20

#9358 Fixed FluidUtil#tryFillContainer returning invalid result when simulating
  src/main/java/net/minecraftforge/fluids/FluidUtil.java
  src/test/java/net/minecraftforge/debug/FluidUtilTest.java
Labels: Bug, Fluids, Triage, LTS, 1.19

#9654 [1.19.4] Re-add in-game mod menu
  patches/minecraft/net/minecraft/client/gui/screens/PauseScreen.java.patch
Labels: Regression, Feature, Assigned, LTS, 1.19

#9655 [1.19.2] Re-add in-game mod menu
  patches/minecraft/net/minecraft/client/gui/screens/PauseScreen.java.patch
Labels: Regression, Feature, Triage, LTS, 1.19

#9656 [1.20.1] Fix parameters and add additional ones to adjustLightmapColors
  src/main/java/net/minecraftforge/client/extensions/IForgeDimensionSpecialEffects.java
Labels: Regression, Feature, Rendering, Assigned, 1.20

#9657 [1.19.4] Fix parameters and add additional ones to adjustLightmapColors
  src/main/java/net/minecraftforge/client/extensions/IForgeDimensionSpecialEffects.java
Labels: Regression, Feature, Rendering, Assigned, LTS, 1.19

#9658 [1.19.2] Fix parameters and add additional ones to adjustLightmapColors
  src/main/java/net/minecraftforge/client/extensions/IForgeDimensionSpecialEffects.java
Labels: Regression, Feature, Rendering, Assigned, LTS, 1.19

#9664 preserve the ability to calculate normals for block models but default to behaving like vanilla
  patches/minecraft/net/minecraft/client/renderer/block/model/FaceBakery.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/model/ForgeFaceData.java
  src/main/java/net/minecraftforge/client/model/generators/ModelBuilder.java
  src/main/java/net/minecraftforge/client/model/generators/loaders/ItemLayerModelBuilder.java
Labels: Bug, Rendering, Assigned, 1.20

#9671 1.20.x on creative mode tabs build contents fix
  patches/minecraft/net/minecraft/world/item/CreativeModeTab.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Bug, Assigned, 1.20

#9669 Stable direction get nearest
  patches/minecraft/com/mojang/blaze3d/vertex/SheetedDecalTextureGenerator.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
  src/test/java/net/minecraftforge/debug/client/model/CalculateNormalsTest.java
  src/test/resources/META-INF/mods.toml
  src/test/resources/assets/calculate_normals_test/blockstates/fire_accurate_normals_test.json
  src/test/resources/assets/calculate_normals_test/models/block/fire_accurate_normals_test.json
  src/test/resources/assets/calculate_normals_test/models/item/fire_accurate_normals_test.json
Labels: Rendering, Assigned, 1.20

#9670 Add a config option to restore the calculate all normals behavior
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Regression, Feature, Rendering, Triage, 1.20

#9679 Revert EntityEvent.Size changes to before #9018 was pulled.
  patches/minecraft/net/minecraft/world/entity/Entity.java.patch
  patches/minecraft/net/minecraft/world/level/portal/PortalShape.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/entity/EntityEvent.java
Labels: Bug, Regression, Triage, 1.20
