Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-03, with the labels that each got.

#9875 Fix #9874 - DatapackBuiltinEntriesProvider causes issues with forge registries
  patches/minecraft/net/minecraft/data/registries/RegistriesDatapackGenerator.java.patch
  patches/minecraft/net/minecraft/data/registries/RegistryPatchGenerator.java.patch
  patches/minecraft/net/minecraft/resources/RegistryDataLoader.java.patch
  patches/minecraft/net/minecraft/server/WorldLoader.java.patch
  src/main/java/net/minecraftforge/registries/DataPackRegistriesHooks.java
  src/test/generated/datapack_builtin_entries_provider_test/data/datapack_builtin_entries_provider_test/biome_modifier/mossy_stone_modifier.json
  src/test/generated/datapack_builtin_entries_provider_test/data/datapack_builtin_entries_provider_test/worldgen/configured_feature/mossy_stone.json
  src/test/generated/datapack_builtin_entries_provider_test/data/datapack_builtin_entries_provider_test/worldgen/placed_feature/mossy_stone.json
  src/test/java/net/minecraftforge/debug/gameplay/data/DatapackBuiltinEntriesProviderTest.java
Labels: Triage, 1.20

#9866 [1.20.4] Add CPU usage config option to early window
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/PerformanceInfo.java
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/RenderElement.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLConfig.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/VersionInfo.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/progress/ProgressMeter.java
Labels: Feature, Triage, 1.20

#9880 1.20.1 bump dependencies
  build.gradle
Labels: Assigned, 1.20, Queued

#9879 1.19.x bump dependencies
  build.gradle
Labels: Assigned, LTS, 1.19, Queued

#9878 1.19.2 bump dependencies (similar to #9877)
  build.gradle
Labels: Assigned, LTS, 1.19, Queued

#9877 1.18.2 bump dependencies
  build.gradle
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/checks/CheckATs.groovy
Labels: Assigned, 1.18, Queued

#9884 [1.20.x] Make common config screen registration tasks easier
  src/main/java/net/minecraftforge/client/ConfigScreenHandler.java
  src/main/java/net/minecraftforge/common/MinecraftForge.java
Labels: Feature, Assigned, 1.20

#9886 [1.20.4] Optimise capabilities a tad
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  patches/minecraft/net/minecraft/world/entity/animal/horse/AbstractHorse.java.patch
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  patches/minecraft/net/minecraft/world/entity/vehicle/AbstractMinecartContainer.java.patch
  patches/minecraft/net/minecraft/world/entity/vehicle/ChestBoat.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/AbstractFurnaceBlockEntity.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/BaseContainerBlockEntity.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/BrewingStandBlockEntity.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/ChestBlockEntity.java.patch
  patches/minecraft/net/minecraft/world/level/block/entity/ChiseledBookShelfBlockEntity.java.patch
  src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java
  src/main/java/net/minecraftforge/common/util/LazyOptional.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: Triage, 1.20
