Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-06, with the labels that each got.

#10004 [1.20.6] Cleanup FML Bindings
  fmlcore/src/main/java/net/minecraftforge/fml/Bindings.java
Labels: Cleanup, Triage, 1.20

#9890 ref(event): change tick event to have pre/post classes
  src/main/java/net/minecraftforge/common/ForgeInternalHandler.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/TickEvent.java
Labels: BreakingChange, Assigned, 1.20

#10006 [1.21] Fixed falling block entities not rendering as moving blocks
  patches/minecraft/net/minecraft/client/renderer/entity/FallingBlockRenderer.java.patch
Labels: Bug, Triage, LTS, 1.21

#10011 fix: restore PartEntity support in Player.attack
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
Labels: Triage, LTS, 1.21

#10014 Fixed perspective rendering in SeparateTransformsModel
  src/main/java/net/minecraftforge/client/model/SeparateTransformsModel.java
Labels: Triage, LTS, 1.21

#9995 fix(registry): change conditional checking so that errors in the original codec are respected
  patches/minecraft/net/minecraft/resources/RegistryDataLoader.java.patch
Labels: Assigned, 1.20

#10029 [1.21] Fix compile errors in MDK
  mdk/src/main/java/com/example/examplemod/Config.java
Labels: Assigned, LTS, 1.21

#10016 [1.20.6] Fixed falling block entities not rendering as moving blocks
  patches/minecraft/net/minecraft/client/renderer/entity/FallingBlockRenderer.java.patch
Labels: Triage, 1.20

#10021 [1.20.6] Choose default JarJar mod file type based on parent JAR
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
Labels: Triage, 1.20

#10017 [1.20.4] Fixed falling block entities not rendering as moving blocks
  patches/minecraft/net/minecraft/client/renderer/entity/FallingBlockRenderer.java.patch
Labels: Triage, 1.20

#10022 [1.20.4] Choose default JarJar mod file type based on parent JAR
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
Labels: Triage, 1.20

#10018 [1.20.1] Fixed falling block entities not rendering as moving blocks
  patches/minecraft/net/minecraft/client/renderer/entity/FallingBlockRenderer.java.patch
Labels: Triage, 1.20

#10023 [1.20.1] Choose default JarJar mod file type based on parent JAR
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
Labels: Triage, 1.20
