Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-10, with the labels that each got.

#10102 [1.19.4] Remove unneeded boat patch
  patches/minecraft/net/minecraft/world/entity/vehicle/Boat.java.patch
Labels: Cleanup, Assigned, LTS, 1.19

#10086 [1.20.6] Remove unneeded boat patch
  patches/minecraft/net/minecraft/world/entity/vehicle/Boat.java.patch
Labels: Cleanup, Assigned, LTS, 1.20

#10087 [1.20.4] Remove unneeded boat patch
  patches/minecraft/net/minecraft/world/entity/vehicle/Boat.java.patch
Labels: Cleanup, Assigned, LTS, 1.20

#10097 [1.20.4] Use the new fire() and Result#isAllowed/isDenied/isDefault methods from EventBus
  patches/minecraft/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
  patches/minecraft/net/minecraft/server/level/ServerPlayerGameMode.java.patch
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/Spider.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/Zombie.java.patch
  patches/minecraft/net/minecraft/world/level/block/FungusBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/grower/TreeGrower.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch
  settings.gradle
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: Feature, Cleanup, Assigned, LTS, 1.20

#10096 [1.20.1] Remove unneeded boat patch
  patches/minecraft/net/minecraft/world/entity/vehicle/Boat.java.patch
Labels: Cleanup, Assigned, LTS, 1.20

#10124 Patch BlockEntity#isValidBlockState to use getType Method
  patches/minecraft/net/minecraft/world/level/block/entity/BlockEntity.java.patch
Labels: Feature, Triage, LTS, 1.21

#10143 [1.21.3] Fix pause menu having a black background
  patches/minecraft/com/mojang/blaze3d/platform/GlStateManager.java.patch
  patches/minecraft/com/mojang/blaze3d/systems/RenderSystem.java.patch
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
Labels: Triage, LTS, 1.21

#10149 Add AT for BlockEntityType constructor.
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Triage, LTS, 1.21

#10128 [1.20.6] Bump CoreMods and ASM
  build_shared.gradle
  settings.gradle
Labels: Assigned, 1.20
