Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-08, with the labels that each got.

#10061 Removed unneeded boat patch (Fix MC-119811)
  patches/minecraft/net/minecraft/world/entity/vehicle/Boat.java.patch
Labels: Triage, LTS, 1.21

#10063 Properly ignore unknown mod files
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
Labels: Triage, LTS, 1.21

#10071 [1.21.1] Add a few Method Helpers onto ResourceKey to make getting Data Driven Entries Simplier
  patches/minecraft/net/minecraft/resources/ResourceKey.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeResourceKey.java
Labels: Triage, LTS, 1.21

#10073 [1.20.1] Early display fixes/workarounds for buggy drivers
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLConfig.java
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
Labels: Bug, Triage, 1.20

#10076 [1.21.1] Fire `OnDatapackSyncEvent` when a player joins a server
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
Labels: Assigned, LTS, 1.21

#10077 [1.20.6] Fire `OnDatapackSyncEvent` when a player joins a server
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
Labels: Assigned, 1.20

#10065 Fix issues with `QuadBakingVertexConsumer` and Forge's OBJ loader
  src/main/java/net/minecraftforge/client/model/obj/ObjModel.java
  src/main/java/net/minecraftforge/client/model/pipeline/QuadBakingVertexConsumer.java
  src/test/java/net/minecraftforge/debug/client/ObjModelTest.java
  src/test/resources/obj_model_test/assets/minecraft/atlases/blocks.json
  src/test/resources/obj_model_test/assets/obj_model_test/models/pyramid.json
  src/test/resources/obj_model_test/assets/obj_model_test/models/pyramid.mtl
  src/test/resources/obj_model_test/assets/obj_model_test/models/pyramid.obj
  src/test/resources/obj_model_test/assets/obj_model_test/textures/pyramid.png
Labels: Assigned, LTS, 1.21
