Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-09, with the labels that each got.

#10069 Fix inverted logic in TagEmptyCondition
  build_forge.gradle
  patches/minecraft/net/minecraft/gametest/framework/GameTestServer.java.patch
  patches/minecraft/net/minecraft/server/Main.java.patch
  src/main/java/net/minecraftforge/common/crafting/conditions/TagEmptyCondition.java
  src/test/generated/conditional_recipe/data/conditional_recipe/advancement/recipes/tag_empty_condition_doesnt_load.json
  src/test/generated/conditional_recipe/data/conditional_recipe/advancement/recipes/tag_empty_condition_loads.json
  src/test/generated/conditional_recipe/data/conditional_recipe/recipe/tag_empty_condition_doesnt_load.json
  src/test/generated/conditional_recipe/data/conditional_recipe/recipe/tag_empty_condition_loads.json
  src/test/generated/conditional_recipe/data/forge/tags/item/eggs.json
  src/test/java/net/minecraftforge/debug/gameplay/crafting/ConditionalRecipeTest.java
  src/test/resources/conditional_recipe/META-INF/mods.toml
Labels: Triage, LTS, 1.21

#10081 Packet distributor test crash fix
  patches/minecraft/net/minecraft/gametest/framework/GameTestServer.java.patch
  src/test/java/net/minecraftforge/debug/network/PacketTest.java
Labels: LTS, 1.21

#10115 [1.21.1] Fix layering of translucent sprites being broken
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
Labels: Regression, Rendering, Triage, LTS, 1.21
