Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-12, with the labels that each got.

#10213 [1.21.4] Manage FileWatcher instance per ConfigFileTypeHandler
  fmlcore/src/main/java/net/minecraftforge/fml/config/ConfigFileTypeHandler.java
  fmlcore/src/main/java/net/minecraftforge/fml/config/ConfigTracker.java
  fmlcore/src/main/java/net/minecraftforge/fml/config/ModConfig.java
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/server/dedicated/DedicatedServer.java.patch
Labels: Bug, Triage, LTS, 1.21

#10242 [1.21.4] Allow mipmap lowering to be disabled
  patches/minecraft/net/minecraft/client/renderer/texture/SpriteLoader.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, LTS, 1.21

#10256 [1.21.3] Allow mipmap lowering to be disabled
  patches/minecraft/net/minecraft/client/renderer/texture/SpriteLoader.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, LTS, 1.21

#10214 [1.21.3] Manage FileWatcher instance per ConfigFileTypeHandler
  fmlcore/src/main/java/net/minecraftforge/fml/config/ConfigFileTypeHandler.java
  fmlcore/src/main/java/net/minecraftforge/fml/config/ConfigTracker.java
  fmlcore/src/main/java/net/minecraftforge/fml/config/ModConfig.java
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/server/dedicated/DedicatedServer.java.patch
Labels: LTS, Queued, 1.21

#10212 [1.21.3] Skip processing Forge classes in `RuntimeDistCleaner`
  fmlloader/src/main/java/net/minecraftforge/fml/loading/RuntimeDistCleaner.java
  src/main/java/net/minecraftforge/client/event/ScreenEvent.java
  src/main/java/net/minecraftforge/client/gui/TitleScreenModUpdateIndicator.java
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
Labels: Performance, Triage, LTS, 1.21

#10220 [1.21.3] Skip Forge classes in the RuntimeEnumExtender transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/RuntimeEnumExtender.java
Labels: Triage, LTS, 1.21

#10225 [1.21.3] Skip Vanilla classes for the `CapabilityTokenSubclass` transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/CapabilityTokenSubclass.java
Labels: Performance, Capabilities, LTS, Queued, 1.21

#10232 [1.21.3] Deprecate `@ObjectHolder`, add a couple of fast-paths
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/ObjectHolderDefinalize.java
  src/main/java/net/minecraftforge/registries/ObjectHolder.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
Labels: Triage, LTS, 1.21

#10237 [1.21.3] Simplify memory usage display on loading screen
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/PerformanceInfo.java
Labels: LTS, Queued, 1.21

#10215 [1.21.1] Manage FileWatcher instance per ConfigFileTypeHandler
  fmlcore/src/main/java/net/minecraftforge/fml/config/ConfigFileTypeHandler.java
  fmlcore/src/main/java/net/minecraftforge/fml/config/ConfigTracker.java
  fmlcore/src/main/java/net/minecraftforge/fml/config/ModConfig.java
  patches/minecraft/net/minecraft/client/Minecraft.java.patch
  patches/minecraft/net/minecraft/server/dedicated/DedicatedServer.java.patch
Labels: LTS, Queued, 1.21

#10236 [1.21.1] Simplify memory usage display on loading screen
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/PerformanceInfo.java
Labels: LTS, Queued, 1.21

#10231 [1.21.1] Deprecate `@ObjectHolder`, add a couple of fast-paths
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/ObjectHolderDefinalize.java
  src/main/java/net/minecraftforge/registries/ObjectHolder.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
Labels: Triage, LTS, 1.21

#10219 [1.21.1] Skip Forge classes in the RuntimeEnumExtender transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/RuntimeEnumExtender.java
Labels: Triage, LTS, 1.21

#10211 [1.21.1] Skip processing Forge classes in `RuntimeDistCleaner`
  fmlloader/src/main/java/net/minecraftforge/fml/loading/RuntimeDistCleaner.java
  src/main/java/net/minecraftforge/client/event/ScreenEvent.java
  src/main/java/net/minecraftforge/client/gui/TitleScreenModUpdateIndicator.java
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
Labels: Performance, Triage, LTS, 1.21

#10210 [1.20.6] Skip processing Forge classes in `RuntimeDistCleaner`
  fmlloader/src/main/java/net/minecraftforge/fml/loading/RuntimeDistCleaner.java
  src/main/java/net/minecraftforge/client/event/ScreenEvent.java
  src/main/java/net/minecraftforge/client/gui/TitleScreenModUpdateIndicator.java
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
Labels: Performance, Triage, LTS, 1.20

#10218 [1.20.6] Skip Forge classes in the RuntimeEnumExtender transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/RuntimeEnumExtender.java
Labels: Triage, LTS, 1.20

#10223 [1.20.6] Skip Vanilla classes for the `CapabilityTokenSubclass` transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/CapabilityTokenSubclass.java
Labels: Performance, Capabilities, LTS, 1.20, Queued

#10254 [1.20.6] Allow mipmap lowering to be disabled
  patches/minecraft/net/minecraft/client/renderer/texture/SpriteLoader.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, LTS, 1.20

#10235 [1.20.6] Simplify memory usage display on loading screen
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/PerformanceInfo.java
Labels: LTS, 1.20, Queued

#10248 [1.20.6] Add optional fix of use item duration, disabled by default
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/event/entity/living/LivingEntityUseItemEvent.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.20

#10230 [1.20.6] Deprecate `@ObjectHolder`, add a couple of fast-paths
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/ObjectHolderDefinalize.java
  src/main/java/net/minecraftforge/registries/ObjectHolder.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
Labels: Triage, LTS, 1.20

#10262 [1.21.4] Bump CoreMods to 5.2.4
  settings.gradle
Labels: Triage, LTS, 1.21

#10267 [1.21.3] Bump CoreMods to 5.2.4
  settings.gradle
Labels: Triage, LTS, 1.21

#10266 [1.21.1] Bump CoreMods to 5.2.4
  settings.gradle
Labels: Triage, LTS, 1.21

#10265 [1.20.6] Bump CoreMods to 5.2.4
  settings.gradle
Labels: Triage, 1.20

#10209 [1.20.4] Skip processing Forge classes in `RuntimeDistCleaner`
  fmlloader/src/main/java/net/minecraftforge/fml/loading/RuntimeDistCleaner.java
  src/main/java/net/minecraftforge/client/event/ScreenEvent.java
  src/main/java/net/minecraftforge/client/gui/TitleScreenModUpdateIndicator.java
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
Labels: Performance, Triage, LTS, 1.20

#10217 [1.20.4] Skip Forge classes in the RuntimeEnumExtender transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/RuntimeEnumExtender.java
Labels: Triage, LTS, 1.20

#10222 [1.20.4] Skip Vanilla classes for the `CapabilityTokenSubclass` transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/CapabilityTokenSubclass.java
Labels: Performance, Capabilities, LTS, 1.20, Queued

#10229 [1.20.4] Deprecate `@ObjectHolder`, add a couple of fast-paths
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/ObjectHolderDefinalize.java
  src/main/java/net/minecraftforge/registries/ObjectHolder.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
Labels: Triage, LTS, 1.20

#10234 [1.20.4] Simplify memory usage display on loading screen
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/PerformanceInfo.java
Labels: LTS, 1.20, Queued

#10247 [1.20.4] Add optional fix of use item duration, disabled by default
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/event/entity/living/LivingEntityUseItemEvent.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.20

#10253 [1.20.4] Allow mipmap lowering to be disabled
  patches/minecraft/net/minecraft/client/renderer/texture/SpriteLoader.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, LTS, 1.20

#10264 [1.20.4] Bump CoreMods to 5.2.4
  settings.gradle
Labels: Triage, 1.20

#10258 [1.20.1] Disable clean on TeamCity
  build.gradle
  settings.gradle
Labels: Triage, 1.20

#10208 [1.20.1] Skip processing Forge classes in `RuntimeDistCleaner`
  fmlloader/src/main/java/net/minecraftforge/fml/loading/RuntimeDistCleaner.java
  src/main/java/net/minecraftforge/client/event/ScreenEvent.java
  src/main/java/net/minecraftforge/client/gui/TitleScreenModUpdateIndicator.java
  src/main/java/net/minecraftforge/client/loading/ClientModLoader.java
Labels: Performance, Triage, LTS, 1.20

#10216 [1.20.1] Skip Forge classes in the RuntimeEnumExtender transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/RuntimeEnumExtender.java
Labels: Triage, LTS, 1.20

#10221 [1.20.1] Skip Vanilla classes for the `CapabilityTokenSubclass` transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/CapabilityTokenSubclass.java
Labels: Performance, Capabilities, LTS, 1.20, Queued

#10228 [1.20.1] Deprecate `@ObjectHolder`, add a couple of fast-paths
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/ObjectHolderDefinalize.java
  src/main/java/net/minecraftforge/registries/ObjectHolder.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
Labels: Triage, LTS, 1.20

#10233 [1.20.1] Simplify memory usage display on loading screen
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/PerformanceInfo.java
Labels: LTS, 1.20, Queued

#10241 [1.20.1] Backport some Vanilla 1.21 `ResourceLocation` methods
  patches/minecraft/net/minecraft/resources/ResourceLocation.java.patch
Labels: Feature, LTS, 1.20, Queued

#10246 [1.20.1] Add optional fix of use item duration, disabled by default
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/event/entity/living/LivingEntityUseItemEvent.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.20

#10263 [1.20.1] Bump CoreMods to 5.2.4
  build.gradle
Labels: Triage, 1.20

#10259 [1.19.4] Disable clean on TeamCity
  build.gradle
  settings.gradle
Labels: Triage, LTS, 1.19

#10227 [1.19.4] Deprecate `@ObjectHolder`, add a couple of fast-paths
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/ObjectHolderDefinalize.java
  src/main/java/net/minecraftforge/registries/ObjectHolder.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
Labels: Triage, 1.19

#10240 [1.19.4] Backport some Vanilla 1.21 `ResourceLocation` methods
  patches/minecraft/net/minecraft/resources/ResourceLocation.java.patch
Labels: Feature, 1.19, Queued

#10245 [1.19.4] Add optional fix of use item duration, disabled by default
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/event/entity/living/LivingEntityUseItemEvent.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.19

#10251 [1.19.4] Allow mipmap lowering to be disabled
  patches/minecraft/net/minecraft/client/renderer/texture/SpriteLoader.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.19

#10270 [1.19.4] Bump CoreMods to 5.2.4
  build.gradle
Labels: Triage, LTS, 1.19

#10226 [1.19.2] Deprecate `@ObjectHolder`, add a couple of fast-paths
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/ObjectHolderDefinalize.java
  src/main/java/net/minecraftforge/registries/ObjectHolder.java
  src/main/java/net/minecraftforge/registries/ObjectHolderRegistry.java
Labels: Triage, 1.19

#10239 [1.19.2] Backport some Vanilla 1.21 `ResourceLocation` methods
  patches/minecraft/net/minecraft/resources/ResourceLocation.java.patch
Labels: Feature, 1.19, Queued

#10244 [1.19.2] Add optional fix of use item duration, disabled by default
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/event/entity/living/LivingEntityUseItemEvent.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.19

#10250 [1.19.2] Allow mipmap lowering to be disabled
  patches/minecraft/net/minecraft/client/renderer/texture/TextureAtlas.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.19

#10238 [1.18.2] Backport some Vanilla 1.21 `ResourceLocation` methods
  patches/minecraft/net/minecraft/resources/ResourceLocation.java.patch
Labels: Feature, 1.18

#10243 [1.18.2] Add optional fix of use item duration, disabled by default
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/event/entity/living/LivingEntityUseItemEvent.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: 1.18

#10249 [1.18.2] Allow mipmap lowering to be disabled
  patches/minecraft/net/minecraft/client/renderer/texture/TextureAtlas.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, 1.18

#10224 [1.21.1] Skip Vanilla classes for the `CapabilityTokenSubclass` transformer
  fmlloader/src/main/java/net/minecraftforge/fml/common/asm/CapabilityTokenSubclass.java
Labels: Performance, Capabilities, LTS, Queued, 1.21

#10279 chore(deps): update jline for better darwin/arm64 support
  settings.gradle
Labels: Triage, LTS, 1.21

#10281 backport[1.21.3]: Update jline for better darwin/arm64 support
  settings.gradle
Labels: Triage, LTS, 1.21

#10282 backport[1.21.1]: Update jline for better darwin/arm64 support
  settings.gradle
Labels: Triage, LTS, 1.21

#10271 [1.21.4] Forge CoreMods cleanup
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/BytecodePredicateFinder.groovy
  build_forge.gradle
  src/main/resources/coremods/field_to_method.js
  src/main/resources/coremods/finalize_spawn_targets.json
  src/main/resources/coremods/method_redirector.js
Labels: Bug, Regression, Cleanup, LTS, 1.21

#10159 [1.21.3] Forge CoreMods cleanup
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/BytecodePredicateFinder.groovy
  build_forge.gradle
  src/main/resources/coremods/field_to_method.js
  src/main/resources/coremods/finalize_spawn_targets.json
  src/main/resources/coremods/method_redirector.js
Labels: Bug, Regression, Cleanup, Triage, LTS, 1.21
