Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-07, with the labels that each got.

#10036 [1.20.4] Unlock wrapped registries when firing register events.
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
Labels: Triage, 1.20

#10035 [1.20.1] Unlock wrapped registries when firing register events.
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
Labels: Triage, 1.20

#10034 [1.19.x] Unlock wrapped registries when firing register events.
  src/main/java/net/minecraftforge/registries/ForgeRegistry.java
Labels: Triage, LTS, 1.19

#10019 [1.19.4] Fixed falling block entities not rendering as moving blocks
  patches/minecraft/net/minecraft/client/renderer/entity/FallingBlockRenderer.java.patch
Labels: Triage, LTS, 1.19

#10025 [1.19.2] Choose default JarJar mod file type based on parent JAR
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
Labels: Triage, LTS, 1.19

#10024 [1.19.4] Choose default JarJar mod file type based on parent JAR
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
Labels: Triage, LTS, 1.19

#10020 [1.19.2] Fixed falling block entities not rendering as moving blocks
  patches/minecraft/net/minecraft/client/renderer/entity/FallingBlockRenderer.java.patch
Labels: Triage, LTS, 1.19

#10026 [1.18.2] Choose default JarJar mod file type based on parent JAR
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/JarInJarDependencyLocator.java
Labels: Triage, 1.18

#10038 Extensible HangingSignBlockEntity for 1.20.1
  patches/minecraft/net/minecraft/world/level/block/entity/HangingSignBlockEntity.java.patch
Labels: Triage, 1.20

#10028 [1.21] Use the new methods in EventBus
  patches/minecraft/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
  patches/minecraft/net/minecraft/server/level/ServerPlayerGameMode.java.patch
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/Spider.java.patch
  patches/minecraft/net/minecraft/world/entity/monster/Zombie.java.patch
  patches/minecraft/net/minecraft/world/level/block/FungusBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/MushroomBlock.java.patch
  patches/minecraft/net/minecraft/world/level/block/grower/TreeGrower.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/PhantomSpawner.java.patch
  settings.gradle
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Cleanup, Triage, LTS, 1.21

#10050 [1.21] Fix matrix stack translations for `RenderHighlightEvent`
  patches/minecraft/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: Assigned, LTS, 1.21

#10047 [1.21] Fix `onPlaceItemIntoWorld` always resetting item stack when in creative mode
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Assigned, LTS, 1.21

#10051 [1.20.6] Fix matrix stack translations for `RenderHighlightEvent`
  patches/minecraft/net/minecraft/client/renderer/LevelRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: Assigned, 1.20

#10048 [1.20.6] Fix `onPlaceItemIntoWorld` always resetting item stack when in creative mode
  src/main/java/net/minecraftforge/common/ForgeHooks.java
Labels: Assigned, 1.20

#10044 Patch CropBlock#mayPlaceOn to use instanceOf FarmBlock check instead of hard coding to Blocks.FARMLAND
  patches/minecraft/net/minecraft/world/level/block/CropBlock.java.patch
Labels: Assigned, LTS, 1.21
