Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-11, with the labels that each got.

#10125 Add proper support for JPMS in normal mods.toml mods
  fmlearlydisplay/src/main/java/net/minecraftforge/fml/earlydisplay/DisplayWindow.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/ImmediateWindowHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/UniqueModListBuilder.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/AbstractModProvider.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/MinecraftLocator.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFileInfo.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModJarMetadata.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/CommonLaunchHandler.java
  fmlloader/src/main/java/net/minecraftforge/fml/loading/targets/ForgeDevLocator.java
  javafmllanguage/build.gradle
  javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
  src/generated_test/resources/criterion_test/data/criterion_test/advancements/break_glass_with_fish.json
  src/generated_test/resources/criterion_test/data/criterion_test/tags/items/fish.json
  src/main/java/net/minecraftforge/gametest/ForgeGameTestHooks.java
  src/test/generated/closed_module/module-info.dat
  src/test/generated/closed_module_test/META-INF/MANIFEST.MF
  src/test/generated/closed_module_test/module-info.dat
  src/test/generated/criterion_test/data/criterion_test/advancement/break_glass_with_fish.json
  src/test/java/net/minecraftforge/debug/gameplay/crafting/TagsTest.java
  src/test/java/net/minecraftforge/debug/modules/automatic/AutomaticModuleMod.java
  src/test/java/net/minecraftforge/debug/modules/closed/ClosedMod.java
  src/test/java/net/minecraftforge/debug/modules/closed/api/PublicUtils.java
  src/test/java/net/minecraftforge/debug/modules/closed/internala/InternalA.java
  src/test/java/net/minecraftforge/debug/modules/closed/internalb/InternalB.java
  src/test/java/net/minecraftforge/debug/modules/closedtest/ClosedTestsMod.java
  src/test/java/net/minecraftforge/test/ManifestProvider.java
  src/test/java/net/minecraftforge/test/ModuleProvider.java
  src/test/resources/automatic_module/META-INF/MANIFEST.MF
Labels: Feature, Assigned, LTS, 1.21

#10167 Fix PlayerRenderer#render invoking RenderLivingEvent and not RenderPlayerEvent
  patches/minecraft/net/minecraft/client/renderer/entity/player/PlayerRenderer.java.patch
Labels: Bug, Assigned, LTS, 1.21

#10156 [1.21.3] Bump CoreMods to 5.2
  settings.gradle
Labels: Regression, Feature, Triage, 1.21

#10160 [1.21.1] Bump CoreMods to 5.2
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
  settings.gradle
Labels: Regression, Feature, Triage, 1.21

#10161 [1.20.6] Bump CoreMods to 5.2
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
  settings.gradle
Labels: Regression, Feature, Triage, 1.20

#10129 [1.20.4] Bump CoreMods to 5.2
  build_shared.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
  settings.gradle
Labels: Feature, Triage, 1.20

#10130 [1.20.1] Bump CoreMods to 5.2
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
Labels: Feature, Triage, 1.20

#10131 [1.19.4] Bump CoreMods to 5.2
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
Labels: Feature, Triage, 1.19

#10151 [1.21.1] Add optional fix of use item duration, disabled by default
  patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch
  src/main/java/net/minecraftforge/common/ForgeConfig.java
  src/main/java/net/minecraftforge/event/entity/living/LivingEntityUseItemEvent.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, LTS, 1.21

#10132 [1.19.2] Bump CoreMods to 5.2
  build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
Labels: Feature, Triage, 1.19

#10133 [1.18.2] Bump CoreMods to 5.2
  build.gradle
  fmlloader/build.gradle
  fmlloader/src/main/java/net/minecraftforge/fml/loading/FMLLoader.java
Labels: Feature, Triage, 1.18

#10170 [1.21.3] Pass player argument when firing `OnDatapackSyncEvent`
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
Labels: Assigned, LTS, 1.21

#10171 [1.21.1] Pass player argument when firing `OnDatapackSyncEvent`
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
Labels: Assigned, LTS, 1.21

#10172 [1.20.6] Pass player argument when firing `OnDatapackSyncEvent`
  patches/minecraft/net/minecraft/server/players/PlayerList.java.patch
Labels: Assigned, 1.20

#10187 [1.19.4] Bump JNA to 5.12.1
  build.gradle
Labels: Triage, 1.19

#10188 [1.18.2] Bump JNA to 5.12.1
  build.gradle
Labels: Triage, 1.18
