Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-04, with the labels that each got.

#9897 [1.20.1] Bump CoreMods and ASM
  build.gradle
  docs/README.md
  mdk/README.txt
Labels: Bug, Regression, Assigned, 1.20

#9889 [1.20.1] Add Leaves method to ModelProvider.java (BackPort of #9887)
  src/main/java/net/minecraftforge/client/model/generators/ModelProvider.java
Labels: Assigned, 1.20

#9898 [1.19.4] Bump CoreMods and ASM
  build.gradle
  docs/README.md
Labels: Bug, Regression, Assigned, LTS, 1.19
