Repository MinecraftForge/MinecraftForge, pull requests merged in 2024-05, with the labels that each got.

#9962 [1.20.6] Add ModelLayers patch back
  patches/minecraft/net/minecraft/client/model/geom/ModelLayers.java.patch
Labels: Triage, 1.20

#9959 Update SimpleChannel to make StreamCodecs easier
  fmlcore/src/main/java/net/minecraftforge/fml/LogicalSide.java
  patches/minecraft/net/minecraft/network/FriendlyByteBuf.java.patch
  patches/minecraft/net/minecraft/network/RegistryFriendlyByteBuf.java.patch
  patches/minecraft/net/minecraft/network/protocol/common/custom/DiscardedPayload.java.patch
  patches/minecraft/net/minecraft/network/protocol/login/ClientboundCustomQueryPacket.java.patch
  patches/minecraft/net/minecraft/network/protocol/login/ServerboundCustomQueryAnswerPacket.java.patch
  patches/minecraft/net/minecraft/network/protocol/login/custom/DiscardedQueryAnswerPayload.java.patch
  patches/minecraft/net/minecraft/network/protocol/login/custom/DiscardedQueryPayload.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/util/LogicalSidedProvider.java
  src/main/java/net/minecraftforge/common/util/PacketLogger.java
  src/main/java/net/minecraftforge/event/network/CustomPayloadEvent.java
  src/main/java/net/minecraftforge/network/Channel.java
  src/main/java/net/minecraftforge/network/EventNetworkChannel.java
  src/main/java/net/minecraftforge/network/ForgePacketHandler.java
  src/main/java/net/minecraftforge/network/ICustomPacket.java
  src/main/java/net/minecraftforge/network/NetworkDirection.java
  src/main/java/net/minecraftforge/network/NetworkInitialization.java
  src/main/java/net/minecraftforge/network/NetworkInstance.java
  src/main/java/net/minecraftforge/network/NetworkProtocol.java
  src/main/java/net/minecraftforge/network/PacketDistributor.java
  src/main/java/net/minecraftforge/network/SimpleChannel.java
  src/main/java/net/minecraftforge/network/packets/Acknowledge.java
  src/main/java/net/minecraftforge/network/packets/ChannelVersions.java
  src/main/java/net/minecraftforge/network/packets/ConfigData.java
  src/main/java/net/minecraftforge/network/packets/LoginWrapper.java
  src/main/java/net/minecraftforge/network/packets/MismatchData.java
  src/main/java/net/minecraftforge/network/packets/ModVersions.java
  src/main/java/net/minecraftforge/network/packets/OpenContainer.java
  src/main/java/net/minecraftforge/network/packets/RegistryData.java
  src/main/java/net/minecraftforge/network/packets/RegistryList.java
  src/main/java/net/minecraftforge/network/packets/SpawnEntity.java
  src/main/java/net/minecraftforge/network/simple/BaseProtocol.java
  src/main/java/net/minecraftforge/network/simple/SimpleBuildable.java
  src/main/java/net/minecraftforge/network/simple/SimpleConnection.java
  src/main/java/net/minecraftforge/network/simple/SimpleFlow.java
  src/main/java/net/minecraftforge/network/simple/SimpleProtocol.java
  src/main/java/net/minecraftforge/network/simple/handler/SimpleHandlerFlow.java
  src/main/java/net/minecraftforge/network/simple/handler/SimpleHandlerProtocol.java
  src/main/java/net/minecraftforge/network/simple/handler/SimplePacket.java
  src/main/java/net/minecraftforge/network/tasks/ChannelVersionsTask.java
  src/main/java/net/minecraftforge/network/tasks/ModVersionsTask.java
  src/main/java/net/minecraftforge/network/tasks/SyncConfigTask.java
  src/main/java/net/minecraftforge/network/tasks/SyncRegistriesTask.java
Labels: Triage, 1.20

#9944 [1.20.6] Add GatherItemComponentsEvent
  build_forge.gradle
  patches/minecraft/net/minecraft/world/item/Item.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
  src/main/java/net/minecraftforge/event/GatherComponentsEvent.java
  src/test/java/net/minecraftforge/debug/gameplay/item/GatherComponentsEventTest.java
Labels: Feature, New Event, Triage, 1.20

#9978 [1.20.6]: Fixes screen layering and re-add the test.
  patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/test/java/net/minecraftforge/debug/client/GuiLayeringTest.java
Labels: Triage, 1.20

#9977 Fix RenderHandEvent firing with incorrect InteractionHand
  patches/minecraft/net/minecraft/client/renderer/ItemInHandRenderer.java.patch
Labels: Triage, 1.20

#9980 [1.20.6] Fix Biome Decoration Crash.
  build_forge.gradle
  patches/minecraft/net/minecraft/world/level/chunk/ChunkGenerator.java.patch
  src/main/java/net/minecraftforge/common/util/ClearableLazy.java
  src/main/java/net/minecraftforge/server/ServerLifecycleHooks.java
  src/test/generated/biome_test_mod/data/biome_test_mod/forge/biome_modifier/add_overworld_netherite_block_ore.json
  src/test/generated/biome_test_mod/data/biome_test_mod/worldgen/configured_feature/overworld_netherite_block_ore.json
  src/test/generated/biome_test_mod/data/biome_test_mod/worldgen/placed_feature/overworld_netherite_block_ore_placed.json
  src/test/java/net/minecraftforge/debug/gameplay/biome/BiomeTestMod.java
Labels: Bug, Triage, 1.20

#9982 [1.20.6]: re-add the customize debug and chat events
  patches/minecraft/net/minecraft/client/gui/Gui.java.patch
  patches/minecraft/net/minecraft/client/gui/components/DebugScreenOverlay.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/event/CustomizeGuiOverlayEvent.java
  src/test/java/net/minecraftforge/debug/client/CustomizeGuiOverlayEventTest.java
Labels: Assigned, 1.20
