Repository MinecraftForge/MinecraftForge, pull requests merged in 2025-05, with the labels that each got.

#10551 Fix creative inventory not displaying item categories correctly.
  patches/minecraft/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.java.patch
Labels: Triage, 1.21

#10554 Ensure changes from keyboard in ForgeSlider behave as changes from mouse
  src/main/java/net/minecraftforge/client/gui/widget/ForgeSlider.java
Labels: Triage, LTS, 1.21

#10521 Make Loot Function without builders Constructors public
  src/main/resources/META-INF/accesstransformer.cfg
Labels: Assigned, 1.21

#10544 Fix warped and crimson fungi not being able to be placed on nylium.
  patches/minecraft/net/minecraft/core/BlockPos.java.patch
  patches/minecraft/net/minecraft/world/level/block/Block.java.patch
  patches/minecraft/net/minecraft/world/level/levelgen/structure/templatesystem/StructureTemplateManager.java.patch
  src/main/java/net/minecraftforge/common/ForgeHooks.java
  src/main/java/net/minecraftforge/common/IPlantable.java
  src/main/java/net/minecraftforge/common/PlantType.java
  src/main/java/net/minecraftforge/common/extensions/IForgeBlockPos.java
  src/main/resources/data/forge/structure/empty3x3x3.nbt
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/bamboo.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/cactus.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/cactus_flower.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/coverage.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/dry_vegitation.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/farmland.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/fungus.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/mushroom.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/nether_fungus.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/nether_vegitation.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/netherwart.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/sugarcane.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/vegitation.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/vegitation_and_clay.json
  src/test/generated/plant_type_placement/data/forge/test_instance/plant_type_placement/withrose.json
  src/test/java/net/minecraftforge/debug/gameplay/block/PlantTypePlacementTest.java
  src/test/java/net/minecraftforge/test/BaseTestMod.java
Labels: Triage, LTS, 1.21
