Repository MinecraftForge/MinecraftForge, pull requests merged in 2025-01, with the labels that each got.

#10287 [1.21.4] Simplify Title Screen Brandings
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/internal/BrandingControl.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Assigned, LTS, 1.21

#10288 [1.21.3] Simplify Title Screen Brandings
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/internal/BrandingControl.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, LTS, 1.21

#10289 [1.21.1] Simplify Title Screen Brandings
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/internal/BrandingControl.java
  src/main/resources/assets/forge/lang/en_us.json
Labels: Triage, LTS, 1.21

#10290 [1.20.4] Add a way to render tooltips from Formatted text and TooltipComponents elements
  patches/minecraft/net/minecraft/client/gui/GuiGraphics.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: Triage, 1.20

#10291 [1.20.6] Add a way to render tooltips from Formatted text and TooltipComponents elements
  patches/minecraft/net/minecraft/client/gui/GuiGraphics.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
Labels: Triage, 1.20

#10292 [1.20.4] Fix boat travel distance being incorrect
  patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
Labels: Triage, 1.20

#10295 Fix render_type in block models not being used. Fixes #10294
  patches/minecraft/net/minecraft/client/renderer/block/model/BlockModel.java.patch
  patches/minecraft/net/minecraft/client/resources/model/ModelBaker.java.patch
  patches/minecraft/net/minecraft/client/resources/model/SimpleBakedModel.java.patch
  src/main/java/net/minecraftforge/client/ForgeHooksClient.java
  src/main/java/net/minecraftforge/client/model/CompositeModel.java
  src/main/java/net/minecraftforge/client/model/IModelBuilder.java
  src/main/java/net/minecraftforge/client/model/SimpleModelState.java
  src/main/java/net/minecraftforge/client/model/geometry/IGeometryBakingContext.java
  src/main/java/net/minecraftforge/client/model/geometry/SimpleUnbakedGeometry.java
  src/main/resources/META-INF/accesstransformer.cfg
  src/test/generated/model_render_type/assets/model_render_type/blockstates/cutout_block.json
  src/test/generated/model_render_type/assets/model_render_type/items/cutout_block.json
  src/test/generated/model_render_type/assets/model_render_type/models/block/cutout_block.json
  src/test/generated/model_render_type/assets/model_render_type/models/item/cutout_block.json
  src/test/java/net/minecraftforge/debug/client/AdditionalModelTest.java
  src/test/java/net/minecraftforge/debug/client/ModelRenderLayerTest.java
Labels: Triage, LTS, 1.21

#10298 Patch VillagerTrades.EmeraldsForVillagerTypeItem to allow modders to make custom Villager Types, Add VillagerType#registerBiomeType
  patches/minecraft/net/minecraft/world/entity/npc/VillagerTrades.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/VillagerType.java.patch
  src/test/java/net/minecraftforge/debug/gameplay/villager/VillagerTypeTestMod.java
Labels: Triage, LTS, 1.21

#10302 [1.20.4] Fix finalizeSpawn's return value not being used correctly
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: Triage, 1.20

#10303 [1.20.4] Gate non-passenger entity ticking behind canUpdate()
  patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch
Labels: Triage, 1.20

#10301 [1.20.1] Fix finalizeSpawn's return value not being used correctly
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: Triage, 1.20

#10304 [1.20.1] Gate non-passenger entity ticking behind canUpdate()
  patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch
Labels: Triage, 1.20

#10308 [1.19.4] Fix finalizeSpawn's return value not being used correctly
  src/main/java/net/minecraftforge/event/ForgeEventFactory.java
Labels: Triage, LTS, 1.19

#10306 [1.19.2] Gate non-passenger entity ticking behind canUpdate()
  patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch
Labels: Triage, 1.19

#10307 [1.18.2] Gate non-passenger entity ticking behind canUpdate()
  patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch
Labels: Triage, 1.18

#10338 [1.21.4] GameTestHelper additions
  patches/minecraft/net/minecraft/gametest/framework/GameTestHelper.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeGameTestHelper.java
Labels: Triage, LTS, 1.21

#10347 [1.21.4] Fix JOpt Simple for real this time
  settings.gradle
Labels: Triage, LTS, 1.21

#10352 [1.21.4] Update Gradle and MDK
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  mdk/build.gradle
Labels: Triage, LTS, 1.21

#10348 [1.21.3] Fix JOpt Simple for real this time
  settings.gradle
Labels: Triage, LTS, 1.21

#10353 [1.21.3] Update Gradle and MDK
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  mdk/build.gradle
Labels: Triage, LTS, 1.21

#10339 [1.21.3] GameTestHelper additions
  patches/minecraft/net/minecraft/gametest/framework/GameTestHelper.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeGameTestHelper.java
Labels: Triage, LTS, 1.21

#10349 [1.21.1] Fix JOpt Simple for real this time
  settings.gradle
Labels: Triage, LTS, 1.21

#10354 [1.21.1] Update Gradle and MDK
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/BytecodePredicateFinder.groovy
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  mdk/build.gradle
Labels: Triage, LTS, 1.21

#10340 [1.21.1] GameTestHelper additions
  patches/minecraft/net/minecraft/gametest/framework/GameTestHelper.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeGameTestHelper.java
Labels: Triage, LTS, 1.21

#10350 [1.20.6] Fix JOpt Simple for real this time
  settings.gradle
Labels: Triage, 1.20

#10355 [1.20.6] Update Gradle and MDK
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/BytecodePredicateFinder.groovy
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  mdk/build.gradle
Labels: Triage, 1.20

#10341 [1.20.6] GameTestHelper additions
  patches/minecraft/net/minecraft/gametest/framework/GameTestHelper.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeGameTestHelper.java
Labels: Triage, 1.20

#10343 [1.20.4] GameTestHelper additions
  patches/minecraft/net/minecraft/gametest/framework/GameTestHelper.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeGameTestHelper.java
Labels: Triage, 1.20

#10356 [1.20.4] Update Gradle and MDK
  buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/BytecodePredicateFinder.groovy
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  mdk/build.gradle
Labels: Triage, 1.20

#10316 [1.21.4] Fix shield disabling being completely ignored
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  patches/minecraft/net/minecraft/world/item/AxeItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/test/java/net/minecraftforge/debug/gameplay/item/ShieldDisablingTest.java
Labels: Bug, Triage, LTS, 1.21

#10357 [1.21.3] Patch VillagerTrades.EmeraldsForVillagerTypeItem to allow modders to make custom Villager Types, Add VillagerType#registerBiomeType
  patches/minecraft/net/minecraft/world/entity/npc/VillagerTrades.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/VillagerType.java.patch
  src/test/java/net/minecraftforge/debug/gameplay/villager/VillagerTypeTestMod.java
Labels: Triage, LTS, 1.21

#10317 [1.21.3] Fix shield disabling being completely ignored
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  patches/minecraft/net/minecraft/world/item/AxeItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/test/java/net/minecraftforge/debug/gameplay/item/ShieldDisablingTest.java
Labels: Triage, LTS, 1.21

#10300 [1.21.1] Backport of #10298
  patches/minecraft/net/minecraft/world/entity/npc/VillagerTrades.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/VillagerType.java.patch
  src/test/java/net/minecraftforge/debug/gameplay/villager/VillagerTypeTestMod.java
Labels: Assigned, LTS, Queued, 1.21

#10318 [1.21.1] Honor attacker shield disabling status
  patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
  patches/minecraft/net/minecraft/world/item/AxeItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/test/java/net/minecraftforge/debug/gameplay/item/ShieldDisablingTest.java
Labels: Triage, LTS, 1.21

#10310 [1.20.6] Backport of #10298
  patches/minecraft/net/minecraft/world/entity/npc/VillagerTrades.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/VillagerType.java.patch
  src/test/java/net/minecraftforge/debug/gameplay/villager/VillagerTypeTestMod.java
Labels: Assigned, LTS, 1.20, Queued

#10319 [1.20.6] Honor attacker shield disabling status
  patches/minecraft/net/minecraft/world/item/AxeItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/test/java/net/minecraftforge/debug/gameplay/item/ShieldDisablingTest.java
Labels: Triage, LTS, 1.20

#10358 [1.20.4] Patch VillagerTrades.EmeraldsForVillagerTypeItem to allow modders to make custom Villager Types, Add VillagerType#registerBiomeType
  patches/minecraft/net/minecraft/world/entity/npc/VillagerTrades.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/VillagerType.java.patch
  src/test/java/net/minecraftforge/debug/gameplay/villager/VillagerTypeTestMod.java
Labels: Triage, 1.20

#10320 [1.20.4] Honor attacker shield disabling status
  patches/minecraft/net/minecraft/world/item/AxeItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeGameTestHelper.java
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
  src/test/java/net/minecraftforge/debug/gameplay/item/ShieldDisablingTest.java
Labels: Triage, LTS, 1.20

#10315 [1.20.1] Backport of #10298
  patches/minecraft/net/minecraft/world/entity/npc/VillagerTrades.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/VillagerType.java.patch
Labels: Triage, LTS, 1.20

#10331 [1.20.1] Fix incorrect method reference in TntBlock.explode()
  patches/minecraft/net/minecraft/world/level/block/TntBlock.java.patch
Labels: Triage, LTS, 1.20

#10322 [1.19.4] Honor attacker shield disabling status
  patches/minecraft/net/minecraft/world/item/AxeItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
Labels: Triage, 1.19

#10332 [1.19.4] Fix incorrect method reference in TntBlock.explode()
  patches/minecraft/net/minecraft/world/level/block/TntBlock.java.patch
Labels: Triage, 1.19

#10359 [1.19.4] Patch VillagerTrades.EmeraldsForVillagerTypeItem to allow modders to make custom Villager Types, Add VillagerType#registerBiomeType
  patches/minecraft/net/minecraft/world/entity/npc/VillagerTrades.java.patch
  patches/minecraft/net/minecraft/world/entity/npc/VillagerType.java.patch
Labels: Triage, LTS, 1.19

#10323 [1.19.2] Honor attacker shield disabling status
  patches/minecraft/net/minecraft/world/item/AxeItem.java.patch
  src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
Labels: Triage, 1.19

#10333 [1.19.2] Fix incorrect method reference in TntBlock.explode()
  patches/minecraft/net/minecraft/world/level/block/TntBlock.java.patch
Labels: Triage, 1.19

#10334 [1.18.2] Fix incorrect method reference in TntBlock.explode()
  patches/minecraft/net/minecraft/world/level/block/TntBlock.java.patch
Labels: Triage, 1.18
