Repository MinecraftForge/MinecraftForge, pull requests merged in 2025-08, with the labels that each got.

#10582 [1.21.4] Update MDK to fix OOM error and Mixin
  mdk/build.gradle
  mdk/gradle.properties
  mdk/settings.gradle
Labels: Triage, LTS, 1.21

#10600 Update GradleUtils to 2.6.4
  build.gradle
  build_forge.gradle
Labels: Triage, LTS, 1.21

#10594 [1.21.1] Allow command suggestions/autocomplete to search all modded paths at once without namespace provided
  patches/minecraft/net/minecraft/commands/SharedSuggestionProvider.java.patch
Labels: Triage, LTS, 1.21

#10597 [1.21.8] Minor cleanup to FML, fix double parsing of mods.toml
  fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java
  mclanguage/src/main/java/net/minecraftforge/fml/mclanguageprovider/MinecraftModContainer.java
  mclanguage/src/main/java/net/minecraftforge/fml/mclanguageprovider/MinecraftModLanguageProvider.java
Labels: Triage, LTS, 1.21

#10646 Ignore item equality when checking `IForgeItemStack#shouldCauseBlockBreakReset`
  patches/minecraft/net/minecraft/client/multiplayer/MultiPlayerGameMode.java.patch
Labels: Triage, 1.20

#10644 [1.21.5] Update to EventBus 6.2.32
  settings.gradle
  src/main/java/net/minecraftforge/common/ForgeInternalHandler.java
  src/main/java/net/minecraftforge/common/MinecraftForge.java
Labels: Performance, Feature, Triage, LTS, 1.21
